// @vitest-environment jsdom
import React from 'react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {act,cleanup,fireEvent,render,screen,within} from '@testing-library/react';
import {App} from './App.jsx';
import {Picture} from './HubShared.jsx';
beforeEach(()=>{vi.spyOn(HTMLMediaElement.prototype,'play').mockResolvedValue();vi.spyOn(HTMLMediaElement.prototype,'pause').mockImplementation(()=>{});});
afterEach(()=>{cleanup();window.history.replaceState(null,'','#welcome');vi.restoreAllMocks();});
function page(hash){window.history.replaceState(null,'',hash);return render(<App/>);}
it('keeps the archive illustration browser with the introduction before the featured story list',()=>{page('#welcome');const ribbon=screen.getByRole('region',{name:'삽화로 만나는 이야기'});const featured=screen.getByRole('link',{name:/01 통역 필경사가/});expect(ribbon.compareDocumentPosition(featured)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();});
it('connects completed home sections to real pages',()=>{page('#welcome');expect(screen.getByRole('link',{name:/모든 이야기 만나보기/}).getAttribute('href')).toBe('#/stories');expect(screen.getByRole('link',{name:/첫 장면 고르기/}).getAttribute('href')).toBe('#/start');});
it('opens the original story with separate reading help',()=>{page('#/story/ini-com-02');expect(screen.getByRole('heading',{name:'같은 땅, 두 이름',level:1})).toBeTruthy();expect(document.querySelector('.story-original').textContent.length).toBeGreaterThan(500);expect(screen.getByText('낯선 말, 함께 알아봐요')).toBeTruthy();});
it('filters people and provides a reset after empty results',()=>{page('#/people');fireEvent.change(screen.getByLabelText('인물 이름 또는 하는 일'),{target:{value:'없는사람가나다'}});expect(screen.getByText('아직 그 이름을 찾지 못했어요.')).toBeTruthy();fireEvent.click(screen.getAllByRole('button',{name:'조건 지우기'})[0]);expect(screen.getByText('100명의 사람을 만날 수 있어요.')).toBeTruthy();});
it('links country places and the next introductory chapter',()=>{page('#/region/tiris');expect(screen.getByRole('heading',{level:1,name:'티리스'})).toBeTruthy();expect(screen.getAllByRole('link').some(a=>a.getAttribute('href')?.startsWith('#/place/'))).toBe(true);cleanup();page('#/guide/first');expect(screen.getByRole('link',{name:/다음 이야기/}).getAttribute('href')).toBe('#/guide/daily');});
it('searches ordinary place names and restores search opener focus',()=>{page('#welcome');const trigger=screen.getByRole('button',{name:'검색 안내'});trigger.focus();fireEvent.click(trigger);const dialog=screen.getByRole('dialog');fireEvent.change(within(dialog).getByLabelText('궁금한 이름'),{target:{value:'레이븐스톤'}});expect(within(dialog).getAllByRole('link').some(a=>a.getAttribute('href')?.startsWith('#/place/'))).toBe(true);fireEvent.keyDown(document,{key:'Escape'});expect(screen.queryByRole('dialog')).toBeNull();expect(document.activeElement).toBe(trigger);});
it('offers recovery for an unknown deep link',()=>{page('#/person/missing');expect(screen.getByRole('heading',{name:'길을 조금 벗어났네요'})).toBeTruthy();expect(screen.getByRole('link',{name:'처음으로 돌아가기'})).toBeTruthy();});
it('provides a readable fallback when an image cannot load',()=>{render(<Picture src="/missing.webp" alt="검수 그림"/>);fireEvent.error(screen.getByRole('img',{name:'검수 그림'}));expect(screen.getByText('그림을 잠시 불러오지 못했어요.')).toBeTruthy();});
it('synchronizes filters when navigating to another query on the same catalog',()=>{page('#/people?q=베켈');expect(screen.getByLabelText('인물 이름 또는 하는 일').value).toBe('베켈');act(()=>{window.history.replaceState(null,'','#/people?q=아렐');window.dispatchEvent(new HashChangeEvent('hashchange'));});expect(screen.getByLabelText('인물 이름 또는 하는 일').value).toBe('아렐');});
it('respects a search category even before a query is entered',()=>{page('#welcome');fireEvent.click(screen.getByRole('button',{name:'검색 안내'}));const dialog=screen.getByRole('dialog');fireEvent.click(within(dialog).getByRole('button',{name:'인물',exact:true}));expect(within(dialog).getAllByRole('link').every(a=>a.getAttribute('href').startsWith('#/person/'))).toBe(true);});
it('honors reduced motion when paging through people',()=>{page('#/people');const scroll=vi.fn();document.querySelector('.catalog-filters').scrollIntoView=scroll;const previous=window.matchMedia;window.matchMedia=()=>({matches:true,addEventListener(){},removeEventListener(){}});fireEvent.click(screen.getByRole('button',{name:'2',exact:true}));expect(scroll).toHaveBeenCalledWith({block:'start',behavior:'instant'});window.matchMedia=previous;});
