// @vitest-environment jsdom
import React from 'react';
import {act,cleanup,fireEvent,render,screen} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {HomeSections} from './HomeSections.jsx';
beforeEach(()=>{vi.useFakeTimers();vi.spyOn(HTMLMediaElement.prototype,'play').mockResolvedValue();vi.spyOn(HTMLMediaElement.prototype,'pause').mockImplementation(()=>{});});
afterEach(()=>{cleanup();vi.useRealTimers();vi.restoreAllMocks();vi.unstubAllGlobals();});
const selected=name=>document.querySelector('.person-feature-details h3')?.textContent===name?'true':'false';
it('removes the name-tab row while preserving the description and encyclopedia action',()=>{render(<HomeSections/>);expect(screen.queryByRole('group',{name:'먼저 만날 인물'})).toBeNull();expect(screen.getByText('어디에서 무슨 일을 하며 지낼까요?',{exact:false})).not.toBeNull();expect(screen.getByRole('link',{name:'인물대백과 펼치기'})).not.toBeNull();});
it('rotates the selected person after five seconds and wraps all three people',()=>{render(<HomeSections/>);expect(selected('베켈 오르민')).toBe('true');act(()=>vi.advanceTimersByTime(4999));expect(selected('베켈 오르민')).toBe('true');act(()=>vi.advanceTimersByTime(1));expect(selected('아렐 라드킨')).toBe('true');act(()=>vi.advanceTimersByTime(5000));expect(selected('벨리 헤드라')).toBe('true');act(()=>vi.advanceTimersByTime(5000));expect(selected('베켈 오르민')).toBe('true');});
it('pauses rotation on request and resumes after five seconds',()=>{render(<HomeSections/>);act(()=>vi.advanceTimersByTime(5000));fireEvent.click(screen.getByRole('button',{name:'자동 넘김 멈추기'}));act(()=>vi.advanceTimersByTime(6000));expect(selected('아렐 라드킨')).toBe('true');fireEvent.click(screen.getByRole('button',{name:'자동 넘김 시작하기'}));act(()=>vi.advanceTimersByTime(5000));expect(selected('벨리 헤드라')).toBe('true');});
it('keeps the outgoing portrait during exit, then returns it as the rear silhouette',()=>{render(<HomeSections/>);act(()=>vi.advanceTimersByTime(5000));expect(document.querySelector('[data-person="c012"]').dataset.pose).toBe('leaving');expect(document.querySelector('[data-person="c001"]').dataset.pose).toBe('active');expect(document.querySelector('[data-person="c027"]').dataset.pose).toBe('waiting');act(()=>vi.advanceTimersByTime(700));expect(document.querySelector('[data-person="c012"]').dataset.pose).toBe('rear');});
it('honors reduced motion without automatic rotation or video playback',()=>{vi.stubGlobal('matchMedia',()=>({matches:true,addEventListener(){},removeEventListener(){}}));render(<HomeSections/>);act(()=>vi.advanceTimersByTime(9000));expect(selected('베켈 오르민')).toBe('true');expect(document.querySelector('.people-feature').dataset.motion).toBe('false');expect(screen.getByRole('link',{name:'인물대백과 펼치기'})).not.toBeNull();expect(document.querySelector('[data-pose="leaving"]')).toBeNull();});
it('stops rotation when the page is hidden',()=>{render(<HomeSections/>);vi.spyOn(document,'hidden','get').mockReturnValue(true);fireEvent(document,new Event('visibilitychange'));act(()=>vi.advanceTimersByTime(6000));expect(selected('베켈 오르민')).toBe('true');});
it('runs only while its section is on screen and disconnects on unmount',()=>{const observations=[];vi.stubGlobal('IntersectionObserver',class{constructor(callback){this.callback=callback;}observe(element){observations.push({element,callback:this.callback,observer:this});}disconnect(){this.disconnected=true;}});const view=render(<HomeSections/>);const own=observations.find(o=>o.element.id==='people');act(()=>vi.advanceTimersByTime(6000));expect(selected('베켈 오르민')).toBe('true');act(()=>own.callback([{isIntersecting:true}]));act(()=>vi.advanceTimersByTime(5000));expect(selected('아렐 라드킨')).toBe('true');act(()=>own.callback([{isIntersecting:false}]));act(()=>vi.advanceTimersByTime(9000));expect(selected('아렐 라드킨')).toBe('true');view.unmount();expect(own.observer.disconnected).toBe(true);});
