// Generated by tools/sync_vireth_wiki_registry.mjs. Do not edit by hand.
export const GENERATED_WIKI_REGIONS = [
  {
    "id": "R001",
    "key": "leonia",
    "name": "레오니아",
    "aliases": [
      "leonia",
      "레오니아"
    ]
  },
  {
    "id": "R002",
    "key": "norghard",
    "name": "노르가르드",
    "aliases": [
      "norghard",
      "노르가르드"
    ]
  },
  {
    "id": "R003",
    "key": "tiris",
    "name": "티리스",
    "aliases": [
      "tiris",
      "티리스"
    ]
  },
  {
    "id": "R004",
    "key": "linrenet",
    "name": "린레네트",
    "aliases": [
      "linrenet",
      "린레네트"
    ]
  },
  {
    "id": "R005",
    "key": "bekdoret",
    "name": "벡도레트",
    "aliases": [
      "bekdoret",
      "벡도레트"
    ]
  },
  {
    "id": "R006",
    "key": "senhalet",
    "name": "센할레트",
    "aliases": [
      "senhalet",
      "센할레트"
    ]
  },
  {
    "id": "R007",
    "key": "hesferet",
    "name": "헤스페레트",
    "aliases": [
      "hesferet",
      "헤스페레트"
    ]
  },
  {
    "id": "R008",
    "key": "kelnabet",
    "name": "켈나베트",
    "aliases": [
      "kelnabet",
      "켈나베트"
    ]
  },
  {
    "id": "R009",
    "key": "hesbeket",
    "name": "헤스베케트",
    "aliases": [
      "hesbeket",
      "헤스베케트"
    ]
  },
  {
    "id": "R010",
    "key": "yenmebet",
    "name": "옌메베트",
    "aliases": [
      "yenmebet",
      "옌메베트"
    ]
  },
  {
    "id": "R011",
    "key": "nimnaret",
    "name": "님나레트",
    "aliases": [
      "nimnaret",
      "님나레트"
    ]
  },
  {
    "id": "R012",
    "key": "silnimet",
    "name": "실니메트",
    "aliases": [
      "silnimet",
      "실니메트"
    ]
  },
  {
    "id": "R013",
    "key": "ardolet",
    "name": "아르도레트",
    "aliases": [
      "ardolet",
      "아르도레트"
    ]
  },
  {
    "id": "R014",
    "key": "garmebet",
    "name": "가르메베트",
    "aliases": [
      "garmebet",
      "가르메베트"
    ]
  },
  {
    "id": "R015",
    "key": "silhalet",
    "name": "실할레트",
    "aliases": [
      "silhalet",
      "실할레트"
    ]
  },
  {
    "id": "R016",
    "key": "merhalet",
    "name": "메르할레트",
    "aliases": [
      "merhalet",
      "메르할레트"
    ]
  },
  {
    "id": "R017",
    "key": "nimsolet",
    "name": "님소레트",
    "aliases": [
      "nimsolet",
      "님소레트"
    ]
  },
  {
    "id": "R018",
    "key": "sylvania",
    "name": "실바니아",
    "aliases": [
      "sylvania",
      "실바니아"
    ]
  },
  {
    "id": "R019",
    "key": "dragonspire",
    "name": "드래곤스파이어",
    "aliases": [
      "dragonspire",
      "드래곤스파이어"
    ]
  },
  {
    "id": "R020",
    "key": "fenrir-s-eye",
    "name": "펜리르의 눈",
    "aliases": [
      "fenrir-s-eye",
      "펜리르의 눈",
      "fenrir-eye",
      "펜리르"
    ]
  }
] as const;

export const GENERATED_WIKI_PLACES = [
  {
    "id": "L001",
    "regionId": "R001",
    "regionKey": "leonia",
    "regionName": "레오니아",
    "name": "렘다트움",
    "aliases": [
      "렘다트움"
    ],
    "kind": "도시·거점",
    "order": 1
  },
  {
    "id": "L002",
    "regionId": "R001",
    "regionKey": "leonia",
    "regionName": "레오니아",
    "name": "라드아르할",
    "aliases": [
      "라드아르할"
    ],
    "kind": "도시·거점",
    "order": 2
  },
  {
    "id": "L003",
    "regionId": "R001",
    "regionKey": "leonia",
    "regionName": "레오니아",
    "name": "렘켈가",
    "aliases": [
      "렘켈가"
    ],
    "kind": "숙소촌",
    "order": 3
  },
  {
    "id": "L004",
    "regionId": "R001",
    "regionKey": "leonia",
    "regionName": "레오니아",
    "name": "지르바르에트",
    "aliases": [
      "지르바르에트"
    ],
    "kind": "도시·거점",
    "order": 4
  },
  {
    "id": "L005",
    "regionId": "R001",
    "regionKey": "leonia",
    "regionName": "레오니아",
    "name": "라드가르가",
    "aliases": [
      "라드가르가"
    ],
    "kind": "마을",
    "order": 5
  },
  {
    "id": "L006",
    "regionId": "R001",
    "regionKey": "leonia",
    "regionName": "레오니아",
    "name": "지르메브가",
    "aliases": [
      "지르메브가"
    ],
    "kind": "마을",
    "order": 6
  },
  {
    "id": "L007",
    "regionId": "R001",
    "regionKey": "leonia",
    "regionName": "레오니아",
    "name": "팔테쿰가",
    "aliases": [
      "팔테쿰가"
    ],
    "kind": "도시·거점",
    "order": 7
  },
  {
    "id": "L008",
    "regionId": "R001",
    "regionKey": "leonia",
    "regionName": "레오니아",
    "name": "팔테크가",
    "aliases": [
      "팔테크가"
    ],
    "kind": "작업촌",
    "order": 8
  },
  {
    "id": "L009",
    "regionId": "R002",
    "regionKey": "norghard",
    "regionName": "노르가르드",
    "name": "마르토르가",
    "aliases": [
      "마르토르가"
    ],
    "kind": "구조물 마을",
    "order": 1
  },
  {
    "id": "L010",
    "regionId": "R002",
    "regionKey": "norghard",
    "regionName": "노르가르드",
    "name": "아르마르토르",
    "aliases": [
      "아르마르토르"
    ],
    "kind": "도시·거점",
    "order": 2
  },
  {
    "id": "L011",
    "regionId": "R002",
    "regionKey": "norghard",
    "regionName": "노르가르드",
    "name": "마르나브미르",
    "aliases": [
      "마르나브미르"
    ],
    "kind": "도시·거점",
    "order": 3
  },
  {
    "id": "L012",
    "regionId": "R002",
    "regionKey": "norghard",
    "regionName": "노르가르드",
    "name": "헤스마르가",
    "aliases": [
      "헤스마르가"
    ],
    "kind": "어항",
    "order": 4
  },
  {
    "id": "L013",
    "regionId": "R002",
    "regionKey": "norghard",
    "regionName": "노르가르드",
    "name": "페르나브부두",
    "aliases": [
      "페르나브부두"
    ],
    "kind": "도시·거점",
    "order": 5
  },
  {
    "id": "L014",
    "regionId": "R002",
    "regionKey": "norghard",
    "regionName": "노르가르드",
    "name": "페르테크가",
    "aliases": [
      "페르테크가"
    ],
    "kind": "작업촌",
    "order": 6
  },
  {
    "id": "L015",
    "regionId": "R002",
    "regionKey": "norghard",
    "regionName": "노르가르드",
    "name": "나브할가",
    "aliases": [
      "나브할가"
    ],
    "kind": "도시·거점",
    "order": 7
  },
  {
    "id": "L016",
    "regionId": "R002",
    "regionKey": "norghard",
    "regionName": "노르가르드",
    "name": "나브할가린",
    "aliases": [
      "나브할가린"
    ],
    "kind": "숙소촌",
    "order": 8
  },
  {
    "id": "L017",
    "regionId": "R003",
    "regionKey": "tiris",
    "regionName": "티리스",
    "name": "실테크에트",
    "aliases": [
      "실테크에트"
    ],
    "kind": "도시·거점",
    "order": 1
  },
  {
    "id": "L018",
    "regionId": "R003",
    "regionKey": "tiris",
    "regionName": "티리스",
    "name": "실베크가",
    "aliases": [
      "실베크가"
    ],
    "kind": "마을",
    "order": 2
  },
  {
    "id": "L019",
    "regionId": "R003",
    "regionKey": "tiris",
    "regionName": "티리스",
    "name": "소르이엘토르",
    "aliases": [
      "소르이엘토르"
    ],
    "kind": "도시·거점",
    "order": 3
  },
  {
    "id": "L020",
    "regionId": "R003",
    "regionKey": "tiris",
    "regionName": "티리스",
    "name": "이엘토르가",
    "aliases": [
      "이엘토르가"
    ],
    "kind": "신전촌",
    "order": 4
  },
  {
    "id": "L021",
    "regionId": "R003",
    "regionKey": "tiris",
    "regionName": "티리스",
    "name": "라드바르할(실버킵)",
    "aliases": [
      "라드바르할(실버킵)"
    ],
    "kind": "도시·거점",
    "order": 5
  },
  {
    "id": "L022",
    "regionId": "R003",
    "regionKey": "tiris",
    "regionName": "티리스",
    "name": "베크켈카르(레이븐스톤)",
    "aliases": [
      "베크켈카르(레이븐스톤)"
    ],
    "kind": "도시·거점",
    "order": 6
  },
  {
    "id": "L023",
    "regionId": "R003",
    "regionKey": "tiris",
    "regionName": "티리스",
    "name": "베크벱가",
    "aliases": [
      "베크벱가"
    ],
    "kind": "피난촌",
    "order": 7
  },
  {
    "id": "L024",
    "regionId": "R003",
    "regionKey": "tiris",
    "regionName": "티리스",
    "name": "벨소르엘",
    "aliases": [
      "벨소르엘"
    ],
    "kind": "도시·거점",
    "order": 8
  },
  {
    "id": "L025",
    "regionId": "R003",
    "regionKey": "tiris",
    "regionName": "티리스",
    "name": "그린할로우",
    "aliases": [
      "그린할로우"
    ],
    "kind": "도시·거점",
    "order": 9
  },
  {
    "id": "L026",
    "regionId": "R003",
    "regionKey": "tiris",
    "regionName": "티리스",
    "name": "헤크가르가",
    "aliases": [
      "헤크가르가"
    ],
    "kind": "재개간촌",
    "order": 10
  },
  {
    "id": "L027",
    "regionId": "R003",
    "regionKey": "tiris",
    "regionName": "티리스",
    "name": "가르메브에트",
    "aliases": [
      "가르메브에트"
    ],
    "kind": "도시·거점",
    "order": 11
  },
  {
    "id": "L028",
    "regionId": "R003",
    "regionKey": "tiris",
    "regionName": "티리스",
    "name": "벨렐가",
    "aliases": [
      "벨렐가"
    ],
    "kind": "마을",
    "order": 12
  },
  {
    "id": "L029",
    "regionId": "R003",
    "regionKey": "tiris",
    "regionName": "티리스",
    "name": "가르푸크가",
    "aliases": [
      "가르푸크가"
    ],
    "kind": "마을",
    "order": 13
  },
  {
    "id": "L030",
    "regionId": "R003",
    "regionKey": "tiris",
    "regionName": "티리스",
    "name": "뉴할로우",
    "aliases": [
      "뉴할로우"
    ],
    "kind": "도시·거점",
    "order": 14
  },
  {
    "id": "L031",
    "regionId": "R004",
    "regionKey": "linrenet",
    "regionName": "린레네트",
    "name": "렘렌가",
    "aliases": [
      "렘렌가"
    ],
    "kind": "도시·거점",
    "order": 1
  },
  {
    "id": "L032",
    "regionId": "R004",
    "regionKey": "linrenet",
    "regionName": "린레네트",
    "name": "렘렌필가",
    "aliases": [
      "렘렌필가"
    ],
    "kind": "작업가",
    "order": 2
  },
  {
    "id": "L033",
    "regionId": "R004",
    "regionKey": "linrenet",
    "regionName": "린레네트",
    "name": "다트킨할",
    "aliases": [
      "다트킨할"
    ],
    "kind": "도시·거점",
    "order": 3
  },
  {
    "id": "L034",
    "regionId": "R004",
    "regionKey": "linrenet",
    "regionName": "린레네트",
    "name": "레눔가",
    "aliases": [
      "레눔가"
    ],
    "kind": "도시·거점",
    "order": 4
  },
  {
    "id": "L035",
    "regionId": "R004",
    "regionKey": "linrenet",
    "regionName": "린레네트",
    "name": "린산가",
    "aliases": [
      "린산가"
    ],
    "kind": "도시·거점",
    "order": 5
  },
  {
    "id": "L036",
    "regionId": "R004",
    "regionKey": "linrenet",
    "regionName": "린레네트",
    "name": "레눔숙가",
    "aliases": [
      "레눔숙가"
    ],
    "kind": "숙소가",
    "order": 6
  },
  {
    "id": "L037",
    "regionId": "R004",
    "regionKey": "linrenet",
    "regionName": "린레네트",
    "name": "님렌할",
    "aliases": [
      "님렌할"
    ],
    "kind": "도시·거점",
    "order": 7
  },
  {
    "id": "L038",
    "regionId": "R004",
    "regionKey": "linrenet",
    "regionName": "린레네트",
    "name": "린산테크가",
    "aliases": [
      "린산테크가"
    ],
    "kind": "작업촌",
    "order": 8
  },
  {
    "id": "L039",
    "regionId": "R005",
    "regionKey": "bekdoret",
    "regionName": "벡도레트",
    "name": "도르테쿰",
    "aliases": [
      "도르테쿰"
    ],
    "kind": "도시·거점",
    "order": 1
  },
  {
    "id": "L040",
    "regionId": "R005",
    "regionKey": "bekdoret",
    "regionName": "벡도레트",
    "name": "켈카르",
    "aliases": [
      "켈카르"
    ],
    "kind": "도시·거점",
    "order": 2
  },
  {
    "id": "L041",
    "regionId": "R005",
    "regionKey": "bekdoret",
    "regionName": "벡도레트",
    "name": "도르테크가",
    "aliases": [
      "도르테크가"
    ],
    "kind": "작업촌",
    "order": 3
  },
  {
    "id": "L042",
    "regionId": "R005",
    "regionKey": "bekdoret",
    "regionName": "벡도레트",
    "name": "도르카르",
    "aliases": [
      "도르카르"
    ],
    "kind": "도시·거점",
    "order": 4
  },
  {
    "id": "L043",
    "regionId": "R005",
    "regionKey": "bekdoret",
    "regionName": "벡도레트",
    "name": "켈베크가",
    "aliases": [
      "켈베크가"
    ],
    "kind": "관문촌",
    "order": 5
  },
  {
    "id": "L044",
    "regionId": "R005",
    "regionKey": "bekdoret",
    "regionName": "벡도레트",
    "name": "베크할",
    "aliases": [
      "베크할"
    ],
    "kind": "도시·거점",
    "order": 6
  },
  {
    "id": "L045",
    "regionId": "R005",
    "regionKey": "bekdoret",
    "regionName": "벡도레트",
    "name": "엔할가",
    "aliases": [
      "엔할가"
    ],
    "kind": "도시·거점",
    "order": 7
  },
  {
    "id": "L046",
    "regionId": "R005",
    "regionKey": "bekdoret",
    "regionName": "벡도레트",
    "name": "베크푸크가",
    "aliases": [
      "베크푸크가"
    ],
    "kind": "창고촌",
    "order": 8
  },
  {
    "id": "L047",
    "regionId": "R006",
    "regionKey": "senhalet",
    "regionName": "센할레트",
    "name": "센푸크에트",
    "aliases": [
      "센푸크에트"
    ],
    "kind": "도시·거점",
    "order": 1
  },
  {
    "id": "L048",
    "regionId": "R006",
    "regionKey": "senhalet",
    "regionName": "센할레트",
    "name": "센푸쿰",
    "aliases": [
      "센푸쿰"
    ],
    "kind": "도시·거점",
    "order": 2
  },
  {
    "id": "L049",
    "regionId": "R006",
    "regionKey": "senhalet",
    "regionName": "센할레트",
    "name": "센푸크가",
    "aliases": [
      "센푸크가"
    ],
    "kind": "마을",
    "order": 3
  },
  {
    "id": "L050",
    "regionId": "R006",
    "regionKey": "senhalet",
    "regionName": "센할레트",
    "name": "벨바르",
    "aliases": [
      "벨바르"
    ],
    "kind": "도시·거점",
    "order": 4
  },
  {
    "id": "L051",
    "regionId": "R006",
    "regionKey": "senhalet",
    "regionName": "센할레트",
    "name": "벨테크가",
    "aliases": [
      "벨테크가"
    ],
    "kind": "작업촌",
    "order": 5
  },
  {
    "id": "L052",
    "regionId": "R006",
    "regionKey": "senhalet",
    "regionName": "센할레트",
    "name": "벱렌할",
    "aliases": [
      "벱렌할"
    ],
    "kind": "도시·거점",
    "order": 6
  },
  {
    "id": "L053",
    "regionId": "R006",
    "regionKey": "senhalet",
    "regionName": "센할레트",
    "name": "벨나브가",
    "aliases": [
      "벨나브가"
    ],
    "kind": "나루촌",
    "order": 7
  },
  {
    "id": "L054",
    "regionId": "R006",
    "regionKey": "senhalet",
    "regionName": "센할레트",
    "name": "가르센에트",
    "aliases": [
      "가르센에트"
    ],
    "kind": "도시·거점",
    "order": 8
  },
  {
    "id": "L055",
    "regionId": "R006",
    "regionKey": "senhalet",
    "regionName": "센할레트",
    "name": "가르센가",
    "aliases": [
      "가르센가"
    ],
    "kind": "마을",
    "order": 9
  },
  {
    "id": "L056",
    "regionId": "R007",
    "regionKey": "hesferet",
    "regionName": "헤스페레트",
    "name": "헤스켈카르",
    "aliases": [
      "헤스켈카르"
    ],
    "kind": "도시·거점",
    "order": 1
  },
  {
    "id": "L057",
    "regionId": "R007",
    "regionKey": "hesferet",
    "regionName": "헤스페레트",
    "name": "헤스푸쿰",
    "aliases": [
      "헤스푸쿰"
    ],
    "kind": "도시·거점",
    "order": 2
  },
  {
    "id": "L058",
    "regionId": "R007",
    "regionKey": "hesferet",
    "regionName": "헤스페레트",
    "name": "켈헤스가",
    "aliases": [
      "켈헤스가"
    ],
    "kind": "숙소촌",
    "order": 3
  },
  {
    "id": "L059",
    "regionId": "R007",
    "regionKey": "hesferet",
    "regionName": "헤스페레트",
    "name": "헤스푸크가",
    "aliases": [
      "헤스푸크가"
    ],
    "kind": "마을",
    "order": 4
  },
  {
    "id": "L060",
    "regionId": "R007",
    "regionKey": "hesferet",
    "regionName": "헤스페레트",
    "name": "도르페르가",
    "aliases": [
      "도르페르가"
    ],
    "kind": "광산촌",
    "order": 5
  },
  {
    "id": "L061",
    "regionId": "R007",
    "regionKey": "hesferet",
    "regionName": "헤스페레트",
    "name": "페르바르",
    "aliases": [
      "페르바르"
    ],
    "kind": "도시·거점",
    "order": 6
  },
  {
    "id": "L062",
    "regionId": "R007",
    "regionKey": "hesferet",
    "regionName": "헤스페레트",
    "name": "람지르가",
    "aliases": [
      "람지르가"
    ],
    "kind": "숙소촌",
    "order": 7
  },
  {
    "id": "L063",
    "regionId": "R007",
    "regionKey": "hesferet",
    "regionName": "헤스페레트",
    "name": "람지르바르",
    "aliases": [
      "람지르바르"
    ],
    "kind": "도시·거점",
    "order": 8
  },
  {
    "id": "L064",
    "regionId": "R007",
    "regionKey": "hesferet",
    "regionName": "헤스페레트",
    "name": "메브켈에트",
    "aliases": [
      "메브켈에트"
    ],
    "kind": "도시·거점",
    "order": 9
  },
  {
    "id": "L065",
    "regionId": "R008",
    "regionKey": "kelnabet",
    "regionName": "켈나베트",
    "name": "워크바르",
    "aliases": [
      "워크바르"
    ],
    "kind": "도시·거점",
    "order": 1
  },
  {
    "id": "L066",
    "regionId": "R008",
    "regionKey": "kelnabet",
    "regionName": "켈나베트",
    "name": "마르켈미르",
    "aliases": [
      "마르켈미르"
    ],
    "kind": "도시·거점",
    "order": 2
  },
  {
    "id": "L067",
    "regionId": "R008",
    "regionKey": "kelnabet",
    "regionName": "켈나베트",
    "name": "마르푸크섬",
    "aliases": [
      "마르푸크섬"
    ],
    "kind": "선착장",
    "order": 3
  },
  {
    "id": "L068",
    "regionId": "R008",
    "regionKey": "kelnabet",
    "regionName": "켈나베트",
    "name": "나브렌가",
    "aliases": [
      "나브렌가"
    ],
    "kind": "기록촌",
    "order": 4
  },
  {
    "id": "L069",
    "regionId": "R008",
    "regionKey": "kelnabet",
    "regionName": "켈나베트",
    "name": "마르렌움",
    "aliases": [
      "마르렌움"
    ],
    "kind": "도시·거점",
    "order": 5
  },
  {
    "id": "L070",
    "regionId": "R008",
    "regionKey": "kelnabet",
    "regionName": "켈나베트",
    "name": "나브할",
    "aliases": [
      "나브할"
    ],
    "kind": "도시·거점",
    "order": 6
  },
  {
    "id": "L071",
    "regionId": "R008",
    "regionKey": "kelnabet",
    "regionName": "켈나베트",
    "name": "움마르켈",
    "aliases": [
      "움마르켈"
    ],
    "kind": "도시·거점",
    "order": 7
  },
  {
    "id": "L072",
    "regionId": "R008",
    "regionKey": "kelnabet",
    "regionName": "켈나베트",
    "name": "움나브가",
    "aliases": [
      "움나브가"
    ],
    "kind": "항구촌",
    "order": 8
  },
  {
    "id": "L073",
    "regionId": "R009",
    "regionKey": "hesbeket",
    "regionName": "헤스베케트",
    "name": "베크헤스푸쿰",
    "aliases": [
      "베크헤스푸쿰"
    ],
    "kind": "도시·거점",
    "order": 1
  },
  {
    "id": "L074",
    "regionId": "R009",
    "regionKey": "hesbeket",
    "regionName": "헤스베케트",
    "name": "푸크헤스가",
    "aliases": [
      "푸크헤스가"
    ],
    "kind": "작업촌",
    "order": 2
  },
  {
    "id": "L075",
    "regionId": "R009",
    "regionKey": "hesbeket",
    "regionName": "헤스베케트",
    "name": "나르할",
    "aliases": [
      "나르할"
    ],
    "kind": "도시·거점",
    "order": 3
  },
  {
    "id": "L076",
    "regionId": "R009",
    "regionKey": "hesbeket",
    "regionName": "헤스베케트",
    "name": "헤스나르가",
    "aliases": [
      "헤스나르가"
    ],
    "kind": "공동주거촌",
    "order": 4
  },
  {
    "id": "L077",
    "regionId": "R009",
    "regionKey": "hesbeket",
    "regionName": "헤스베케트",
    "name": "헤스워켈",
    "aliases": [
      "헤스워켈"
    ],
    "kind": "도시·거점",
    "order": 5
  },
  {
    "id": "L078",
    "regionId": "R009",
    "regionKey": "hesbeket",
    "regionName": "헤스베케트",
    "name": "메브헤스베크",
    "aliases": [
      "메브헤스베크"
    ],
    "kind": "도시·거점",
    "order": 6
  },
  {
    "id": "L079",
    "regionId": "R009",
    "regionKey": "hesbeket",
    "regionName": "헤스베케트",
    "name": "메브헤스가",
    "aliases": [
      "메브헤스가"
    ],
    "kind": "초소",
    "order": 7
  },
  {
    "id": "L080",
    "regionId": "R010",
    "regionKey": "yenmebet",
    "regionName": "옌메베트",
    "name": "옌베크할",
    "aliases": [
      "옌베크할"
    ],
    "kind": "도시·거점",
    "order": 1
  },
  {
    "id": "L081",
    "regionId": "R010",
    "regionKey": "yenmebet",
    "regionName": "옌메베트",
    "name": "옌워켈",
    "aliases": [
      "옌워켈"
    ],
    "kind": "도시·거점",
    "order": 2
  },
  {
    "id": "L082",
    "regionId": "R010",
    "regionKey": "yenmebet",
    "regionName": "옌메베트",
    "name": "옌테크가",
    "aliases": [
      "옌테크가"
    ],
    "kind": "작업촌",
    "order": 3
  },
  {
    "id": "L083",
    "regionId": "R010",
    "regionKey": "yenmebet",
    "regionName": "옌메베트",
    "name": "옌켈가",
    "aliases": [
      "옌켈가"
    ],
    "kind": "숙소촌",
    "order": 4
  },
  {
    "id": "L084",
    "regionId": "R010",
    "regionKey": "yenmebet",
    "regionName": "옌메베트",
    "name": "실베크에트",
    "aliases": [
      "실베크에트"
    ],
    "kind": "도시·거점",
    "order": 5
  },
  {
    "id": "L085",
    "regionId": "R010",
    "regionKey": "yenmebet",
    "regionName": "옌메베트",
    "name": "실람렌움",
    "aliases": [
      "실람렌움"
    ],
    "kind": "도시·거점",
    "order": 6
  },
  {
    "id": "L086",
    "regionId": "R010",
    "regionKey": "yenmebet",
    "regionName": "옌메베트",
    "name": "실람가",
    "aliases": [
      "실람가"
    ],
    "kind": "기록촌",
    "order": 7
  },
  {
    "id": "L087",
    "regionId": "R011",
    "regionKey": "nimnaret",
    "regionName": "님나레트",
    "name": "님나할",
    "aliases": [
      "님나할"
    ],
    "kind": "도시·거점",
    "order": 1
  },
  {
    "id": "L088",
    "regionId": "R011",
    "regionKey": "nimnaret",
    "regionName": "님나레트",
    "name": "얄베크움",
    "aliases": [
      "얄베크움"
    ],
    "kind": "도시·거점",
    "order": 2
  },
  {
    "id": "L089",
    "regionId": "R011",
    "regionKey": "nimnaret",
    "regionName": "님나레트",
    "name": "얄베크가",
    "aliases": [
      "얄베크가"
    ],
    "kind": "초소",
    "order": 3
  },
  {
    "id": "L090",
    "regionId": "R011",
    "regionKey": "nimnaret",
    "regionName": "님나레트",
    "name": "푸크베크움",
    "aliases": [
      "푸크베크움"
    ],
    "kind": "보관시설",
    "order": 4
  },
  {
    "id": "L091",
    "regionId": "R011",
    "regionKey": "nimnaret",
    "regionName": "님나레트",
    "name": "푸크나움",
    "aliases": [
      "푸크나움"
    ],
    "kind": "도시·거점",
    "order": 5
  },
  {
    "id": "L092",
    "regionId": "R011",
    "regionKey": "nimnaret",
    "regionName": "님나레트",
    "name": "엔켈할",
    "aliases": [
      "엔켈할"
    ],
    "kind": "도시·거점",
    "order": 6
  },
  {
    "id": "L093",
    "regionId": "R011",
    "regionKey": "nimnaret",
    "regionName": "님나레트",
    "name": "헤드렌움",
    "aliases": [
      "헤드렌움"
    ],
    "kind": "도시·거점",
    "order": 7
  },
  {
    "id": "L094",
    "regionId": "R011",
    "regionKey": "nimnaret",
    "regionName": "님나레트",
    "name": "헤드렌가",
    "aliases": [
      "헤드렌가"
    ],
    "kind": "대기촌",
    "order": 8
  },
  {
    "id": "L095",
    "regionId": "R012",
    "regionKey": "silnimet",
    "regionName": "실니메트",
    "name": "실소르가",
    "aliases": [
      "실소르가"
    ],
    "kind": "숲문 마을",
    "order": 1
  },
  {
    "id": "L096",
    "regionId": "R012",
    "regionKey": "silnimet",
    "regionName": "실니메트",
    "name": "실소르켈",
    "aliases": [
      "실소르켈"
    ],
    "kind": "도시·거점",
    "order": 2
  },
  {
    "id": "L097",
    "regionId": "R012",
    "regionKey": "silnimet",
    "regionName": "실니메트",
    "name": "도르소르산",
    "aliases": [
      "도르소르산"
    ],
    "kind": "도시·거점",
    "order": 3
  },
  {
    "id": "L098",
    "regionId": "R012",
    "regionKey": "silnimet",
    "regionName": "실니메트",
    "name": "실메르가",
    "aliases": [
      "실메르가"
    ],
    "kind": "채집촌",
    "order": 4
  },
  {
    "id": "L099",
    "regionId": "R012",
    "regionKey": "silnimet",
    "regionName": "실니메트",
    "name": "실메르미르",
    "aliases": [
      "실메르미르"
    ],
    "kind": "도시·거점",
    "order": 5
  },
  {
    "id": "L100",
    "regionId": "R012",
    "regionKey": "silnimet",
    "regionName": "실니메트",
    "name": "소르산가",
    "aliases": [
      "소르산가"
    ],
    "kind": "신전촌",
    "order": 6
  },
  {
    "id": "L101",
    "regionId": "R012",
    "regionKey": "silnimet",
    "regionName": "실니메트",
    "name": "메브메르켈",
    "aliases": [
      "메브메르켈"
    ],
    "kind": "도시·거점",
    "order": 7
  },
  {
    "id": "L102",
    "regionId": "R012",
    "regionKey": "silnimet",
    "regionName": "실니메트",
    "name": "메브메르가",
    "aliases": [
      "메브메르가"
    ],
    "kind": "야영지",
    "order": 8
  },
  {
    "id": "L103",
    "regionId": "R012",
    "regionKey": "silnimet",
    "regionName": "실니메트",
    "name": "벨마르미르",
    "aliases": [
      "벨마르미르"
    ],
    "kind": "도시·거점",
    "order": 9
  },
  {
    "id": "L104",
    "regionId": "R013",
    "regionKey": "ardolet",
    "regionName": "아르도레트",
    "name": "옌토르가",
    "aliases": [
      "옌토르가"
    ],
    "kind": "숙소촌",
    "order": 1
  },
  {
    "id": "L105",
    "regionId": "R013",
    "regionKey": "ardolet",
    "regionName": "아르도레트",
    "name": "옌이엘토르",
    "aliases": [
      "옌이엘토르"
    ],
    "kind": "도시·거점",
    "order": 2
  },
  {
    "id": "L106",
    "regionId": "R013",
    "regionKey": "ardolet",
    "regionName": "아르도레트",
    "name": "도르소르할",
    "aliases": [
      "도르소르할"
    ],
    "kind": "도시·거점",
    "order": 3
  },
  {
    "id": "L107",
    "regionId": "R013",
    "regionKey": "ardolet",
    "regionName": "아르도레트",
    "name": "아르소르산",
    "aliases": [
      "아르소르산"
    ],
    "kind": "도시·거점",
    "order": 4
  },
  {
    "id": "L108",
    "regionId": "R013",
    "regionKey": "ardolet",
    "regionName": "아르도레트",
    "name": "도르켈가",
    "aliases": [
      "도르켈가"
    ],
    "kind": "산길 마을",
    "order": 5
  },
  {
    "id": "L109",
    "regionId": "R013",
    "regionKey": "ardolet",
    "regionName": "아르도레트",
    "name": "도르켈바르",
    "aliases": [
      "도르켈바르"
    ],
    "kind": "도시·거점",
    "order": 6
  },
  {
    "id": "L110",
    "regionId": "R013",
    "regionKey": "ardolet",
    "regionName": "아르도레트",
    "name": "소르할",
    "aliases": [
      "소르할"
    ],
    "kind": "도시·거점",
    "order": 7
  },
  {
    "id": "L111",
    "regionId": "R013",
    "regionKey": "ardolet",
    "regionName": "아르도레트",
    "name": "소르할가",
    "aliases": [
      "소르할가"
    ],
    "kind": "숙소촌",
    "order": 8
  },
  {
    "id": "L112",
    "regionId": "R014",
    "regionKey": "garmebet",
    "regionName": "가르메베트",
    "name": "벨메브가",
    "aliases": [
      "벨메브가"
    ],
    "kind": "야영지",
    "order": 1
  },
  {
    "id": "L113",
    "regionId": "R014",
    "regionKey": "garmebet",
    "regionName": "가르메베트",
    "name": "벨람바르",
    "aliases": [
      "벨람바르"
    ],
    "kind": "도시·거점",
    "order": 2
  },
  {
    "id": "L114",
    "regionId": "R014",
    "regionKey": "garmebet",
    "regionName": "가르메베트",
    "name": "워크렌가",
    "aliases": [
      "워크렌가"
    ],
    "kind": "숙소촌",
    "order": 3
  },
  {
    "id": "L115",
    "regionId": "R014",
    "regionKey": "garmebet",
    "regionName": "가르메베트",
    "name": "워크렌움",
    "aliases": [
      "워크렌움"
    ],
    "kind": "도시·거점",
    "order": 4
  },
  {
    "id": "L116",
    "regionId": "R014",
    "regionKey": "garmebet",
    "regionName": "가르메베트",
    "name": "틱람가",
    "aliases": [
      "틱람가"
    ],
    "kind": "야영지",
    "order": 5
  },
  {
    "id": "L117",
    "regionId": "R014",
    "regionKey": "garmebet",
    "regionName": "가르메베트",
    "name": "틱메브할",
    "aliases": [
      "틱메브할"
    ],
    "kind": "도시·거점",
    "order": 6
  },
  {
    "id": "L118",
    "regionId": "R014",
    "regionKey": "garmebet",
    "regionName": "가르메베트",
    "name": "메브바르",
    "aliases": [
      "메브바르"
    ],
    "kind": "도시·거점",
    "order": 7
  },
  {
    "id": "L119",
    "regionId": "R014",
    "regionKey": "garmebet",
    "regionName": "가르메베트",
    "name": "메브테크가",
    "aliases": [
      "메브테크가"
    ],
    "kind": "작업촌",
    "order": 8
  },
  {
    "id": "L120",
    "regionId": "R014",
    "regionKey": "garmebet",
    "regionName": "가르메베트",
    "name": "벨베크엘",
    "aliases": [
      "벨베크엘"
    ],
    "kind": "도시·거점",
    "order": 9
  },
  {
    "id": "L121",
    "regionId": "R015",
    "regionKey": "silhalet",
    "regionName": "실할레트",
    "name": "라드실할",
    "aliases": [
      "라드실할"
    ],
    "kind": "도시·거점",
    "order": 1
  },
  {
    "id": "L122",
    "regionId": "R015",
    "regionKey": "silhalet",
    "regionName": "실할레트",
    "name": "실베크엘",
    "aliases": [
      "실베크엘"
    ],
    "kind": "도시·거점",
    "order": 2
  },
  {
    "id": "L123",
    "regionId": "R015",
    "regionKey": "silhalet",
    "regionName": "실할레트",
    "name": "라드실가",
    "aliases": [
      "라드실가"
    ],
    "kind": "작업촌",
    "order": 3
  },
  {
    "id": "L124",
    "regionId": "R015",
    "regionKey": "silhalet",
    "regionName": "실할레트",
    "name": "실소르산",
    "aliases": [
      "실소르산"
    ],
    "kind": "도시·거점",
    "order": 4
  },
  {
    "id": "L125",
    "regionId": "R015",
    "regionKey": "silhalet",
    "regionName": "실할레트",
    "name": "실문가",
    "aliases": [
      "실문가"
    ],
    "kind": "숲문 마을",
    "order": 5
  },
  {
    "id": "L126",
    "regionId": "R015",
    "regionKey": "silhalet",
    "regionName": "실할레트",
    "name": "실다트바르",
    "aliases": [
      "실다트바르"
    ],
    "kind": "도시·거점",
    "order": 6
  },
  {
    "id": "L127",
    "regionId": "R015",
    "regionKey": "silhalet",
    "regionName": "실할레트",
    "name": "실다트가",
    "aliases": [
      "실다트가"
    ],
    "kind": "채집촌",
    "order": 7
  },
  {
    "id": "L128",
    "regionId": "R015",
    "regionKey": "silhalet",
    "regionName": "실할레트",
    "name": "실테크엘",
    "aliases": [
      "실테크엘"
    ],
    "kind": "도시·거점",
    "order": 8
  },
  {
    "id": "L129",
    "regionId": "R015",
    "regionKey": "silhalet",
    "regionName": "실할레트",
    "name": "실테크가",
    "aliases": [
      "실테크가"
    ],
    "kind": "숙소촌",
    "order": 9
  },
  {
    "id": "L130",
    "regionId": "R016",
    "regionKey": "merhalet",
    "regionName": "메르할레트",
    "name": "헤드메르가",
    "aliases": [
      "헤드메르가"
    ],
    "kind": "대기촌",
    "order": 1
  },
  {
    "id": "L131",
    "regionId": "R016",
    "regionKey": "merhalet",
    "regionName": "메르할레트",
    "name": "헤드켈바르",
    "aliases": [
      "헤드켈바르"
    ],
    "kind": "도시·거점",
    "order": 2
  },
  {
    "id": "L132",
    "regionId": "R016",
    "regionKey": "merhalet",
    "regionName": "메르할레트",
    "name": "메르바르",
    "aliases": [
      "메르바르"
    ],
    "kind": "도시·거점",
    "order": 3
  },
  {
    "id": "L133",
    "regionId": "R016",
    "regionKey": "merhalet",
    "regionName": "메르할레트",
    "name": "메르벨마르",
    "aliases": [
      "메르벨마르"
    ],
    "kind": "도시·거점",
    "order": 4
  },
  {
    "id": "L134",
    "regionId": "R016",
    "regionKey": "merhalet",
    "regionName": "메르할레트",
    "name": "푸크메르가",
    "aliases": [
      "푸크메르가"
    ],
    "kind": "창고촌",
    "order": 5
  },
  {
    "id": "L135",
    "regionId": "R016",
    "regionKey": "merhalet",
    "regionName": "메르할레트",
    "name": "푸크테쿰",
    "aliases": [
      "푸크테쿰"
    ],
    "kind": "도시·거점",
    "order": 6
  },
  {
    "id": "L136",
    "regionId": "R016",
    "regionKey": "merhalet",
    "regionName": "메르할레트",
    "name": "메르나브가",
    "aliases": [
      "메르나브가"
    ],
    "kind": "항구가",
    "order": 7
  },
  {
    "id": "L137",
    "regionId": "R016",
    "regionKey": "merhalet",
    "regionName": "메르할레트",
    "name": "메르님바르",
    "aliases": [
      "메르님바르"
    ],
    "kind": "도시·거점",
    "order": 8
  },
  {
    "id": "L138",
    "regionId": "R017",
    "regionKey": "nimsolet",
    "regionName": "님소레트",
    "name": "님렘할",
    "aliases": [
      "님렘할"
    ],
    "kind": "도시·거점",
    "order": 1
  },
  {
    "id": "L139",
    "regionId": "R017",
    "regionKey": "nimsolet",
    "regionName": "님소레트",
    "name": "렌메르미르",
    "aliases": [
      "렌메르미르"
    ],
    "kind": "도시·거점",
    "order": 2
  },
  {
    "id": "L140",
    "regionId": "R017",
    "regionKey": "nimsolet",
    "regionName": "님소레트",
    "name": "님렌가",
    "aliases": [
      "님렌가"
    ],
    "kind": "숙소가",
    "order": 3
  },
  {
    "id": "L141",
    "regionId": "R017",
    "regionKey": "nimsolet",
    "regionName": "님소레트",
    "name": "님할",
    "aliases": [
      "님할"
    ],
    "kind": "도시·거점",
    "order": 4
  },
  {
    "id": "L142",
    "regionId": "R017",
    "regionKey": "nimsolet",
    "regionName": "님소레트",
    "name": "소르다트가",
    "aliases": [
      "소르다트가"
    ],
    "kind": "신전촌",
    "order": 5
  },
  {
    "id": "L143",
    "regionId": "R017",
    "regionKey": "nimsolet",
    "regionName": "님소레트",
    "name": "소르다트움",
    "aliases": [
      "소르다트움"
    ],
    "kind": "도시·거점",
    "order": 6
  },
  {
    "id": "L144",
    "regionId": "R017",
    "regionKey": "nimsolet",
    "regionName": "님소레트",
    "name": "렌테쿰",
    "aliases": [
      "렌테쿰"
    ],
    "kind": "도시·거점",
    "order": 7
  },
  {
    "id": "L145",
    "regionId": "R017",
    "regionKey": "nimsolet",
    "regionName": "님소레트",
    "name": "렌테크가",
    "aliases": [
      "렌테크가"
    ],
    "kind": "작업가",
    "order": 8
  },
  {
    "id": "L146",
    "regionId": "R018",
    "regionKey": "sylvania",
    "regionName": "실바니아",
    "name": "워크실가",
    "aliases": [
      "워크실가"
    ],
    "kind": "마을",
    "order": 1
  },
  {
    "id": "L147",
    "regionId": "R018",
    "regionKey": "sylvania",
    "regionName": "실바니아",
    "name": "워크켈할",
    "aliases": [
      "워크켈할"
    ],
    "kind": "도시·거점",
    "order": 2
  },
  {
    "id": "L148",
    "regionId": "R018",
    "regionKey": "sylvania",
    "regionName": "실바니아",
    "name": "실렌산",
    "aliases": [
      "실렌산"
    ],
    "kind": "도시·거점",
    "order": 3
  },
  {
    "id": "L149",
    "regionId": "R018",
    "regionKey": "sylvania",
    "regionName": "실바니아",
    "name": "실킨가",
    "aliases": [
      "실킨가"
    ],
    "kind": "마을",
    "order": 4
  },
  {
    "id": "L150",
    "regionId": "R018",
    "regionKey": "sylvania",
    "regionName": "실바니아",
    "name": "렌얄움",
    "aliases": [
      "렌얄움"
    ],
    "kind": "도시·거점",
    "order": 5
  },
  {
    "id": "L151",
    "regionId": "R018",
    "regionKey": "sylvania",
    "regionName": "실바니아",
    "name": "움켈산",
    "aliases": [
      "움켈산"
    ],
    "kind": "도시·거점",
    "order": 6
  },
  {
    "id": "L152",
    "regionId": "R018",
    "regionKey": "sylvania",
    "regionName": "실바니아",
    "name": "움켈가",
    "aliases": [
      "움켈가"
    ],
    "kind": "숙소촌",
    "order": 7
  },
  {
    "id": "L153",
    "regionId": "R019",
    "regionKey": "dragonspire",
    "regionName": "드래곤스파이어",
    "name": "나르베크토르",
    "aliases": [
      "나르베크토르"
    ],
    "kind": "도시·거점",
    "order": 1
  },
  {
    "id": "L154",
    "regionId": "R019",
    "regionKey": "dragonspire",
    "regionName": "드래곤스파이어",
    "name": "나르페르가",
    "aliases": [
      "나르페르가"
    ],
    "kind": "작업촌",
    "order": 2
  },
  {
    "id": "L155",
    "regionId": "R019",
    "regionKey": "dragonspire",
    "regionName": "드래곤스파이어",
    "name": "나르마르켈",
    "aliases": [
      "나르마르켈"
    ],
    "kind": "도시·거점",
    "order": 3
  },
  {
    "id": "L156",
    "regionId": "R019",
    "regionKey": "dragonspire",
    "regionName": "드래곤스파이어",
    "name": "나르마르렌움",
    "aliases": [
      "나르마르렌움"
    ],
    "kind": "도시·거점",
    "order": 4
  },
  {
    "id": "L157",
    "regionId": "R019",
    "regionKey": "dragonspire",
    "regionName": "드래곤스파이어",
    "name": "나르모스가",
    "aliases": [
      "나르모스가"
    ],
    "kind": "피난촌",
    "order": 5
  },
  {
    "id": "L158",
    "regionId": "R019",
    "regionKey": "dragonspire",
    "regionName": "드래곤스파이어",
    "name": "마르모스할",
    "aliases": [
      "마르모스할"
    ],
    "kind": "도시·거점",
    "order": 6
  },
  {
    "id": "L159",
    "regionId": "R019",
    "regionKey": "dragonspire",
    "regionName": "드래곤스파이어",
    "name": "마르나르가",
    "aliases": [
      "마르나르가"
    ],
    "kind": "선착장",
    "order": 7
  },
  {
    "id": "L160",
    "regionId": "R020",
    "regionKey": "fenrir-s-eye",
    "regionName": "펜리르의 눈",
    "name": "둔토르가",
    "aliases": [
      "둔토르가"
    ],
    "kind": "등대촌",
    "order": 1
  },
  {
    "id": "L161",
    "regionId": "R020",
    "regionKey": "fenrir-s-eye",
    "regionName": "펜리르의 눈",
    "name": "둔아르토르",
    "aliases": [
      "둔아르토르"
    ],
    "kind": "도시·거점",
    "order": 2
  },
  {
    "id": "L162",
    "regionId": "R020",
    "regionKey": "fenrir-s-eye",
    "regionName": "펜리르의 눈",
    "name": "둔나브렌움",
    "aliases": [
      "둔나브렌움"
    ],
    "kind": "도시·거점",
    "order": 3
  },
  {
    "id": "L163",
    "regionId": "R020",
    "regionKey": "fenrir-s-eye",
    "regionName": "펜리르의 눈",
    "name": "둔푸크가",
    "aliases": [
      "둔푸크가"
    ],
    "kind": "보관시설",
    "order": 4
  },
  {
    "id": "L164",
    "regionId": "R020",
    "regionKey": "fenrir-s-eye",
    "regionName": "펜리르의 눈",
    "name": "움마르소르",
    "aliases": [
      "움마르소르"
    ],
    "kind": "도시·거점",
    "order": 5
  },
  {
    "id": "L165",
    "regionId": "R020",
    "regionKey": "fenrir-s-eye",
    "regionName": "펜리르의 눈",
    "name": "벱나브할",
    "aliases": [
      "벱나브할"
    ],
    "kind": "도시·거점",
    "order": 6
  },
  {
    "id": "L166",
    "regionId": "R020",
    "regionKey": "fenrir-s-eye",
    "regionName": "펜리르의 눈",
    "name": "벱나브가",
    "aliases": [
      "벱나브가"
    ],
    "kind": "구조 거점",
    "order": 7
  }
] as const;
