// Generated from curated LunaTalk unused NPC pool. Do not edit by hand.
export const GENERATED_RANDOM_NPC_ASSETS = [
    {
        "assetId":  "rnpc-f-human-0001",
        "imagePath":  "/npc-assets/rnpc-f-human-0001.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C003",
        "sourceRoleHint":  "궁정 납품 해설자",
        "sourceCultureHint":  "인간계·레오니아 궁정권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  71044
    },
    {
        "assetId":  "rnpc-f-human-0002",
        "imagePath":  "/npc-assets/rnpc-f-human-0002.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C003",
        "sourceRoleHint":  "궁정 납품 해설자",
        "sourceCultureHint":  "인간계·레오니아 궁정권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  55004
    },
    {
        "assetId":  "rnpc-f-human-0003",
        "imagePath":  "/npc-assets/rnpc-f-human-0003.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C003",
        "sourceRoleHint":  "궁정 납품 해설자",
        "sourceCultureHint":  "인간계·레오니아 궁정권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  47070
    },
    {
        "assetId":  "rnpc-f-human-0004",
        "imagePath":  "/npc-assets/rnpc-f-human-0004.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C005",
        "sourceRoleHint":  "전마·수행 좌표",
        "sourceCultureHint":  "인간계·레오니아 궁정권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  33638
    },
    {
        "assetId":  "rnpc-f-human-0005",
        "imagePath":  "/npc-assets/rnpc-f-human-0005.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C005",
        "sourceRoleHint":  "전마·수행 좌표",
        "sourceCultureHint":  "인간계·레오니아 궁정권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  30780
    },
    {
        "assetId":  "rnpc-f-human-0006",
        "imagePath":  "/npc-assets/rnpc-f-human-0006.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C005",
        "sourceRoleHint":  "전마·수행 좌표",
        "sourceCultureHint":  "인간계·레오니아 궁정권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  25412
    },
    {
        "assetId":  "rnpc-f-human-0007",
        "imagePath":  "/npc-assets/rnpc-f-human-0007.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C006",
        "sourceRoleHint":  "항만 권위대표",
        "sourceCultureHint":  "인간계·노르가르드 항만권",
        "sourceAgeHint":  "중년",
        "bytes":  30762
    },
    {
        "assetId":  "rnpc-f-human-0008",
        "imagePath":  "/npc-assets/rnpc-f-human-0008.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C006",
        "sourceRoleHint":  "항만 권위대표",
        "sourceCultureHint":  "인간계·노르가르드 항만권",
        "sourceAgeHint":  "중년",
        "bytes":  30600
    },
    {
        "assetId":  "rnpc-f-human-0009",
        "imagePath":  "/npc-assets/rnpc-f-human-0009.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C006",
        "sourceRoleHint":  "항만 권위대표",
        "sourceCultureHint":  "인간계·노르가르드 항만권",
        "sourceAgeHint":  "중년",
        "bytes":  37544
    },
    {
        "assetId":  "rnpc-f-human-0010",
        "imagePath":  "/npc-assets/rnpc-f-human-0010.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C007",
        "sourceRoleHint":  "철강 부두 집행자",
        "sourceCultureHint":  "인간계·노르가르드 항만권",
        "sourceAgeHint":  "중년",
        "bytes":  40466
    },
    {
        "assetId":  "rnpc-f-human-0011",
        "imagePath":  "/npc-assets/rnpc-f-human-0011.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C009",
        "sourceRoleHint":  "군항 좌표",
        "sourceCultureHint":  "인간계·노르가르드 항만권",
        "sourceAgeHint":  "중년",
        "bytes":  82512
    },
    {
        "assetId":  "rnpc-f-human-0012",
        "imagePath":  "/npc-assets/rnpc-f-human-0012.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C009",
        "sourceRoleHint":  "군항 좌표",
        "sourceCultureHint":  "인간계·노르가르드 항만권",
        "sourceAgeHint":  "중년",
        "bytes":  85354
    },
    {
        "assetId":  "rnpc-f-human-0013",
        "imagePath":  "/npc-assets/rnpc-f-human-0013.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C009",
        "sourceRoleHint":  "군항 좌표",
        "sourceCultureHint":  "인간계·노르가르드 항만권",
        "sourceAgeHint":  "중년",
        "bytes":  63846
    },
    {
        "assetId":  "rnpc-f-human-0014",
        "imagePath":  "/npc-assets/rnpc-f-human-0014.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C013",
        "sourceRoleHint":  "신전·관측 해설자",
        "sourceCultureHint":  "인간계·티리스 서부 접경권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  43636
    },
    {
        "assetId":  "rnpc-f-human-0015",
        "imagePath":  "/npc-assets/rnpc-f-human-0015.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C015",
        "sourceRoleHint":  "성문 좌표",
        "sourceCultureHint":  "인간계·티리스 서부 접경권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  50040
    },
    {
        "assetId":  "rnpc-f-human-0016",
        "imagePath":  "/npc-assets/rnpc-f-human-0016.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C015",
        "sourceRoleHint":  "성문 좌표",
        "sourceCultureHint":  "인간계·티리스 서부 접경권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  52662
    },
    {
        "assetId":  "rnpc-f-human-0017",
        "imagePath":  "/npc-assets/rnpc-f-human-0017.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C015",
        "sourceRoleHint":  "성문 좌표",
        "sourceCultureHint":  "인간계·티리스 서부 접경권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  64914
    },
    {
        "assetId":  "rnpc-f-human-0018",
        "imagePath":  "/npc-assets/rnpc-f-human-0018.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C016",
        "sourceRoleHint":  "기록원 권위대표",
        "sourceCultureHint":  "인간계·린레네트 학예권",
        "sourceAgeHint":  "중년",
        "bytes":  57998
    },
    {
        "assetId":  "rnpc-f-human-0019",
        "imagePath":  "/npc-assets/rnpc-f-human-0019.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C016",
        "sourceRoleHint":  "기록원 권위대표",
        "sourceCultureHint":  "인간계·린레네트 학예권",
        "sourceAgeHint":  "중년",
        "bytes":  48210
    },
    {
        "assetId":  "rnpc-f-human-0020",
        "imagePath":  "/npc-assets/rnpc-f-human-0020.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C017",
        "sourceRoleHint":  "극장 질서 집행자",
        "sourceCultureHint":  "인간계·린레네트 학예권",
        "sourceAgeHint":  "중년",
        "bytes":  58790
    },
    {
        "assetId":  "rnpc-f-human-0021",
        "imagePath":  "/npc-assets/rnpc-f-human-0021.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C017",
        "sourceRoleHint":  "극장 질서 집행자",
        "sourceCultureHint":  "인간계·린레네트 학예권",
        "sourceAgeHint":  "중년",
        "bytes":  65670
    },
    {
        "assetId":  "rnpc-f-human-0022",
        "imagePath":  "/npc-assets/rnpc-f-human-0022.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C019",
        "sourceRoleHint":  "기록원 좌표",
        "sourceCultureHint":  "인간계·린레네트 학예권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  50920
    },
    {
        "assetId":  "rnpc-f-human-0023",
        "imagePath":  "/npc-assets/rnpc-f-human-0023.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C023",
        "sourceRoleHint":  "성벽 공사 해설자",
        "sourceCultureHint":  "인간계·벡도레트 성채권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  30980
    },
    {
        "assetId":  "rnpc-f-human-0024",
        "imagePath":  "/npc-assets/rnpc-f-human-0024.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C023",
        "sourceRoleHint":  "성벽 공사 해설자",
        "sourceCultureHint":  "인간계·벡도레트 성채권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  53596
    },
    {
        "assetId":  "rnpc-f-human-0025",
        "imagePath":  "/npc-assets/rnpc-f-human-0025.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C023",
        "sourceRoleHint":  "성벽 공사 해설자",
        "sourceCultureHint":  "인간계·벡도레트 성채권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  33360
    },
    {
        "assetId":  "rnpc-f-human-0026",
        "imagePath":  "/npc-assets/rnpc-f-human-0026.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C025",
        "sourceRoleHint":  "외성문 좌표",
        "sourceCultureHint":  "인간계·벡도레트 성채권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  52142
    },
    {
        "assetId":  "rnpc-f-human-0027",
        "imagePath":  "/npc-assets/rnpc-f-human-0027.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C025",
        "sourceRoleHint":  "외성문 좌표",
        "sourceCultureHint":  "인간계·벡도레트 성채권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  32458
    },
    {
        "assetId":  "rnpc-f-human-0028",
        "imagePath":  "/npc-assets/rnpc-f-human-0028.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C026",
        "sourceRoleHint":  "공동 창고 대표",
        "sourceCultureHint":  "인간계·센할레트 공동창고권",
        "sourceAgeHint":  "중년",
        "bytes":  80382
    },
    {
        "assetId":  "rnpc-f-human-0029",
        "imagePath":  "/npc-assets/rnpc-f-human-0029.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C026",
        "sourceRoleHint":  "공동 창고 대표",
        "sourceCultureHint":  "인간계·센할레트 공동창고권",
        "sourceAgeHint":  "중년",
        "bytes":  67446
    },
    {
        "assetId":  "rnpc-f-human-0030",
        "imagePath":  "/npc-assets/rnpc-f-human-0030.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C026",
        "sourceRoleHint":  "공동 창고 대표",
        "sourceCultureHint":  "인간계·센할레트 공동창고권",
        "sourceAgeHint":  "중년",
        "bytes":  26750
    },
    {
        "assetId":  "rnpc-f-human-0031",
        "imagePath":  "/npc-assets/rnpc-f-human-0031.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C027",
        "sourceRoleHint":  "수로 회의 집행자",
        "sourceCultureHint":  "인간계·센할레트 공동창고권",
        "sourceAgeHint":  "중년",
        "bytes":  30892
    },
    {
        "assetId":  "rnpc-f-human-0032",
        "imagePath":  "/npc-assets/rnpc-f-human-0032.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C029",
        "sourceRoleHint":  "공동 창고 좌표",
        "sourceCultureHint":  "인간계·센할레트 공동창고권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  34474
    },
    {
        "assetId":  "rnpc-f-human-0033",
        "imagePath":  "/npc-assets/rnpc-f-human-0033.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C029",
        "sourceRoleHint":  "공동 창고 좌표",
        "sourceCultureHint":  "인간계·센할레트 공동창고권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  70872
    },
    {
        "assetId":  "rnpc-f-human-0034",
        "imagePath":  "/npc-assets/rnpc-f-human-0034.webp",
        "gender":  "female",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C029",
        "sourceRoleHint":  "공동 창고 좌표",
        "sourceCultureHint":  "인간계·센할레트 공동창고권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  58866
    },
    {
        "assetId":  "rnpc-f-mixed-0001",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0001.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C033",
        "sourceRoleHint":  "무기 중개 해설자",
        "sourceCultureHint":  "북방 혼거권·헤스페레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  52666
    },
    {
        "assetId":  "rnpc-f-mixed-0002",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0002.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C033",
        "sourceRoleHint":  "무기 중개 해설자",
        "sourceCultureHint":  "북방 혼거권·헤스페레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  47498
    },
    {
        "assetId":  "rnpc-f-mixed-0003",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0003.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C033",
        "sourceRoleHint":  "무기 중개 해설자",
        "sourceCultureHint":  "북방 혼거권·헤스페레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  76668
    },
    {
        "assetId":  "rnpc-f-mixed-0004",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0004.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C035",
        "sourceRoleHint":  "고개 좌표",
        "sourceCultureHint":  "북방 혼거권·헤스페레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  24598
    },
    {
        "assetId":  "rnpc-f-mixed-0005",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0005.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C035",
        "sourceRoleHint":  "고개 좌표",
        "sourceCultureHint":  "북방 혼거권·헤스페레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  32454
    },
    {
        "assetId":  "rnpc-f-mixed-0006",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0006.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C035",
        "sourceRoleHint":  "고개 좌표",
        "sourceCultureHint":  "북방 혼거권·헤스페레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  55338
    },
    {
        "assetId":  "rnpc-f-mixed-0007",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0007.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C036",
        "sourceRoleHint":  "자유항 의회 대표",
        "sourceCultureHint":  "북방 혼거권·켈나베트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  36184
    },
    {
        "assetId":  "rnpc-f-mixed-0008",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0008.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C036",
        "sourceRoleHint":  "자유항 의회 대표",
        "sourceCultureHint":  "북방 혼거권·켈나베트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  23908
    },
    {
        "assetId":  "rnpc-f-mixed-0009",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0009.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C036",
        "sourceRoleHint":  "자유항 의회 대표",
        "sourceCultureHint":  "북방 혼거권·켈나베트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  77086
    },
    {
        "assetId":  "rnpc-f-mixed-0010",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0010.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C037",
        "sourceRoleHint":  "원정 허가 집행자",
        "sourceCultureHint":  "북방 혼거권·켈나베트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  30638
    },
    {
        "assetId":  "rnpc-f-mixed-0011",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0011.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C039",
        "sourceRoleHint":  "자유항 좌표",
        "sourceCultureHint":  "북방 혼거권·켈나베트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  30984
    },
    {
        "assetId":  "rnpc-f-mixed-0012",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0012.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C039",
        "sourceRoleHint":  "자유항 좌표",
        "sourceCultureHint":  "북방 혼거권·켈나베트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  75950
    },
    {
        "assetId":  "rnpc-f-mixed-0013",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0013.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C039",
        "sourceRoleHint":  "자유항 좌표",
        "sourceCultureHint":  "북방 혼거권·켈나베트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  70446
    },
    {
        "assetId":  "rnpc-f-mixed-0014",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0014.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C043",
        "sourceRoleHint":  "불씨 공동주거 해설자",
        "sourceCultureHint":  "북방 혼거권·헤스베케트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  68868
    },
    {
        "assetId":  "rnpc-f-mixed-0015",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0015.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C045",
        "sourceRoleHint":  "겨울 통행 좌표",
        "sourceCultureHint":  "북방 혼거권·헤스베케트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  84000
    },
    {
        "assetId":  "rnpc-f-mixed-0016",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0016.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C045",
        "sourceRoleHint":  "겨울 통행 좌표",
        "sourceCultureHint":  "북방 혼거권·헤스베케트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  30356
    },
    {
        "assetId":  "rnpc-f-mixed-0017",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0017.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C046",
        "sourceRoleHint":  "고공 통행 대표",
        "sourceCultureHint":  "산악·학술 혼거권·옌메베트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  48752
    },
    {
        "assetId":  "rnpc-f-mixed-0018",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0018.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C046",
        "sourceRoleHint":  "고공 통행 대표",
        "sourceCultureHint":  "산악·학술 혼거권·옌메베트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  58640
    },
    {
        "assetId":  "rnpc-f-mixed-0019",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0019.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C046",
        "sourceRoleHint":  "고공 통행 대표",
        "sourceCultureHint":  "산악·학술 혼거권·옌메베트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  62684
    },
    {
        "assetId":  "rnpc-f-mixed-0020",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0020.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C047",
        "sourceRoleHint":  "기수단 집행자",
        "sourceCultureHint":  "산악·학술 혼거권·옌메베트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  74348
    },
    {
        "assetId":  "rnpc-f-mixed-0021",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0021.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C047",
        "sourceRoleHint":  "기수단 집행자",
        "sourceCultureHint":  "산악·학술 혼거권·옌메베트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  32326
    },
    {
        "assetId":  "rnpc-f-mixed-0022",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0022.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C047",
        "sourceRoleHint":  "기수단 집행자",
        "sourceCultureHint":  "산악·학술 혼거권·옌메베트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  35826
    },
    {
        "assetId":  "rnpc-f-mixed-0023",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0023.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C049",
        "sourceRoleHint":  "고공 통행 좌표",
        "sourceCultureHint":  "산악·학술 혼거권·옌메베트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  35310
    },
    {
        "assetId":  "rnpc-f-mixed-0024",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0024.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C049",
        "sourceRoleHint":  "고공 통행 좌표",
        "sourceCultureHint":  "산악·학술 혼거권·옌메베트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  32398
    },
    {
        "assetId":  "rnpc-f-mixed-0025",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0025.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C053",
        "sourceRoleHint":  "제한 학당 해설자",
        "sourceCultureHint":  "산악·학술 혼거권·님나레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  37316
    },
    {
        "assetId":  "rnpc-f-mixed-0026",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0026.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C055",
        "sourceRoleHint":  "제한 학당 좌표",
        "sourceCultureHint":  "산악·학술 혼거권·님나레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  36210
    },
    {
        "assetId":  "rnpc-f-mixed-0027",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0027.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C055",
        "sourceRoleHint":  "제한 학당 좌표",
        "sourceCultureHint":  "산악·학술 혼거권·님나레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  31950
    },
    {
        "assetId":  "rnpc-f-mixed-0028",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0028.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C055",
        "sourceRoleHint":  "제한 학당 좌표",
        "sourceCultureHint":  "산악·학술 혼거권·님나레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  35420
    },
    {
        "assetId":  "rnpc-f-mixed-0029",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0029.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C056",
        "sourceRoleHint":  "산악 사원 대표",
        "sourceCultureHint":  "산악·학술 혼거권·실니메트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  40162
    },
    {
        "assetId":  "rnpc-f-mixed-0030",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0030.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C056",
        "sourceRoleHint":  "산악 사원 대표",
        "sourceCultureHint":  "산악·학술 혼거권·실니메트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  21236
    },
    {
        "assetId":  "rnpc-f-mixed-0031",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0031.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C056",
        "sourceRoleHint":  "산악 사원 대표",
        "sourceCultureHint":  "산악·학술 혼거권·실니메트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  40098
    },
    {
        "assetId":  "rnpc-f-mixed-0032",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0032.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C057",
        "sourceRoleHint":  "약초 장터 집행자",
        "sourceCultureHint":  "산악·학술 혼거권·실니메트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  25712
    },
    {
        "assetId":  "rnpc-f-mixed-0033",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0033.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C059",
        "sourceRoleHint":  "산악 사원 좌표",
        "sourceCultureHint":  "산악·학술 혼거권·실니메트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  81704
    },
    {
        "assetId":  "rnpc-f-mixed-0034",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0034.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C063",
        "sourceRoleHint":  "등정 해설자",
        "sourceCultureHint":  "산악·학술 혼거권·아르도레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  35066
    },
    {
        "assetId":  "rnpc-f-mixed-0035",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0035.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C063",
        "sourceRoleHint":  "등정 해설자",
        "sourceCultureHint":  "산악·학술 혼거권·아르도레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  33454
    },
    {
        "assetId":  "rnpc-f-mixed-0036",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0036.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C063",
        "sourceRoleHint":  "등정 해설자",
        "sourceCultureHint":  "산악·학술 혼거권·아르도레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  50400
    },
    {
        "assetId":  "rnpc-f-mixed-0037",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0037.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C065",
        "sourceRoleHint":  "관측대 좌표",
        "sourceCultureHint":  "산악·학술 혼거권·아르도레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  29846
    },
    {
        "assetId":  "rnpc-f-mixed-0038",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0038.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C065",
        "sourceRoleHint":  "관측대 좌표",
        "sourceCultureHint":  "산악·학술 혼거권·아르도레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  33762
    },
    {
        "assetId":  "rnpc-f-mixed-0039",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0039.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C065",
        "sourceRoleHint":  "관측대 좌표",
        "sourceCultureHint":  "산악·학술 혼거권·아르도레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  37296
    },
    {
        "assetId":  "rnpc-f-mixed-0040",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0040.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C066",
        "sourceRoleHint":  "계절 야영 대표",
        "sourceCultureHint":  "초지 유목 혼거권·가르메베트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  35346
    },
    {
        "assetId":  "rnpc-f-mixed-0041",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0041.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C067",
        "sourceRoleHint":  "물가 약속 집행자",
        "sourceCultureHint":  "초지 유목 혼거권·가르메베트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  42108
    },
    {
        "assetId":  "rnpc-f-mixed-0042",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0042.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C069",
        "sourceRoleHint":  "계절 야영 좌표",
        "sourceCultureHint":  "초지 유목 혼거권·가르메베트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  31938
    },
    {
        "assetId":  "rnpc-f-mixed-0043",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0043.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C069",
        "sourceRoleHint":  "계절 야영 좌표",
        "sourceCultureHint":  "초지 유목 혼거권·가르메베트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  29932
    },
    {
        "assetId":  "rnpc-f-mixed-0044",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0044.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C073",
        "sourceRoleHint":  "왕실 정원 해설자",
        "sourceCultureHint":  "성림 혼거권·실할레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  36110
    },
    {
        "assetId":  "rnpc-f-mixed-0045",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0045.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C073",
        "sourceRoleHint":  "왕실 정원 해설자",
        "sourceCultureHint":  "성림 혼거권·실할레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  62462
    },
    {
        "assetId":  "rnpc-f-mixed-0046",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0046.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C073",
        "sourceRoleHint":  "왕실 정원 해설자",
        "sourceCultureHint":  "성림 혼거권·실할레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  38712
    },
    {
        "assetId":  "rnpc-f-mixed-0047",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0047.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C075",
        "sourceRoleHint":  "왕실 정원 좌표",
        "sourceCultureHint":  "성림 혼거권·실할레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  33854
    },
    {
        "assetId":  "rnpc-f-mixed-0048",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0048.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C076",
        "sourceRoleHint":  "강하 항구 대표",
        "sourceCultureHint":  "강하 교역 혼거권·메르할레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  34332
    },
    {
        "assetId":  "rnpc-f-mixed-0049",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0049.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C076",
        "sourceRoleHint":  "강하 항구 대표",
        "sourceCultureHint":  "강하 교역 혼거권·메르할레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  27540
    },
    {
        "assetId":  "rnpc-f-mixed-0050",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0050.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C076",
        "sourceRoleHint":  "강하 항구 대표",
        "sourceCultureHint":  "강하 교역 혼거권·메르할레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  30924
    },
    {
        "assetId":  "rnpc-f-mixed-0051",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0051.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C077",
        "sourceRoleHint":  "세금 관문 집행자",
        "sourceCultureHint":  "강하 교역 혼거권·메르할레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  36640
    },
    {
        "assetId":  "rnpc-f-mixed-0052",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0052.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C077",
        "sourceRoleHint":  "세금 관문 집행자",
        "sourceCultureHint":  "강하 교역 혼거권·메르할레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  25272
    },
    {
        "assetId":  "rnpc-f-mixed-0053",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0053.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C077",
        "sourceRoleHint":  "세금 관문 집행자",
        "sourceCultureHint":  "강하 교역 혼거권·메르할레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  36024
    },
    {
        "assetId":  "rnpc-f-mixed-0054",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0054.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C079",
        "sourceRoleHint":  "강하 항구 좌표",
        "sourceCultureHint":  "강하 교역 혼거권·메르할레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  43684
    },
    {
        "assetId":  "rnpc-f-mixed-0055",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0055.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C083",
        "sourceRoleHint":  "사본 교환 해설자",
        "sourceCultureHint":  "강하 교역 혼거권·님소레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  48584
    },
    {
        "assetId":  "rnpc-f-mixed-0056",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0056.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C083",
        "sourceRoleHint":  "사본 교환 해설자",
        "sourceCultureHint":  "강하 교역 혼거권·님소레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  29766
    },
    {
        "assetId":  "rnpc-f-mixed-0057",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0057.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C085",
        "sourceRoleHint":  "철학 회합 좌표",
        "sourceCultureHint":  "강하 교역 혼거권·님소레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  107924
    },
    {
        "assetId":  "rnpc-f-mixed-0058",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0058.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C085",
        "sourceRoleHint":  "철학 회합 좌표",
        "sourceCultureHint":  "강하 교역 혼거권·님소레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  57872
    },
    {
        "assetId":  "rnpc-f-mixed-0059",
        "imagePath":  "/npc-assets/rnpc-f-mixed-0059.webp",
        "gender":  "female",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C085",
        "sourceRoleHint":  "철학 회합 좌표",
        "sourceCultureHint":  "강하 교역 혼거권·님소레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  41540
    },
    {
        "assetId":  "rnpc-f-outer-0001",
        "imagePath":  "/npc-assets/rnpc-f-outer-0001.webp",
        "gender":  "female",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C093",
        "sourceRoleHint":  "항만 대기 해설자",
        "sourceCultureHint":  "화산섬호 혼거권·드래곤스파이어 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  33154
    },
    {
        "assetId":  "rnpc-f-outer-0002",
        "imagePath":  "/npc-assets/rnpc-f-outer-0002.webp",
        "gender":  "female",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C093",
        "sourceRoleHint":  "항만 대기 해설자",
        "sourceCultureHint":  "화산섬호 혼거권·드래곤스파이어 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  49304
    },
    {
        "assetId":  "rnpc-f-outer-0003",
        "imagePath":  "/npc-assets/rnpc-f-outer-0003.webp",
        "gender":  "female",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C093",
        "sourceRoleHint":  "항만 대기 해설자",
        "sourceCultureHint":  "화산섬호 혼거권·드래곤스파이어 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  31060
    },
    {
        "assetId":  "rnpc-f-outer-0004",
        "imagePath":  "/npc-assets/rnpc-f-outer-0004.webp",
        "gender":  "female",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C095",
        "sourceRoleHint":  "분화 감시 좌표",
        "sourceCultureHint":  "화산섬호 혼거권·드래곤스파이어 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  33396
    },
    {
        "assetId":  "rnpc-f-outer-0005",
        "imagePath":  "/npc-assets/rnpc-f-outer-0005.webp",
        "gender":  "female",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C095",
        "sourceRoleHint":  "분화 감시 좌표",
        "sourceCultureHint":  "화산섬호 혼거권·드래곤스파이어 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  31004
    },
    {
        "assetId":  "rnpc-f-outer-0006",
        "imagePath":  "/npc-assets/rnpc-f-outer-0006.webp",
        "gender":  "female",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C095",
        "sourceRoleHint":  "분화 감시 좌표",
        "sourceCultureHint":  "화산섬호 혼거권·드래곤스파이어 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  30904
    },
    {
        "assetId":  "rnpc-f-outer-0007",
        "imagePath":  "/npc-assets/rnpc-f-outer-0007.webp",
        "gender":  "female",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C096",
        "sourceRoleHint":  "등대권 대표",
        "sourceCultureHint":  "외해 등대 혼거권·펜리르의 눈 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  35162
    },
    {
        "assetId":  "rnpc-f-outer-0008",
        "imagePath":  "/npc-assets/rnpc-f-outer-0008.webp",
        "gender":  "female",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C096",
        "sourceRoleHint":  "등대권 대표",
        "sourceCultureHint":  "외해 등대 혼거권·펜리르의 눈 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  30852
    },
    {
        "assetId":  "rnpc-f-outer-0009",
        "imagePath":  "/npc-assets/rnpc-f-outer-0009.webp",
        "gender":  "female",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C096",
        "sourceRoleHint":  "등대권 대표",
        "sourceCultureHint":  "외해 등대 혼거권·펜리르의 눈 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  27364
    },
    {
        "assetId":  "rnpc-f-outer-0010",
        "imagePath":  "/npc-assets/rnpc-f-outer-0010.webp",
        "gender":  "female",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C097",
        "sourceRoleHint":  "난파 기록 집행자",
        "sourceCultureHint":  "외해 등대 혼거권·펜리르의 눈 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  37476
    },
    {
        "assetId":  "rnpc-f-outer-0011",
        "imagePath":  "/npc-assets/rnpc-f-outer-0011.webp",
        "gender":  "female",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C097",
        "sourceRoleHint":  "난파 기록 집행자",
        "sourceCultureHint":  "외해 등대 혼거권·펜리르의 눈 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  23628
    },
    {
        "assetId":  "rnpc-f-outer-0012",
        "imagePath":  "/npc-assets/rnpc-f-outer-0012.webp",
        "gender":  "female",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C097",
        "sourceRoleHint":  "난파 기록 집행자",
        "sourceCultureHint":  "외해 등대 혼거권·펜리르의 눈 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  47746
    },
    {
        "assetId":  "rnpc-f-outer-0013",
        "imagePath":  "/npc-assets/rnpc-f-outer-0013.webp",
        "gender":  "female",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C099",
        "sourceRoleHint":  "등대 좌표",
        "sourceCultureHint":  "외해 등대 혼거권·펜리르의 눈 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  35444
    },
    {
        "assetId":  "rnpc-f-outer-0014",
        "imagePath":  "/npc-assets/rnpc-f-outer-0014.webp",
        "gender":  "female",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C099",
        "sourceRoleHint":  "등대 좌표",
        "sourceCultureHint":  "외해 등대 혼거권·펜리르의 눈 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  75296
    },
    {
        "assetId":  "rnpc-f-outer-0015",
        "imagePath":  "/npc-assets/rnpc-f-outer-0015.webp",
        "gender":  "female",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C099",
        "sourceRoleHint":  "등대 좌표",
        "sourceCultureHint":  "외해 등대 혼거권·펜리르의 눈 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  26164
    },
    {
        "assetId":  "rnpc-f-sylvania-0001",
        "imagePath":  "/npc-assets/rnpc-f-sylvania-0001.webp",
        "gender":  "female",
        "species":  "sylvania_forestline",
        "tier":  "curated",
        "sourceId":  "C086",
        "sourceRoleHint":  "숲 전승 대표",
        "sourceCultureHint":  "성림·탐사 혼거권·실바니아 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  35538
    },
    {
        "assetId":  "rnpc-f-sylvania-0002",
        "imagePath":  "/npc-assets/rnpc-f-sylvania-0002.webp",
        "gender":  "female",
        "species":  "sylvania_forestline",
        "tier":  "curated",
        "sourceId":  "C086",
        "sourceRoleHint":  "숲 전승 대표",
        "sourceCultureHint":  "성림·탐사 혼거권·실바니아 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  59958
    },
    {
        "assetId":  "rnpc-f-sylvania-0003",
        "imagePath":  "/npc-assets/rnpc-f-sylvania-0003.webp",
        "gender":  "female",
        "species":  "sylvania_forestline",
        "tier":  "curated",
        "sourceId":  "C086",
        "sourceRoleHint":  "숲 전승 대표",
        "sourceCultureHint":  "성림·탐사 혼거권·실바니아 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  32136
    },
    {
        "assetId":  "rnpc-f-sylvania-0004",
        "imagePath":  "/npc-assets/rnpc-f-sylvania-0004.webp",
        "gender":  "female",
        "species":  "sylvania_forestline",
        "tier":  "curated",
        "sourceId":  "C087",
        "sourceRoleHint":  "탐사 허가 집행자",
        "sourceCultureHint":  "성림·탐사 혼거권·실바니아 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  31848
    },
    {
        "assetId":  "rnpc-f-sylvania-0005",
        "imagePath":  "/npc-assets/rnpc-f-sylvania-0005.webp",
        "gender":  "female",
        "species":  "sylvania_forestline",
        "tier":  "curated",
        "sourceId":  "C087",
        "sourceRoleHint":  "탐사 허가 집행자",
        "sourceCultureHint":  "성림·탐사 혼거권·실바니아 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  57034
    },
    {
        "assetId":  "rnpc-f-sylvania-0006",
        "imagePath":  "/npc-assets/rnpc-f-sylvania-0006.webp",
        "gender":  "female",
        "species":  "sylvania_forestline",
        "tier":  "curated",
        "sourceId":  "C087",
        "sourceRoleHint":  "탐사 허가 집행자",
        "sourceCultureHint":  "성림·탐사 혼거권·실바니아 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  83438
    },
    {
        "assetId":  "rnpc-f-sylvania-0007",
        "imagePath":  "/npc-assets/rnpc-f-sylvania-0007.webp",
        "gender":  "female",
        "species":  "sylvania_forestline",
        "tier":  "curated",
        "sourceId":  "C089",
        "sourceRoleHint":  "숲 전승 좌표",
        "sourceCultureHint":  "성림·탐사 혼거권·실바니아 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  33284
    },
    {
        "assetId":  "rnpc-f-sylvania-0008",
        "imagePath":  "/npc-assets/rnpc-f-sylvania-0008.webp",
        "gender":  "female",
        "species":  "sylvania_forestline",
        "tier":  "curated",
        "sourceId":  "C089",
        "sourceRoleHint":  "숲 전승 좌표",
        "sourceCultureHint":  "성림·탐사 혼거권·실바니아 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  42108
    },
    {
        "assetId":  "rnpc-f-sylvania-0009",
        "imagePath":  "/npc-assets/rnpc-f-sylvania-0009.webp",
        "gender":  "female",
        "species":  "sylvania_forestline",
        "tier":  "curated",
        "sourceId":  "C089",
        "sourceRoleHint":  "숲 전승 좌표",
        "sourceCultureHint":  "성림·탐사 혼거권·실바니아 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  41470
    },
    {
        "assetId":  "rnpc-m-masked-0001",
        "imagePath":  "/npc-assets/rnpc-m-masked-0001.webp",
        "gender":  "male",
        "species":  "beastlike_or_masked_misc",
        "tier":  "curated",
        "sourceId":  "C048",
        "sourceRoleHint":  "동맹 기록 해설자",
        "sourceCultureHint":  "산악·학술 혼거권·옌메베트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  66236
    },
    {
        "assetId":  "rnpc-m-human-0001",
        "imagePath":  "/npc-assets/rnpc-m-human-0001.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C001",
        "sourceRoleHint":  "궁정 권위대표",
        "sourceCultureHint":  "인간계·레오니아 궁정권",
        "sourceAgeHint":  "중년",
        "bytes":  32914
    },
    {
        "assetId":  "rnpc-m-human-0002",
        "imagePath":  "/npc-assets/rnpc-m-human-0002.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C001",
        "sourceRoleHint":  "궁정 권위대표",
        "sourceCultureHint":  "인간계·레오니아 궁정권",
        "sourceAgeHint":  "중년",
        "bytes":  34246
    },
    {
        "assetId":  "rnpc-m-human-0003",
        "imagePath":  "/npc-assets/rnpc-m-human-0003.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C001",
        "sourceRoleHint":  "궁정 권위대표",
        "sourceCultureHint":  "인간계·레오니아 궁정권",
        "sourceAgeHint":  "중년",
        "bytes":  25748
    },
    {
        "assetId":  "rnpc-m-human-0004",
        "imagePath":  "/npc-assets/rnpc-m-human-0004.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C002",
        "sourceRoleHint":  "기사 봉토 집행자",
        "sourceCultureHint":  "인간계·레오니아 궁정권",
        "sourceAgeHint":  "중년",
        "bytes":  32504
    },
    {
        "assetId":  "rnpc-m-human-0005",
        "imagePath":  "/npc-assets/rnpc-m-human-0005.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C002",
        "sourceRoleHint":  "기사 봉토 집행자",
        "sourceCultureHint":  "인간계·레오니아 궁정권",
        "sourceAgeHint":  "중년",
        "bytes":  23280
    },
    {
        "assetId":  "rnpc-m-human-0006",
        "imagePath":  "/npc-assets/rnpc-m-human-0006.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C004",
        "sourceRoleHint":  "궁정 출입 좌표",
        "sourceCultureHint":  "인간계·레오니아 궁정권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  42938
    },
    {
        "assetId":  "rnpc-m-human-0007",
        "imagePath":  "/npc-assets/rnpc-m-human-0007.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C004",
        "sourceRoleHint":  "궁정 출입 좌표",
        "sourceCultureHint":  "인간계·레오니아 궁정권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  37720
    },
    {
        "assetId":  "rnpc-m-human-0008",
        "imagePath":  "/npc-assets/rnpc-m-human-0008.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C004",
        "sourceRoleHint":  "궁정 출입 좌표",
        "sourceCultureHint":  "인간계·레오니아 궁정권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  29160
    },
    {
        "assetId":  "rnpc-m-human-0009",
        "imagePath":  "/npc-assets/rnpc-m-human-0009.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C008",
        "sourceRoleHint":  "등대·난파 해설자",
        "sourceCultureHint":  "인간계·노르가르드 항만권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  72568
    },
    {
        "assetId":  "rnpc-m-human-0010",
        "imagePath":  "/npc-assets/rnpc-m-human-0010.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C008",
        "sourceRoleHint":  "등대·난파 해설자",
        "sourceCultureHint":  "인간계·노르가르드 항만권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  72218
    },
    {
        "assetId":  "rnpc-m-human-0011",
        "imagePath":  "/npc-assets/rnpc-m-human-0011.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C008",
        "sourceRoleHint":  "등대·난파 해설자",
        "sourceCultureHint":  "인간계·노르가르드 항만권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  57874
    },
    {
        "assetId":  "rnpc-m-human-0012",
        "imagePath":  "/npc-assets/rnpc-m-human-0012.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C010",
        "sourceRoleHint":  "철강 좌표",
        "sourceCultureHint":  "인간계·노르가르드 항만권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  43742
    },
    {
        "assetId":  "rnpc-m-human-0013",
        "imagePath":  "/npc-assets/rnpc-m-human-0013.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C010",
        "sourceRoleHint":  "철강 좌표",
        "sourceCultureHint":  "인간계·노르가르드 항만권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  33154
    },
    {
        "assetId":  "rnpc-m-human-0014",
        "imagePath":  "/npc-assets/rnpc-m-human-0014.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C010",
        "sourceRoleHint":  "철강 좌표",
        "sourceCultureHint":  "인간계·노르가르드 항만권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  31892
    },
    {
        "assetId":  "rnpc-m-human-0015",
        "imagePath":  "/npc-assets/rnpc-m-human-0015.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C011",
        "sourceRoleHint":  "왕실 법정 대표",
        "sourceCultureHint":  "인간계·티리스 서부 접경권",
        "sourceAgeHint":  "중년",
        "bytes":  23000
    },
    {
        "assetId":  "rnpc-m-human-0016",
        "imagePath":  "/npc-assets/rnpc-m-human-0016.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C012",
        "sourceRoleHint":  "접경 성문 집행자",
        "sourceCultureHint":  "인간계·티리스 서부 접경권",
        "sourceAgeHint":  "중년",
        "bytes":  31822
    },
    {
        "assetId":  "rnpc-m-human-0017",
        "imagePath":  "/npc-assets/rnpc-m-human-0017.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C014",
        "sourceRoleHint":  "왕실 법정 좌표",
        "sourceCultureHint":  "인간계·티리스 서부 접경권",
        "sourceAgeHint":  "중년",
        "bytes":  73130
    },
    {
        "assetId":  "rnpc-m-human-0018",
        "imagePath":  "/npc-assets/rnpc-m-human-0018.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C018",
        "sourceRoleHint":  "필사 거리 해설자",
        "sourceCultureHint":  "인간계·린레네트 학예권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  29724
    },
    {
        "assetId":  "rnpc-m-human-0019",
        "imagePath":  "/npc-assets/rnpc-m-human-0019.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C020",
        "sourceRoleHint":  "극장 좌표",
        "sourceCultureHint":  "인간계·린레네트 학예권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  29200
    },
    {
        "assetId":  "rnpc-m-human-0020",
        "imagePath":  "/npc-assets/rnpc-m-human-0020.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C020",
        "sourceRoleHint":  "극장 좌표",
        "sourceCultureHint":  "인간계·린레네트 학예권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  36282
    },
    {
        "assetId":  "rnpc-m-human-0021",
        "imagePath":  "/npc-assets/rnpc-m-human-0021.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C021",
        "sourceRoleHint":  "방어 평의회 대표",
        "sourceCultureHint":  "인간계·벡도레트 성채권",
        "sourceAgeHint":  "중년",
        "bytes":  74866
    },
    {
        "assetId":  "rnpc-m-human-0022",
        "imagePath":  "/npc-assets/rnpc-m-human-0022.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C022",
        "sourceRoleHint":  "외성문 집행자",
        "sourceCultureHint":  "인간계·벡도레트 성채권",
        "sourceAgeHint":  "중년",
        "bytes":  31920
    },
    {
        "assetId":  "rnpc-m-human-0023",
        "imagePath":  "/npc-assets/rnpc-m-human-0023.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C022",
        "sourceRoleHint":  "외성문 집행자",
        "sourceCultureHint":  "인간계·벡도레트 성채권",
        "sourceAgeHint":  "중년",
        "bytes":  71672
    },
    {
        "assetId":  "rnpc-m-human-0024",
        "imagePath":  "/npc-assets/rnpc-m-human-0024.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C024",
        "sourceRoleHint":  "내성 좌표",
        "sourceCultureHint":  "인간계·벡도레트 성채권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  64736
    },
    {
        "assetId":  "rnpc-m-human-0025",
        "imagePath":  "/npc-assets/rnpc-m-human-0025.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C024",
        "sourceRoleHint":  "내성 좌표",
        "sourceCultureHint":  "인간계·벡도레트 성채권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  43256
    },
    {
        "assetId":  "rnpc-m-human-0026",
        "imagePath":  "/npc-assets/rnpc-m-human-0026.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C024",
        "sourceRoleHint":  "내성 좌표",
        "sourceCultureHint":  "인간계·벡도레트 성채권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  28334
    },
    {
        "assetId":  "rnpc-m-human-0027",
        "imagePath":  "/npc-assets/rnpc-m-human-0027.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C028",
        "sourceRoleHint":  "농촌 공동체 해설자",
        "sourceCultureHint":  "인간계·센할레트 공동창고권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  38652
    },
    {
        "assetId":  "rnpc-m-human-0028",
        "imagePath":  "/npc-assets/rnpc-m-human-0028.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C028",
        "sourceRoleHint":  "농촌 공동체 해설자",
        "sourceCultureHint":  "인간계·센할레트 공동창고권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  35764
    },
    {
        "assetId":  "rnpc-m-human-0029",
        "imagePath":  "/npc-assets/rnpc-m-human-0029.webp",
        "gender":  "male",
        "species":  "human_lineage",
        "tier":  "curated",
        "sourceId":  "C030",
        "sourceRoleHint":  "수로 회의 좌표",
        "sourceCultureHint":  "인간계·센할레트 공동창고권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  33670
    },
    {
        "assetId":  "rnpc-m-mixed-0001",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0001.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C031",
        "sourceRoleHint":  "저장고 산악 대표",
        "sourceCultureHint":  "북방 혼거권·헤스페레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  32114
    },
    {
        "assetId":  "rnpc-m-mixed-0002",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0002.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C032",
        "sourceRoleHint":  "고개 초소 집행자",
        "sourceCultureHint":  "북방 혼거권·헤스페레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  23694
    },
    {
        "assetId":  "rnpc-m-mixed-0003",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0003.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C034",
        "sourceRoleHint":  "저장고 좌표",
        "sourceCultureHint":  "북방 혼거권·헤스페레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  23298
    },
    {
        "assetId":  "rnpc-m-mixed-0004",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0004.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C040",
        "sourceRoleHint":  "원정 허가 좌표",
        "sourceCultureHint":  "북방 혼거권·켈나베트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  30318
    },
    {
        "assetId":  "rnpc-m-mixed-0005",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0005.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C041",
        "sourceRoleHint":  "혹한 저장 대표",
        "sourceCultureHint":  "북방 혼거권·헤스베케트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  25176
    },
    {
        "assetId":  "rnpc-m-mixed-0006",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0006.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C042",
        "sourceRoleHint":  "겨울 통행 집행자",
        "sourceCultureHint":  "북방 혼거권·헤스베케트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  25940
    },
    {
        "assetId":  "rnpc-m-mixed-0007",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0007.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C042",
        "sourceRoleHint":  "겨울 통행 집행자",
        "sourceCultureHint":  "북방 혼거권·헤스베케트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  25570
    },
    {
        "assetId":  "rnpc-m-mixed-0008",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0008.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C044",
        "sourceRoleHint":  "혹한 저장 좌표",
        "sourceCultureHint":  "북방 혼거권·헤스베케트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  32648
    },
    {
        "assetId":  "rnpc-m-mixed-0009",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0009.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C048",
        "sourceRoleHint":  "동맹 기록 해설자",
        "sourceCultureHint":  "산악·학술 혼거권·옌메베트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  31872
    },
    {
        "assetId":  "rnpc-m-mixed-0010",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0010.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C048",
        "sourceRoleHint":  "동맹 기록 해설자",
        "sourceCultureHint":  "산악·학술 혼거권·옌메베트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  58944
    },
    {
        "assetId":  "rnpc-m-mixed-0011",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0011.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C050",
        "sourceRoleHint":  "기수단 좌표",
        "sourceCultureHint":  "산악·학술 혼거권·옌메베트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  34814
    },
    {
        "assetId":  "rnpc-m-mixed-0012",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0012.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C051",
        "sourceRoleHint":  "감찰 대표",
        "sourceCultureHint":  "산악·학술 혼거권·님나레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  35792
    },
    {
        "assetId":  "rnpc-m-mixed-0013",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0013.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C051",
        "sourceRoleHint":  "감찰 대표",
        "sourceCultureHint":  "산악·학술 혼거권·님나레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  67126
    },
    {
        "assetId":  "rnpc-m-mixed-0014",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0014.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C052",
        "sourceRoleHint":  "재료 장부 집행자",
        "sourceCultureHint":  "산악·학술 혼거권·님나레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  37790
    },
    {
        "assetId":  "rnpc-m-mixed-0015",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0015.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C052",
        "sourceRoleHint":  "재료 장부 집행자",
        "sourceCultureHint":  "산악·학술 혼거권·님나레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  40974
    },
    {
        "assetId":  "rnpc-m-mixed-0016",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0016.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C052",
        "sourceRoleHint":  "재료 장부 집행자",
        "sourceCultureHint":  "산악·학술 혼거권·님나레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  90986
    },
    {
        "assetId":  "rnpc-m-mixed-0017",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0017.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C054",
        "sourceRoleHint":  "감찰 좌표",
        "sourceCultureHint":  "산악·학술 혼거권·님나레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  27966
    },
    {
        "assetId":  "rnpc-m-mixed-0018",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0018.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C058",
        "sourceRoleHint":  "강하 교역 해설자",
        "sourceCultureHint":  "산악·학술 혼거권·실니메트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  28040
    },
    {
        "assetId":  "rnpc-m-mixed-0019",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0019.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C060",
        "sourceRoleHint":  "약초 장터 좌표",
        "sourceCultureHint":  "산악·학술 혼거권·실니메트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  38716
    },
    {
        "assetId":  "rnpc-m-mixed-0020",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0020.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C060",
        "sourceRoleHint":  "약초 장터 좌표",
        "sourceCultureHint":  "산악·학술 혼거권·실니메트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  33510
    },
    {
        "assetId":  "rnpc-m-mixed-0021",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0021.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C061",
        "sourceRoleHint":  "산악 신정 대표",
        "sourceCultureHint":  "산악·학술 혼거권·아르도레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  42848
    },
    {
        "assetId":  "rnpc-m-mixed-0022",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0022.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C061",
        "sourceRoleHint":  "산악 신정 대표",
        "sourceCultureHint":  "산악·학술 혼거권·아르도레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  32866
    },
    {
        "assetId":  "rnpc-m-mixed-0023",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0023.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C061",
        "sourceRoleHint":  "산악 신정 대표",
        "sourceCultureHint":  "산악·학술 혼거권·아르도레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  25048
    },
    {
        "assetId":  "rnpc-m-mixed-0024",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0024.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C062",
        "sourceRoleHint":  "관측대 집행자",
        "sourceCultureHint":  "산악·학술 혼거권·아르도레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  27348
    },
    {
        "assetId":  "rnpc-m-mixed-0025",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0025.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C062",
        "sourceRoleHint":  "관측대 집행자",
        "sourceCultureHint":  "산악·학술 혼거권·아르도레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  30896
    },
    {
        "assetId":  "rnpc-m-mixed-0026",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0026.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C064",
        "sourceRoleHint":  "수도원 좌표",
        "sourceCultureHint":  "산악·학술 혼거권·아르도레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  32398
    },
    {
        "assetId":  "rnpc-m-mixed-0027",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0027.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C068",
        "sourceRoleHint":  "이동 장부 해설자",
        "sourceCultureHint":  "초지 유목 혼거권·가르메베트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  38948
    },
    {
        "assetId":  "rnpc-m-mixed-0028",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0028.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C068",
        "sourceRoleHint":  "이동 장부 해설자",
        "sourceCultureHint":  "초지 유목 혼거권·가르메베트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  29434
    },
    {
        "assetId":  "rnpc-m-mixed-0029",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0029.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C068",
        "sourceRoleHint":  "이동 장부 해설자",
        "sourceCultureHint":  "초지 유목 혼거권·가르메베트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  34130
    },
    {
        "assetId":  "rnpc-m-mixed-0030",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0030.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C070",
        "sourceRoleHint":  "물가 약속 좌표",
        "sourceCultureHint":  "초지 유목 혼거권·가르메베트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  33516
    },
    {
        "assetId":  "rnpc-m-mixed-0031",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0031.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C071",
        "sourceRoleHint":  "성림 대표",
        "sourceCultureHint":  "성림 혼거권·실할레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  29834
    },
    {
        "assetId":  "rnpc-m-mixed-0032",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0032.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C071",
        "sourceRoleHint":  "성림 대표",
        "sourceCultureHint":  "성림 혼거권·실할레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  69036
    },
    {
        "assetId":  "rnpc-m-mixed-0033",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0033.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C071",
        "sourceRoleHint":  "성림 대표",
        "sourceCultureHint":  "성림 혼거권·실할레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  34578
    },
    {
        "assetId":  "rnpc-m-mixed-0034",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0034.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C072",
        "sourceRoleHint":  "숲 감시 집행자",
        "sourceCultureHint":  "성림 혼거권·실할레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  76104
    },
    {
        "assetId":  "rnpc-m-mixed-0035",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0035.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C072",
        "sourceRoleHint":  "숲 감시 집행자",
        "sourceCultureHint":  "성림 혼거권·실할레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  29858
    },
    {
        "assetId":  "rnpc-m-mixed-0036",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0036.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C074",
        "sourceRoleHint":  "성림 의례 좌표",
        "sourceCultureHint":  "성림 혼거권·실할레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  34234
    },
    {
        "assetId":  "rnpc-m-mixed-0037",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0037.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C074",
        "sourceRoleHint":  "성림 의례 좌표",
        "sourceCultureHint":  "성림 혼거권·실할레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  107050
    },
    {
        "assetId":  "rnpc-m-mixed-0038",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0038.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C074",
        "sourceRoleHint":  "성림 의례 좌표",
        "sourceCultureHint":  "성림 혼거권·실할레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  33820
    },
    {
        "assetId":  "rnpc-m-mixed-0039",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0039.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C078",
        "sourceRoleHint":  "상업 법정 해설자",
        "sourceCultureHint":  "강하 교역 혼거권·메르할레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  48568
    },
    {
        "assetId":  "rnpc-m-mixed-0040",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0040.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C078",
        "sourceRoleHint":  "상업 법정 해설자",
        "sourceCultureHint":  "강하 교역 혼거권·메르할레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  93208
    },
    {
        "assetId":  "rnpc-m-mixed-0041",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0041.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C078",
        "sourceRoleHint":  "상업 법정 해설자",
        "sourceCultureHint":  "강하 교역 혼거권·메르할레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  22954
    },
    {
        "assetId":  "rnpc-m-mixed-0042",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0042.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C080",
        "sourceRoleHint":  "상인 의회 좌표",
        "sourceCultureHint":  "강하 교역 혼거권·메르할레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  50524
    },
    {
        "assetId":  "rnpc-m-mixed-0043",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0043.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C080",
        "sourceRoleHint":  "상인 의회 좌표",
        "sourceCultureHint":  "강하 교역 혼거권·메르할레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  29656
    },
    {
        "assetId":  "rnpc-m-mixed-0044",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0044.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C080",
        "sourceRoleHint":  "상인 의회 좌표",
        "sourceCultureHint":  "강하 교역 혼거권·메르할레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  68060
    },
    {
        "assetId":  "rnpc-m-mixed-0045",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0045.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C081",
        "sourceRoleHint":  "학문·종교 대표",
        "sourceCultureHint":  "강하 교역 혼거권·님소레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  31854
    },
    {
        "assetId":  "rnpc-m-mixed-0046",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0046.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C082",
        "sourceRoleHint":  "철학 회합 집행자",
        "sourceCultureHint":  "강하 교역 혼거권·님소레트 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  25910
    },
    {
        "assetId":  "rnpc-m-mixed-0047",
        "imagePath":  "/npc-assets/rnpc-m-mixed-0047.webp",
        "gender":  "male",
        "species":  "mixed_contact_humanoid",
        "tier":  "curated",
        "sourceId":  "C084",
        "sourceRoleHint":  "학당 좌표",
        "sourceCultureHint":  "강하 교역 혼거권·님소레트 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  28416
    },
    {
        "assetId":  "rnpc-m-outer-0001",
        "imagePath":  "/npc-assets/rnpc-m-outer-0001.webp",
        "gender":  "male",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C091",
        "sourceRoleHint":  "화산 항로 대표",
        "sourceCultureHint":  "화산섬호 혼거권·드래곤스파이어 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  29852
    },
    {
        "assetId":  "rnpc-m-outer-0002",
        "imagePath":  "/npc-assets/rnpc-m-outer-0002.webp",
        "gender":  "male",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C091",
        "sourceRoleHint":  "화산 항로 대표",
        "sourceCultureHint":  "화산섬호 혼거권·드래곤스파이어 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  42146
    },
    {
        "assetId":  "rnpc-m-outer-0003",
        "imagePath":  "/npc-assets/rnpc-m-outer-0003.webp",
        "gender":  "male",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C091",
        "sourceRoleHint":  "화산 항로 대표",
        "sourceCultureHint":  "화산섬호 혼거권·드래곤스파이어 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  32914
    },
    {
        "assetId":  "rnpc-m-outer-0004",
        "imagePath":  "/npc-assets/rnpc-m-outer-0004.webp",
        "gender":  "male",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C092",
        "sourceRoleHint":  "분화 감시 집행자",
        "sourceCultureHint":  "화산섬호 혼거권·드래곤스파이어 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  31200
    },
    {
        "assetId":  "rnpc-m-outer-0005",
        "imagePath":  "/npc-assets/rnpc-m-outer-0005.webp",
        "gender":  "male",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C092",
        "sourceRoleHint":  "분화 감시 집행자",
        "sourceCultureHint":  "화산섬호 혼거권·드래곤스파이어 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  38502
    },
    {
        "assetId":  "rnpc-m-outer-0006",
        "imagePath":  "/npc-assets/rnpc-m-outer-0006.webp",
        "gender":  "male",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C092",
        "sourceRoleHint":  "분화 감시 집행자",
        "sourceCultureHint":  "화산섬호 혼거권·드래곤스파이어 문화권",
        "sourceAgeHint":  "중년",
        "bytes":  60772
    },
    {
        "assetId":  "rnpc-m-outer-0007",
        "imagePath":  "/npc-assets/rnpc-m-outer-0007.webp",
        "gender":  "male",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C094",
        "sourceRoleHint":  "화산 항로 좌표",
        "sourceCultureHint":  "화산섬호 혼거권·드래곤스파이어 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  30550
    },
    {
        "assetId":  "rnpc-m-outer-0008",
        "imagePath":  "/npc-assets/rnpc-m-outer-0008.webp",
        "gender":  "male",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C098",
        "sourceRoleHint":  "구조 대기 해설자",
        "sourceCultureHint":  "외해 등대 혼거권·펜리르의 눈 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  33524
    },
    {
        "assetId":  "rnpc-m-outer-0009",
        "imagePath":  "/npc-assets/rnpc-m-outer-0009.webp",
        "gender":  "male",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C098",
        "sourceRoleHint":  "구조 대기 해설자",
        "sourceCultureHint":  "외해 등대 혼거권·펜리르의 눈 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  32878
    },
    {
        "assetId":  "rnpc-m-outer-0010",
        "imagePath":  "/npc-assets/rnpc-m-outer-0010.webp",
        "gender":  "male",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C098",
        "sourceRoleHint":  "구조 대기 해설자",
        "sourceCultureHint":  "외해 등대 혼거권·펜리르의 눈 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  20720
    },
    {
        "assetId":  "rnpc-m-outer-0011",
        "imagePath":  "/npc-assets/rnpc-m-outer-0011.webp",
        "gender":  "male",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C100",
        "sourceRoleHint":  "난파 기록 좌표",
        "sourceCultureHint":  "외해 등대 혼거권·펜리르의 눈 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  31682
    },
    {
        "assetId":  "rnpc-m-outer-0012",
        "imagePath":  "/npc-assets/rnpc-m-outer-0012.webp",
        "gender":  "male",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C100",
        "sourceRoleHint":  "난파 기록 좌표",
        "sourceCultureHint":  "외해 등대 혼거권·펜리르의 눈 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  33454
    },
    {
        "assetId":  "rnpc-m-outer-0013",
        "imagePath":  "/npc-assets/rnpc-m-outer-0013.webp",
        "gender":  "male",
        "species":  "outer_sea_lighthouse_lineage",
        "tier":  "curated",
        "sourceId":  "C100",
        "sourceRoleHint":  "난파 기록 좌표",
        "sourceCultureHint":  "외해 등대 혼거권·펜리르의 눈 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  55496
    },
    {
        "assetId":  "rnpc-m-sylvania-0001",
        "imagePath":  "/npc-assets/rnpc-m-sylvania-0001.webp",
        "gender":  "male",
        "species":  "sylvania_forestline",
        "tier":  "curated",
        "sourceId":  "C088",
        "sourceRoleHint":  "사본 열람 해설자",
        "sourceCultureHint":  "성림·탐사 혼거권·실바니아 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  35220
    },
    {
        "assetId":  "rnpc-m-sylvania-0002",
        "imagePath":  "/npc-assets/rnpc-m-sylvania-0002.webp",
        "gender":  "male",
        "species":  "sylvania_forestline",
        "tier":  "curated",
        "sourceId":  "C088",
        "sourceRoleHint":  "사본 열람 해설자",
        "sourceCultureHint":  "성림·탐사 혼거권·실바니아 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  51644
    },
    {
        "assetId":  "rnpc-m-sylvania-0003",
        "imagePath":  "/npc-assets/rnpc-m-sylvania-0003.webp",
        "gender":  "male",
        "species":  "sylvania_forestline",
        "tier":  "curated",
        "sourceId":  "C088",
        "sourceRoleHint":  "사본 열람 해설자",
        "sourceCultureHint":  "성림·탐사 혼거권·실바니아 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  77010
    },
    {
        "assetId":  "rnpc-m-sylvania-0004",
        "imagePath":  "/npc-assets/rnpc-m-sylvania-0004.webp",
        "gender":  "male",
        "species":  "sylvania_forestline",
        "tier":  "curated",
        "sourceId":  "C090",
        "sourceRoleHint":  "탐사 거점 좌표",
        "sourceCultureHint":  "성림·탐사 혼거권·실바니아 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  74886
    },
    {
        "assetId":  "rnpc-m-sylvania-0005",
        "imagePath":  "/npc-assets/rnpc-m-sylvania-0005.webp",
        "gender":  "male",
        "species":  "sylvania_forestline",
        "tier":  "curated",
        "sourceId":  "C090",
        "sourceRoleHint":  "탐사 거점 좌표",
        "sourceCultureHint":  "성림·탐사 혼거권·실바니아 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  30986
    },
    {
        "assetId":  "rnpc-m-sylvania-0006",
        "imagePath":  "/npc-assets/rnpc-m-sylvania-0006.webp",
        "gender":  "male",
        "species":  "sylvania_forestline",
        "tier":  "curated",
        "sourceId":  "C090",
        "sourceRoleHint":  "탐사 거점 좌표",
        "sourceCultureHint":  "성림·탐사 혼거권·실바니아 문화권",
        "sourceAgeHint":  "청년~중년",
        "bytes":  55616
    }
] as const;
