// Auto-generated by tools/build_vireth_talk_background_assets.mjs
export const GENERATED_TALK_BACKGROUNDS = [
  {
    "key": "city-representative-ardolet",
    "aliases": [
      "13_N013_ardolet_dorsorhal_rectangular_monastery_v52_00001_",
      "ardolet",
      "아르돌레트",
      "dorsorhal",
      "ardolet-dorsorhal"
    ],
    "kind": "city_representative",
    "regionKey": "ardolet",
    "regionName": "아르돌레트",
    "cityAlias": "dorsorhal",
    "imageUrl": "/talk-background-assets/city-representative/ardolet.webp",
    "sourceAssetId": "13_N013_ardolet_dorsorhal_rectangular_monastery_v52_00001_",
    "priority": 80
  },
  {
    "key": "city-representative-bekdoret",
    "aliases": [
      "05_N005_bekdoret_dorkar_outer_gate_empty_eyelevel_v51_00001_",
      "bekdoret",
      "베크도레트",
      "dorkar",
      "bekdoret-dorkar",
      "MIL"
    ],
    "kind": "city_representative",
    "regionKey": "bekdoret",
    "regionName": "베크도레트",
    "cityAlias": "dorkar",
    "bgType": "MIL",
    "imageUrl": "/talk-background-assets/city-representative/bekdoret.webp",
    "sourceAssetId": "05_N005_bekdoret_dorkar_outer_gate_empty_eyelevel_v51_00001_",
    "priority": 80
  },
  {
    "key": "city-representative-dragonspire",
    "aliases": [
      "19_N019_dragonspire_narmarkel_basalt_watch_station_lowfantasy_v41_00001_",
      "dragonspire",
      "드래곤스파이어",
      "narmarkel",
      "dragonspire-narmarkel"
    ],
    "kind": "city_representative",
    "regionKey": "dragonspire",
    "regionName": "드래곤스파이어",
    "cityAlias": "narmarkel",
    "imageUrl": "/talk-background-assets/city-representative/dragonspire.webp",
    "sourceAssetId": "19_N019_dragonspire_narmarkel_basalt_watch_station_lowfantasy_v41_00001_",
    "priority": 80
  },
  {
    "key": "city-representative-fenrir-eye",
    "aliases": [
      "20_N020_fenrir_eye_dunartor_wreck_record_lighthouse_lowfantasy_v41_00001_",
      "fenrir-eye",
      "펜리르의 눈",
      "eye",
      "fenrir-eye-eye",
      "POR"
    ],
    "kind": "city_representative",
    "regionKey": "fenrir-eye",
    "regionName": "펜리르의 눈",
    "cityAlias": "eye",
    "bgType": "POR",
    "imageUrl": "/talk-background-assets/city-representative/fenrir-eye.webp",
    "sourceAssetId": "20_N020_fenrir_eye_dunartor_wreck_record_lighthouse_lowfantasy_v41_00001_",
    "priority": 80
  },
  {
    "key": "city-representative-garmebet",
    "aliases": [
      "14_N014_garmebet_tikmebhal_near_camp_well_v52_00001_",
      "garmebet",
      "가르메베트",
      "tikmebhal",
      "garmebet-tikmebhal",
      "NAT"
    ],
    "kind": "city_representative",
    "regionKey": "garmebet",
    "regionName": "가르메베트",
    "cityAlias": "tikmebhal",
    "bgType": "NAT",
    "imageUrl": "/talk-background-assets/city-representative/garmebet.webp",
    "sourceAssetId": "14_N014_garmebet_tikmebhal_near_camp_well_v52_00001_",
    "priority": 80
  },
  {
    "key": "city-representative-hesbeket",
    "aliases": [
      "09_N009_hesbeket_bekhespukum_winter_storage_street_lowfantasy_v41_00001_",
      "hesbeket",
      "헤스베케트",
      "bekhespukum",
      "hesbeket-bekhespukum"
    ],
    "kind": "city_representative",
    "regionKey": "hesbeket",
    "regionName": "헤스베케트",
    "cityAlias": "bekhespukum",
    "imageUrl": "/talk-background-assets/city-representative/hesbeket.webp",
    "sourceAssetId": "09_N009_hesbeket_bekhespukum_winter_storage_street_lowfantasy_v41_00001_",
    "priority": 80
  },
  {
    "key": "city-representative-hesferet",
    "aliases": [
      "07_N007_hesferet_hespukum_pass_storehouse_empty_noanimal_v52_00001_",
      "hesferet",
      "헤스페레트",
      "hespukum",
      "hesferet-hespukum"
    ],
    "kind": "city_representative",
    "regionKey": "hesferet",
    "regionName": "헤스페레트",
    "cityAlias": "hespukum",
    "imageUrl": "/talk-background-assets/city-representative/hesferet.webp",
    "sourceAssetId": "07_N007_hesferet_hespukum_pass_storehouse_empty_noanimal_v52_00001_",
    "priority": 80
  },
  {
    "key": "city-representative-kelnabet",
    "aliases": [
      "08_N008_kelnabet_markelmir_freeport_sailing_quay_lowfantasy_v42_00001_",
      "kelnabet",
      "켈나베트",
      "markelmir",
      "kelnabet-markelmir",
      "POR"
    ],
    "kind": "city_representative",
    "regionKey": "kelnabet",
    "regionName": "켈나베트",
    "cityAlias": "markelmir",
    "bgType": "POR",
    "imageUrl": "/talk-background-assets/city-representative/kelnabet.webp",
    "sourceAssetId": "08_N008_kelnabet_markelmir_freeport_sailing_quay_lowfantasy_v42_00001_",
    "priority": 80
  },
  {
    "key": "city-representative-leonia",
    "aliases": [
      "01_N001_leonia_radarel_court_district_lowfantasy_v41_00001_",
      "leonia",
      "레오니아",
      "radarel",
      "leonia-radarel",
      "ADM"
    ],
    "kind": "city_representative",
    "regionKey": "leonia",
    "regionName": "레오니아",
    "cityAlias": "radarel",
    "bgType": "ADM",
    "imageUrl": "/talk-background-assets/city-representative/leonia.webp",
    "sourceAssetId": "01_N001_leonia_radarel_court_district_lowfantasy_v41_00001_",
    "priority": 80
  },
  {
    "key": "city-representative-linrenet",
    "aliases": [
      "04_N004_linrenet_lenumga_record_lane_theater_lowfantasy_v42_00001_",
      "linrenet",
      "린레네트",
      "lenumga",
      "linrenet-lenumga"
    ],
    "kind": "city_representative",
    "regionKey": "linrenet",
    "regionName": "린레네트",
    "cityAlias": "lenumga",
    "imageUrl": "/talk-background-assets/city-representative/linrenet.webp",
    "sourceAssetId": "04_N004_linrenet_lenumga_record_lane_theater_lowfantasy_v42_00001_",
    "priority": 80
  },
  {
    "key": "city-representative-merhalet",
    "aliases": [
      "16_N016_merhalet_merbelmar_exterior_customs_quay_v52_00001_",
      "merhalet",
      "메르할레트",
      "merbelmar",
      "merhalet-merbelmar",
      "POR"
    ],
    "kind": "city_representative",
    "regionKey": "merhalet",
    "regionName": "메르할레트",
    "cityAlias": "merbelmar",
    "bgType": "POR",
    "imageUrl": "/talk-background-assets/city-representative/merhalet.webp",
    "sourceAssetId": "16_N016_merhalet_merbelmar_exterior_customs_quay_v52_00001_",
    "priority": 80
  },
  {
    "key": "city-representative-nimnaret",
    "aliases": [
      "11_N011_nimnaret_yalbekum_academy_courtyard_no_void_v52_00001_",
      "nimnaret",
      "님나레트",
      "yalbekum",
      "nimnaret-yalbekum",
      "EDU"
    ],
    "kind": "city_representative",
    "regionKey": "nimnaret",
    "regionName": "님나레트",
    "cityAlias": "yalbekum",
    "bgType": "EDU",
    "imageUrl": "/talk-background-assets/city-representative/nimnaret.webp",
    "sourceAssetId": "11_N011_nimnaret_yalbekum_academy_courtyard_no_void_v52_00001_",
    "priority": 80
  },
  {
    "key": "city-representative-nimsolet",
    "aliases": [
      "17_N017_nimsolet_nimhal_school_copyist_courtyard_lowfantasy_v41_00001_",
      "nimsolet",
      "님솔레트",
      "nimhal",
      "nimsolet-nimhal",
      "EDU"
    ],
    "kind": "city_representative",
    "regionKey": "nimsolet",
    "regionName": "님솔레트",
    "cityAlias": "nimhal",
    "bgType": "EDU",
    "imageUrl": "/talk-background-assets/city-representative/nimsolet.webp",
    "sourceAssetId": "17_N017_nimsolet_nimhal_school_copyist_courtyard_lowfantasy_v41_00001_",
    "priority": 80
  },
  {
    "key": "city-representative-norghard",
    "aliases": [
      "02_N002_norgard_marnavmir_naval_tax_quay_lowfantasy_v41_00001_",
      "norghard",
      "노르가르드",
      "marnavmir",
      "norghard-marnavmir",
      "POR"
    ],
    "kind": "city_representative",
    "regionKey": "norghard",
    "regionName": "노르가르드",
    "cityAlias": "marnavmir",
    "bgType": "POR",
    "imageUrl": "/talk-background-assets/city-representative/norghard.webp",
    "sourceAssetId": "02_N002_norgard_marnavmir_naval_tax_quay_lowfantasy_v41_00001_",
    "priority": 80
  },
  {
    "key": "city-representative-senhalet",
    "aliases": [
      "06_N006_senhalet_senpukum_granary_watergate_lowfantasy_v41_00001_",
      "senhalet",
      "센할레트",
      "senpukum",
      "senhalet-senpukum",
      "MIL"
    ],
    "kind": "city_representative",
    "regionKey": "senhalet",
    "regionName": "센할레트",
    "cityAlias": "senpukum",
    "bgType": "MIL",
    "imageUrl": "/talk-background-assets/city-representative/senhalet.webp",
    "sourceAssetId": "06_N006_senhalet_senpukum_granary_watergate_lowfantasy_v41_00001_",
    "priority": 80
  },
  {
    "key": "city-representative-silhalet",
    "aliases": [
      "15_N015_silhalet_radsilhal_forest_permit_empty_eyelevel_v51_00001_",
      "silhalet",
      "실할레트",
      "radsilhal",
      "silhalet-radsilhal",
      "NAT"
    ],
    "kind": "city_representative",
    "regionKey": "silhalet",
    "regionName": "실할레트",
    "cityAlias": "radsilhal",
    "bgType": "NAT",
    "imageUrl": "/talk-background-assets/city-representative/silhalet.webp",
    "sourceAssetId": "15_N015_silhalet_radsilhal_forest_permit_empty_eyelevel_v51_00001_",
    "priority": 80
  },
  {
    "key": "city-representative-silnimet",
    "aliases": [
      "12_N012_silnimet_silmermir_herb_river_temple_lowfantasy_v41_00001_",
      "silnimet",
      "실니메트",
      "silmermir",
      "silnimet-silmermir",
      "REL"
    ],
    "kind": "city_representative",
    "regionKey": "silnimet",
    "regionName": "실니메트",
    "cityAlias": "silmermir",
    "bgType": "REL",
    "imageUrl": "/talk-background-assets/city-representative/silnimet.webp",
    "sourceAssetId": "12_N012_silnimet_silmermir_herb_river_temple_lowfantasy_v41_00001_",
    "priority": 80
  },
  {
    "key": "city-representative-sylvania",
    "aliases": [
      "18_N018_sylvania_silensan_forest_guide_empty_eyelevel_v51_00001_",
      "sylvania",
      "실바니아",
      "silensan",
      "sylvania-silensan",
      "NAT"
    ],
    "kind": "city_representative",
    "regionKey": "sylvania",
    "regionName": "실바니아",
    "cityAlias": "silensan",
    "bgType": "NAT",
    "imageUrl": "/talk-background-assets/city-representative/sylvania.webp",
    "sourceAssetId": "18_N018_sylvania_silensan_forest_guide_empty_eyelevel_v51_00001_",
    "priority": 80
  },
  {
    "key": "city-representative-tiris",
    "aliases": [
      "03_N003_tiris_radvarhal_estate_archive_seed_hall_lowfantasy_v41_00001_",
      "tiris",
      "티리스",
      "radvarhal",
      "tiris-radvarhal",
      "ADM"
    ],
    "kind": "city_representative",
    "regionKey": "tiris",
    "regionName": "티리스",
    "cityAlias": "radvarhal",
    "bgType": "ADM",
    "imageUrl": "/talk-background-assets/city-representative/tiris.webp",
    "sourceAssetId": "03_N003_tiris_radvarhal_estate_archive_seed_hall_lowfantasy_v41_00001_",
    "priority": 80
  },
  {
    "key": "city-representative-yenmebet",
    "aliases": [
      "10_N010_yenmebet_yenworkel_forest_checkpoint_dirtroad_lowfantasy_v42_00001_",
      "yenmebet",
      "옌메베트",
      "yenworkel",
      "yenmebet-yenworkel",
      "NAT"
    ],
    "kind": "city_representative",
    "regionKey": "yenmebet",
    "regionName": "옌메베트",
    "cityAlias": "yenworkel",
    "bgType": "NAT",
    "imageUrl": "/talk-background-assets/city-representative/yenmebet.webp",
    "sourceAssetId": "10_N010_yenmebet_yenworkel_forest_checkpoint_dirtroad_lowfantasy_v42_00001_",
    "priority": 80
  },
  {
    "key": "region-default-ardolet",
    "aliases": [
      "13_NATDEF_ARD_ardolet_final",
      "ardolet",
      "아르돌레트",
      "final",
      "ardolet-final"
    ],
    "kind": "region_default",
    "regionKey": "ardolet",
    "regionName": "아르돌레트",
    "cityAlias": "final",
    "imageUrl": "/talk-background-assets/region-default/ardolet.webp",
    "sourceAssetId": "13_NATDEF_ARD_ardolet_final",
    "priority": 50
  },
  {
    "key": "region-default-bekdoret",
    "aliases": [
      "05_NATDEF_BEK_bekdoret_final",
      "bekdoret",
      "베크도레트",
      "final",
      "bekdoret-final"
    ],
    "kind": "region_default",
    "regionKey": "bekdoret",
    "regionName": "베크도레트",
    "cityAlias": "final",
    "imageUrl": "/talk-background-assets/region-default/bekdoret.webp",
    "sourceAssetId": "05_NATDEF_BEK_bekdoret_final",
    "priority": 50
  },
  {
    "key": "region-default-dragonspire",
    "aliases": [
      "19_NATDEF_DRA_dragonspire_final",
      "dragonspire",
      "드래곤스파이어",
      "final",
      "dragonspire-final"
    ],
    "kind": "region_default",
    "regionKey": "dragonspire",
    "regionName": "드래곤스파이어",
    "cityAlias": "final",
    "imageUrl": "/talk-background-assets/region-default/dragonspire.webp",
    "sourceAssetId": "19_NATDEF_DRA_dragonspire_final",
    "priority": 50
  },
  {
    "key": "region-default-fenrir-eye",
    "aliases": [
      "20_NATDEF_FEN_fenrir-eye_final",
      "fenrir-eye",
      "펜리르의 눈",
      "final",
      "fenrir-eye-final"
    ],
    "kind": "region_default",
    "regionKey": "fenrir-eye",
    "regionName": "펜리르의 눈",
    "cityAlias": "final",
    "imageUrl": "/talk-background-assets/region-default/fenrir-eye.webp",
    "sourceAssetId": "20_NATDEF_FEN_fenrir-eye_final",
    "priority": 50
  },
  {
    "key": "region-default-garmebet",
    "aliases": [
      "14_NATDEF_GAR_garmebet_final",
      "garmebet",
      "가르메베트",
      "final",
      "garmebet-final"
    ],
    "kind": "region_default",
    "regionKey": "garmebet",
    "regionName": "가르메베트",
    "cityAlias": "final",
    "imageUrl": "/talk-background-assets/region-default/garmebet.webp",
    "sourceAssetId": "14_NATDEF_GAR_garmebet_final",
    "priority": 50
  },
  {
    "key": "region-default-hesbeket",
    "aliases": [
      "09_NATDEF_HEB_hesbeket_final",
      "hesbeket",
      "헤스베케트",
      "final",
      "hesbeket-final"
    ],
    "kind": "region_default",
    "regionKey": "hesbeket",
    "regionName": "헤스베케트",
    "cityAlias": "final",
    "imageUrl": "/talk-background-assets/region-default/hesbeket.webp",
    "sourceAssetId": "09_NATDEF_HEB_hesbeket_final",
    "priority": 50
  },
  {
    "key": "region-default-hesferet",
    "aliases": [
      "07_NATDEF_HEF_hesferet_final",
      "hesferet",
      "헤스페레트",
      "final",
      "hesferet-final"
    ],
    "kind": "region_default",
    "regionKey": "hesferet",
    "regionName": "헤스페레트",
    "cityAlias": "final",
    "imageUrl": "/talk-background-assets/region-default/hesferet.webp",
    "sourceAssetId": "07_NATDEF_HEF_hesferet_final",
    "priority": 50
  },
  {
    "key": "region-default-kelnabet",
    "aliases": [
      "08_NATDEF_KEL_kelnabet_final",
      "kelnabet",
      "켈나베트",
      "final",
      "kelnabet-final"
    ],
    "kind": "region_default",
    "regionKey": "kelnabet",
    "regionName": "켈나베트",
    "cityAlias": "final",
    "imageUrl": "/talk-background-assets/region-default/kelnabet.webp",
    "sourceAssetId": "08_NATDEF_KEL_kelnabet_final",
    "priority": 50
  },
  {
    "key": "region-default-leonia",
    "aliases": [
      "01_NATDEF_LEO_leonia_final",
      "leonia",
      "레오니아",
      "final",
      "leonia-final"
    ],
    "kind": "region_default",
    "regionKey": "leonia",
    "regionName": "레오니아",
    "cityAlias": "final",
    "imageUrl": "/talk-background-assets/region-default/leonia.webp",
    "sourceAssetId": "01_NATDEF_LEO_leonia_final",
    "priority": 50
  },
  {
    "key": "region-default-linrenet",
    "aliases": [
      "04_NATDEF_LIN_linrenet_final",
      "linrenet",
      "린레네트",
      "final",
      "linrenet-final"
    ],
    "kind": "region_default",
    "regionKey": "linrenet",
    "regionName": "린레네트",
    "cityAlias": "final",
    "imageUrl": "/talk-background-assets/region-default/linrenet.webp",
    "sourceAssetId": "04_NATDEF_LIN_linrenet_final",
    "priority": 50
  },
  {
    "key": "region-default-merhalet",
    "aliases": [
      "16_NATDEF_MER_merhalet_final",
      "merhalet",
      "메르할레트",
      "final",
      "merhalet-final"
    ],
    "kind": "region_default",
    "regionKey": "merhalet",
    "regionName": "메르할레트",
    "cityAlias": "final",
    "imageUrl": "/talk-background-assets/region-default/merhalet.webp",
    "sourceAssetId": "16_NATDEF_MER_merhalet_final",
    "priority": 50
  },
  {
    "key": "region-default-nimnaret",
    "aliases": [
      "11_NATDEF_NIN_nimnaret_final",
      "nimnaret",
      "님나레트",
      "final",
      "nimnaret-final"
    ],
    "kind": "region_default",
    "regionKey": "nimnaret",
    "regionName": "님나레트",
    "cityAlias": "final",
    "imageUrl": "/talk-background-assets/region-default/nimnaret.webp",
    "sourceAssetId": "11_NATDEF_NIN_nimnaret_final",
    "priority": 50
  },
  {
    "key": "region-default-nimsolet",
    "aliases": [
      "17_NATDEF_NIS_nimsolet_final",
      "nimsolet",
      "님솔레트",
      "final",
      "nimsolet-final"
    ],
    "kind": "region_default",
    "regionKey": "nimsolet",
    "regionName": "님솔레트",
    "cityAlias": "final",
    "imageUrl": "/talk-background-assets/region-default/nimsolet.webp",
    "sourceAssetId": "17_NATDEF_NIS_nimsolet_final",
    "priority": 50
  },
  {
    "key": "region-default-norghard",
    "aliases": [
      "02_NATDEF_NOR_norghard_final",
      "norghard",
      "노르가르드",
      "final",
      "norghard-final"
    ],
    "kind": "region_default",
    "regionKey": "norghard",
    "regionName": "노르가르드",
    "cityAlias": "final",
    "imageUrl": "/talk-background-assets/region-default/norghard.webp",
    "sourceAssetId": "02_NATDEF_NOR_norghard_final",
    "priority": 50
  },
  {
    "key": "region-default-senhalet",
    "aliases": [
      "06_NATDEF_SEN_senhalet_final",
      "senhalet",
      "센할레트",
      "final",
      "senhalet-final"
    ],
    "kind": "region_default",
    "regionKey": "senhalet",
    "regionName": "센할레트",
    "cityAlias": "final",
    "imageUrl": "/talk-background-assets/region-default/senhalet.webp",
    "sourceAssetId": "06_NATDEF_SEN_senhalet_final",
    "priority": 50
  },
  {
    "key": "region-default-silhalet",
    "aliases": [
      "15_NATDEF_SIH_silhalet_final",
      "silhalet",
      "실할레트",
      "final",
      "silhalet-final"
    ],
    "kind": "region_default",
    "regionKey": "silhalet",
    "regionName": "실할레트",
    "cityAlias": "final",
    "imageUrl": "/talk-background-assets/region-default/silhalet.webp",
    "sourceAssetId": "15_NATDEF_SIH_silhalet_final",
    "priority": 50
  },
  {
    "key": "region-default-silnimet",
    "aliases": [
      "12_NATDEF_SIN_silnimet_final",
      "silnimet",
      "실니메트",
      "final",
      "silnimet-final"
    ],
    "kind": "region_default",
    "regionKey": "silnimet",
    "regionName": "실니메트",
    "cityAlias": "final",
    "imageUrl": "/talk-background-assets/region-default/silnimet.webp",
    "sourceAssetId": "12_NATDEF_SIN_silnimet_final",
    "priority": 50
  },
  {
    "key": "region-default-sylvania",
    "aliases": [
      "18_NATDEF_SYL_sylvania_final",
      "sylvania",
      "실바니아",
      "final",
      "sylvania-final"
    ],
    "kind": "region_default",
    "regionKey": "sylvania",
    "regionName": "실바니아",
    "cityAlias": "final",
    "imageUrl": "/talk-background-assets/region-default/sylvania.webp",
    "sourceAssetId": "18_NATDEF_SYL_sylvania_final",
    "priority": 50
  },
  {
    "key": "region-default-tiris",
    "aliases": [
      "03_NATDEF_TIR_tiris_final",
      "tiris",
      "티리스",
      "final",
      "tiris-final"
    ],
    "kind": "region_default",
    "regionKey": "tiris",
    "regionName": "티리스",
    "cityAlias": "final",
    "imageUrl": "/talk-background-assets/region-default/tiris.webp",
    "sourceAssetId": "03_NATDEF_TIR_tiris_final",
    "priority": 50
  },
  {
    "key": "region-default-yenmebet",
    "aliases": [
      "10_NATDEF_YEN_yenmebet_final",
      "yenmebet",
      "옌메베트",
      "final",
      "yenmebet-final"
    ],
    "kind": "region_default",
    "regionKey": "yenmebet",
    "regionName": "옌메베트",
    "cityAlias": "final",
    "imageUrl": "/talk-background-assets/region-default/yenmebet.webp",
    "sourceAssetId": "10_NATDEF_YEN_yenmebet_final",
    "priority": 50
  }
] as const;
