// Generated by tools/build_vireth_region_map_place_index.mjs. Do not edit by hand.
export const GENERATED_REGION_MAP_PLACES = [
  {
    "regionKey": "leonia",
    "regionName": "레오니아",
    "outputOrder": 1,
    "title": "렘다트움",
    "aliases": [
      "렘다트움"
    ],
    "kind": "도시·거점",
    "icon": "castle",
    "gridX": 88,
    "gridY": 12,
    "pixelX": 1387,
    "pixelY": 213,
    "mapXPct": 86.69,
    "mapYPct": 13.31,
    "order": 1
  },
  {
    "regionKey": "leonia",
    "regionName": "레오니아",
    "outputOrder": 1,
    "title": "라드아르할",
    "aliases": [
      "라드아르할"
    ],
    "kind": "도시·거점",
    "icon": "city",
    "gridX": 46.5455,
    "gridY": 33.7143,
    "pixelX": 745,
    "pixelY": 539,
    "mapXPct": 46.56,
    "mapYPct": 33.69,
    "order": 2
  },
  {
    "regionKey": "leonia",
    "regionName": "레오니아",
    "outputOrder": 1,
    "title": "렘켈가",
    "aliases": [
      "렘켈가"
    ],
    "kind": "숙소촌",
    "icon": "village",
    "gridX": 88,
    "gridY": 22.8571,
    "pixelX": 1387,
    "pixelY": 672,
    "mapXPct": 86.69,
    "mapYPct": 42,
    "order": 3
  },
  {
    "regionKey": "leonia",
    "regionName": "레오니아",
    "outputOrder": 1,
    "title": "지르바르에트",
    "aliases": [
      "지르바르에트"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 18.9091,
    "gridY": 55.4286,
    "pixelX": 303,
    "pixelY": 887,
    "mapXPct": 18.94,
    "mapYPct": 55.44,
    "order": 4
  },
  {
    "regionKey": "leonia",
    "regionName": "레오니아",
    "outputOrder": 1,
    "title": "라드가르가",
    "aliases": [
      "라드가르가"
    ],
    "kind": "마을",
    "icon": "village",
    "gridX": 39.6364,
    "gridY": 44.5714,
    "pixelX": 787,
    "pixelY": 1019,
    "mapXPct": 49.19,
    "mapYPct": 63.69,
    "order": 5
  },
  {
    "regionKey": "leonia",
    "regionName": "레오니아",
    "outputOrder": 1,
    "title": "지르메브가",
    "aliases": [
      "지르메브가"
    ],
    "kind": "마을",
    "icon": "village",
    "gridX": 12,
    "gridY": 66.2857,
    "pixelX": 213,
    "pixelY": 1332,
    "mapXPct": 13.31,
    "mapYPct": 83.25,
    "order": 6
  },
  {
    "regionKey": "leonia",
    "regionName": "레오니아",
    "outputOrder": 1,
    "title": "팔테쿰가",
    "aliases": [
      "팔테쿰가"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 67.2727,
    "gridY": 88,
    "pixelX": 1076,
    "pixelY": 1387,
    "mapXPct": 67.25,
    "mapYPct": 86.69,
    "order": 7
  },
  {
    "regionKey": "leonia",
    "regionName": "레오니아",
    "outputOrder": 1,
    "title": "팔테크가",
    "aliases": [
      "팔테크가"
    ],
    "kind": "작업촌",
    "icon": "village",
    "gridX": 60.3636,
    "gridY": 88,
    "pixelX": 966,
    "pixelY": 1408,
    "mapXPct": 60.38,
    "mapYPct": 88,
    "order": 8
  },
  {
    "regionKey": "norghard",
    "regionName": "노르가르드",
    "outputOrder": 2,
    "title": "마르토르가",
    "aliases": [
      "마르토르가"
    ],
    "kind": "구조물 마을",
    "icon": "watchtower",
    "gridX": 18.9091,
    "gridY": 12,
    "pixelX": 303,
    "pixelY": 192,
    "mapXPct": 18.94,
    "mapYPct": 12,
    "order": 1
  },
  {
    "regionKey": "norghard",
    "regionName": "노르가르드",
    "outputOrder": 2,
    "title": "아르마르토르",
    "aliases": [
      "아르마르토르"
    ],
    "kind": "도시·거점",
    "icon": "stronghold",
    "gridX": 12,
    "gridY": 12,
    "pixelX": 213,
    "pixelY": 213,
    "mapXPct": 13.31,
    "mapYPct": 13.31,
    "order": 2
  },
  {
    "regionKey": "norghard",
    "regionName": "노르가르드",
    "outputOrder": 2,
    "title": "마르나브미르",
    "aliases": [
      "마르나브미르"
    ],
    "kind": "도시·거점",
    "icon": "port",
    "gridX": 53.4545,
    "gridY": 27.2,
    "pixelX": 855,
    "pixelY": 435,
    "mapXPct": 53.44,
    "mapYPct": 27.19,
    "order": 3
  },
  {
    "regionKey": "norghard",
    "regionName": "노르가르드",
    "outputOrder": 2,
    "title": "헤스마르가",
    "aliases": [
      "헤스마르가"
    ],
    "kind": "어항",
    "icon": "port",
    "gridX": 32.7273,
    "gridY": 19.6,
    "pixelX": 401,
    "pixelY": 644,
    "mapXPct": 25.06,
    "mapYPct": 40.25,
    "order": 4
  },
  {
    "regionKey": "norghard",
    "regionName": "노르가르드",
    "outputOrder": 2,
    "title": "페르나브부두",
    "aliases": [
      "페르나브부두"
    ],
    "kind": "도시·거점",
    "icon": "port",
    "gridX": 88,
    "gridY": 50,
    "pixelX": 1387,
    "pixelY": 800,
    "mapXPct": 86.69,
    "mapYPct": 50,
    "order": 5
  },
  {
    "regionKey": "norghard",
    "regionName": "노르가르드",
    "outputOrder": 2,
    "title": "페르테크가",
    "aliases": [
      "페르테크가"
    ],
    "kind": "작업촌",
    "icon": "village",
    "gridX": 81.0909,
    "gridY": 57.6,
    "pixelX": 1297,
    "pixelY": 922,
    "mapXPct": 81.06,
    "mapYPct": 57.63,
    "order": 6
  },
  {
    "regionKey": "norghard",
    "regionName": "노르가르드",
    "outputOrder": 2,
    "title": "나브할가",
    "aliases": [
      "나브할가"
    ],
    "kind": "도시·거점",
    "icon": "port",
    "gridX": 74.1818,
    "gridY": 80.4,
    "pixelX": 1187,
    "pixelY": 1286,
    "mapXPct": 74.19,
    "mapYPct": 80.38,
    "order": 7
  },
  {
    "regionKey": "norghard",
    "regionName": "노르가르드",
    "outputOrder": 2,
    "title": "나브할가린",
    "aliases": [
      "나브할가린"
    ],
    "kind": "숙소촌",
    "icon": "village",
    "gridX": 74.1818,
    "gridY": 88,
    "pixelX": 1187,
    "pixelY": 1408,
    "mapXPct": 74.19,
    "mapYPct": 88,
    "order": 8
  },
  {
    "regionKey": "tiris",
    "regionName": "티리스",
    "outputOrder": 3,
    "title": "실테크에트",
    "aliases": [
      "실테크에트"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 68,
    "gridY": 12,
    "pixelX": 1088,
    "pixelY": 213,
    "mapXPct": 68,
    "mapYPct": 13.31,
    "order": 1
  },
  {
    "regionKey": "tiris",
    "regionName": "티리스",
    "outputOrder": 3,
    "title": "실베크가",
    "aliases": [
      "실베크가"
    ],
    "kind": "마을",
    "icon": "village",
    "gridX": 68,
    "gridY": 18.9091,
    "pixelX": 1088,
    "pixelY": 303,
    "mapXPct": 68,
    "mapYPct": 18.94,
    "order": 2
  },
  {
    "regionKey": "tiris",
    "regionName": "티리스",
    "outputOrder": 3,
    "title": "소르이엘토르",
    "aliases": [
      "소르이엘토르"
    ],
    "kind": "도시·거점",
    "icon": "temple",
    "gridX": 88,
    "gridY": 25.8182,
    "pixelX": 1408,
    "pixelY": 413,
    "mapXPct": 88,
    "mapYPct": 25.81,
    "order": 3
  },
  {
    "regionKey": "tiris",
    "regionName": "티리스",
    "outputOrder": 3,
    "title": "이엘토르가",
    "aliases": [
      "이엘토르가"
    ],
    "kind": "신전촌",
    "icon": "temple",
    "gridX": 88,
    "gridY": 32.7273,
    "pixelX": 1408,
    "pixelY": 524,
    "mapXPct": 88,
    "mapYPct": 32.75,
    "order": 4
  },
  {
    "regionKey": "tiris",
    "regionName": "티리스",
    "outputOrder": 3,
    "title": "라드바르할(실버킵)",
    "aliases": [
      "라드바르할(실버킵)"
    ],
    "kind": "도시·거점",
    "icon": "castle",
    "gridX": 56,
    "gridY": 39.6364,
    "pixelX": 896,
    "pixelY": 634,
    "mapXPct": 56,
    "mapYPct": 39.63,
    "order": 5
  },
  {
    "regionKey": "tiris",
    "regionName": "티리스",
    "outputOrder": 3,
    "title": "베크켈카르(레이븐스톤)",
    "aliases": [
      "베크켈카르(레이븐스톤)"
    ],
    "kind": "도시·거점",
    "icon": "castle",
    "gridX": 24,
    "gridY": 46.5455,
    "pixelX": 384,
    "pixelY": 745,
    "mapXPct": 24,
    "mapYPct": 46.56,
    "order": 6
  },
  {
    "regionKey": "tiris",
    "regionName": "티리스",
    "outputOrder": 3,
    "title": "베크벱가",
    "aliases": [
      "베크벱가"
    ],
    "kind": "피난촌",
    "icon": "stronghold",
    "gridX": 20,
    "gridY": 53.4545,
    "pixelX": 320,
    "pixelY": 855,
    "mapXPct": 20,
    "mapYPct": 53.44,
    "order": 7
  },
  {
    "regionKey": "tiris",
    "regionName": "티리스",
    "outputOrder": 3,
    "title": "벨소르엘",
    "aliases": [
      "벨소르엘"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 76,
    "gridY": 60.3636,
    "pixelX": 1216,
    "pixelY": 966,
    "mapXPct": 76,
    "mapYPct": 60.38,
    "order": 8
  },
  {
    "regionKey": "tiris",
    "regionName": "티리스",
    "outputOrder": 3,
    "title": "그린할로우",
    "aliases": [
      "그린할로우"
    ],
    "kind": "도시·거점",
    "icon": "ruin",
    "gridX": 12,
    "gridY": 67.2727,
    "pixelX": 243,
    "pixelY": 1176,
    "mapXPct": 15.19,
    "mapYPct": 73.5,
    "order": 9
  },
  {
    "regionKey": "tiris",
    "regionName": "티리스",
    "outputOrder": 3,
    "title": "헤크가르가",
    "aliases": [
      "헤크가르가"
    ],
    "kind": "재개간촌",
    "icon": "ruin",
    "gridX": 16,
    "gridY": 74.1818,
    "pixelX": 256,
    "pixelY": 1187,
    "mapXPct": 16,
    "mapYPct": 74.19,
    "order": 10
  },
  {
    "regionKey": "tiris",
    "regionName": "티리스",
    "outputOrder": 3,
    "title": "가르메브에트",
    "aliases": [
      "가르메브에트"
    ],
    "kind": "도시·거점",
    "icon": "market",
    "gridX": 52,
    "gridY": 81.0909,
    "pixelX": 832,
    "pixelY": 1297,
    "mapXPct": 52,
    "mapYPct": 81.06,
    "order": 11
  },
  {
    "regionKey": "tiris",
    "regionName": "티리스",
    "outputOrder": 3,
    "title": "벨렐가",
    "aliases": [
      "벨렐가"
    ],
    "kind": "마을",
    "icon": "village",
    "gridX": 76,
    "gridY": 67.2727,
    "pixelX": 1369,
    "pixelY": 1382,
    "mapXPct": 85.56,
    "mapYPct": 86.38,
    "order": 12
  },
  {
    "regionKey": "tiris",
    "regionName": "티리스",
    "outputOrder": 3,
    "title": "가르푸크가",
    "aliases": [
      "가르푸크가"
    ],
    "kind": "마을",
    "icon": "village",
    "gridX": 48,
    "gridY": 88,
    "pixelX": 768,
    "pixelY": 1408,
    "mapXPct": 48,
    "mapYPct": 88,
    "order": 13
  },
  {
    "regionKey": "tiris",
    "regionName": "티리스",
    "outputOrder": 3,
    "title": "뉴할로우",
    "aliases": [
      "뉴할로우"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 28,
    "gridY": 88,
    "pixelX": 448,
    "pixelY": 1408,
    "mapXPct": 28,
    "mapYPct": 88,
    "order": 14
  },
  {
    "regionKey": "linrenet",
    "regionName": "린레네트",
    "outputOrder": 4,
    "title": "렘렌가",
    "aliases": [
      "렘렌가"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 12,
    "gridY": 12,
    "pixelX": 192,
    "pixelY": 192,
    "mapXPct": 12,
    "mapYPct": 12,
    "order": 1
  },
  {
    "regionKey": "linrenet",
    "regionName": "린레네트",
    "outputOrder": 4,
    "title": "렘렌필가",
    "aliases": [
      "렘렌필가"
    ],
    "kind": "작업가",
    "icon": "village",
    "gridX": 12,
    "gridY": 12,
    "pixelX": 192,
    "pixelY": 192,
    "mapXPct": 12,
    "mapYPct": 12,
    "order": 2
  },
  {
    "regionKey": "linrenet",
    "regionName": "린레네트",
    "outputOrder": 4,
    "title": "다트킨할",
    "aliases": [
      "다트킨할"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 69,
    "gridY": 12,
    "pixelX": 1104,
    "pixelY": 213,
    "mapXPct": 69,
    "mapYPct": 13.31,
    "order": 3
  },
  {
    "regionKey": "linrenet",
    "regionName": "린레네트",
    "outputOrder": 4,
    "title": "레눔가",
    "aliases": [
      "레눔가"
    ],
    "kind": "도시·거점",
    "icon": "market",
    "gridX": 31,
    "gridY": 31,
    "pixelX": 496,
    "pixelY": 496,
    "mapXPct": 31,
    "mapYPct": 31,
    "order": 4
  },
  {
    "regionKey": "linrenet",
    "regionName": "린레네트",
    "outputOrder": 4,
    "title": "린산가",
    "aliases": [
      "린산가"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 50,
    "gridY": 50,
    "pixelX": 800,
    "pixelY": 800,
    "mapXPct": 50,
    "mapYPct": 50,
    "order": 5
  },
  {
    "regionKey": "linrenet",
    "regionName": "린레네트",
    "outputOrder": 4,
    "title": "레눔숙가",
    "aliases": [
      "레눔숙가"
    ],
    "kind": "숙소가",
    "icon": "village",
    "gridX": 12,
    "gridY": 50,
    "pixelX": 192,
    "pixelY": 800,
    "mapXPct": 12,
    "mapYPct": 50,
    "order": 6
  },
  {
    "regionKey": "linrenet",
    "regionName": "린레네트",
    "outputOrder": 4,
    "title": "님렌할",
    "aliases": [
      "님렌할"
    ],
    "kind": "도시·거점",
    "icon": "market",
    "gridX": 12,
    "gridY": 69,
    "pixelX": 213,
    "pixelY": 1104,
    "mapXPct": 13.31,
    "mapYPct": 69,
    "order": 7
  },
  {
    "regionKey": "linrenet",
    "regionName": "린레네트",
    "outputOrder": 4,
    "title": "린산테크가",
    "aliases": [
      "린산테크가"
    ],
    "kind": "작업촌",
    "icon": "stronghold",
    "gridX": 50,
    "gridY": 69,
    "pixelX": 955,
    "pixelY": 1200,
    "mapXPct": 59.69,
    "mapYPct": 75,
    "order": 8
  },
  {
    "regionKey": "bekdoret",
    "regionName": "벡도레트",
    "outputOrder": 5,
    "title": "도르테쿰",
    "aliases": [
      "도르테쿰"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 88,
    "gridY": 12,
    "pixelX": 1387,
    "pixelY": 213,
    "mapXPct": 86.69,
    "mapYPct": 13.31,
    "order": 1
  },
  {
    "regionKey": "bekdoret",
    "regionName": "벡도레트",
    "outputOrder": 5,
    "title": "켈카르",
    "aliases": [
      "켈카르"
    ],
    "kind": "도시·거점",
    "icon": "castle",
    "gridX": 12,
    "gridY": 12,
    "pixelX": 213,
    "pixelY": 213,
    "mapXPct": 13.31,
    "mapYPct": 13.31,
    "order": 2
  },
  {
    "regionKey": "bekdoret",
    "regionName": "벡도레트",
    "outputOrder": 5,
    "title": "도르테크가",
    "aliases": [
      "도르테크가"
    ],
    "kind": "작업촌",
    "icon": "village",
    "gridX": 88,
    "gridY": 31,
    "pixelX": 1408,
    "pixelY": 496,
    "mapXPct": 88,
    "mapYPct": 31,
    "order": 3
  },
  {
    "regionKey": "bekdoret",
    "regionName": "벡도레트",
    "outputOrder": 5,
    "title": "도르카르",
    "aliases": [
      "도르카르"
    ],
    "kind": "도시·거점",
    "icon": "castle",
    "gridX": 50,
    "gridY": 31,
    "pixelX": 800,
    "pixelY": 496,
    "mapXPct": 50,
    "mapYPct": 31,
    "order": 4
  },
  {
    "regionKey": "bekdoret",
    "regionName": "벡도레트",
    "outputOrder": 5,
    "title": "켈베크가",
    "aliases": [
      "켈베크가"
    ],
    "kind": "관문촌",
    "icon": "watchtower",
    "gridX": 12,
    "gridY": 31,
    "pixelX": 230,
    "pixelY": 684,
    "mapXPct": 14.37,
    "mapYPct": 42.75,
    "order": 5
  },
  {
    "regionKey": "bekdoret",
    "regionName": "벡도레트",
    "outputOrder": 5,
    "title": "베크할",
    "aliases": [
      "베크할"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 69,
    "gridY": 50,
    "pixelX": 1104,
    "pixelY": 800,
    "mapXPct": 69,
    "mapYPct": 50,
    "order": 6
  },
  {
    "regionKey": "bekdoret",
    "regionName": "벡도레트",
    "outputOrder": 5,
    "title": "엔할가",
    "aliases": [
      "엔할가"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 31,
    "gridY": 69,
    "pixelX": 496,
    "pixelY": 1104,
    "mapXPct": 31,
    "mapYPct": 69,
    "order": 7
  },
  {
    "regionKey": "bekdoret",
    "regionName": "벡도레트",
    "outputOrder": 5,
    "title": "베크푸크가",
    "aliases": [
      "베크푸크가"
    ],
    "kind": "창고촌",
    "icon": "stronghold",
    "gridX": 69,
    "gridY": 69,
    "pixelX": 1259,
    "pixelY": 1200,
    "mapXPct": 78.69,
    "mapYPct": 75,
    "order": 8
  },
  {
    "regionKey": "senhalet",
    "regionName": "센할레트",
    "outputOrder": 6,
    "title": "센푸크에트",
    "aliases": [
      "센푸크에트"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 72.8,
    "gridY": 12,
    "pixelX": 1165,
    "pixelY": 213,
    "mapXPct": 72.81,
    "mapYPct": 13.31,
    "order": 1
  },
  {
    "regionKey": "senhalet",
    "regionName": "센할레트",
    "outputOrder": 6,
    "title": "센푸쿰",
    "aliases": [
      "센푸쿰"
    ],
    "kind": "도시·거점",
    "icon": "city",
    "gridX": 42.4,
    "gridY": 24.6667,
    "pixelX": 678,
    "pixelY": 395,
    "mapXPct": 42.38,
    "mapYPct": 24.69,
    "order": 2
  },
  {
    "regionKey": "senhalet",
    "regionName": "센할레트",
    "outputOrder": 6,
    "title": "센푸크가",
    "aliases": [
      "센푸크가"
    ],
    "kind": "마을",
    "icon": "stronghold",
    "gridX": 57.6,
    "gridY": 37.3333,
    "pixelX": 1077,
    "pixelY": 693,
    "mapXPct": 67.31,
    "mapYPct": 43.31,
    "order": 3
  },
  {
    "regionKey": "senhalet",
    "regionName": "센할레트",
    "outputOrder": 6,
    "title": "벨바르",
    "aliases": [
      "벨바르"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 12,
    "gridY": 50,
    "pixelX": 213,
    "pixelY": 800,
    "mapXPct": 13.31,
    "mapYPct": 50,
    "order": 4
  },
  {
    "regionKey": "senhalet",
    "regionName": "센할레트",
    "outputOrder": 6,
    "title": "벨테크가",
    "aliases": [
      "벨테크가"
    ],
    "kind": "작업촌",
    "icon": "village",
    "gridX": 12,
    "gridY": 50,
    "pixelX": 192,
    "pixelY": 800,
    "mapXPct": 12,
    "mapYPct": 50,
    "order": 5
  },
  {
    "regionKey": "senhalet",
    "regionName": "센할레트",
    "outputOrder": 6,
    "title": "벱렌할",
    "aliases": [
      "벱렌할"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 88,
    "gridY": 62.6667,
    "pixelX": 1387,
    "pixelY": 1003,
    "mapXPct": 86.69,
    "mapYPct": 62.69,
    "order": 6
  },
  {
    "regionKey": "senhalet",
    "regionName": "센할레트",
    "outputOrder": 6,
    "title": "벨나브가",
    "aliases": [
      "벨나브가"
    ],
    "kind": "나루촌",
    "icon": "port",
    "gridX": 27.2,
    "gridY": 62.6667,
    "pixelX": 687,
    "pixelY": 1006,
    "mapXPct": 42.94,
    "mapYPct": 62.88,
    "order": 7
  },
  {
    "regionKey": "senhalet",
    "regionName": "센할레트",
    "outputOrder": 6,
    "title": "가르센에트",
    "aliases": [
      "가르센에트"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 27.2,
    "gridY": 88,
    "pixelX": 435,
    "pixelY": 1387,
    "mapXPct": 27.19,
    "mapYPct": 86.69,
    "order": 8
  },
  {
    "regionKey": "senhalet",
    "regionName": "센할레트",
    "outputOrder": 6,
    "title": "가르센가",
    "aliases": [
      "가르센가"
    ],
    "kind": "마을",
    "icon": "village",
    "gridX": 27.2,
    "gridY": 88,
    "pixelX": 435,
    "pixelY": 1408,
    "mapXPct": 27.19,
    "mapYPct": 88,
    "order": 9
  },
  {
    "regionKey": "hesferet",
    "regionName": "헤스페레트",
    "outputOrder": 7,
    "title": "헤스켈카르",
    "aliases": [
      "헤스켈카르"
    ],
    "kind": "도시·거점",
    "icon": "castle",
    "gridX": 59.5,
    "gridY": 12,
    "pixelX": 952,
    "pixelY": 213,
    "mapXPct": 59.5,
    "mapYPct": 13.31,
    "order": 1
  },
  {
    "regionKey": "hesferet",
    "regionName": "헤스페레트",
    "outputOrder": 7,
    "title": "헤스푸쿰",
    "aliases": [
      "헤스푸쿰"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 31,
    "gridY": 34.8,
    "pixelX": 496,
    "pixelY": 557,
    "mapXPct": 31,
    "mapYPct": 34.81,
    "order": 2
  },
  {
    "regionKey": "hesferet",
    "regionName": "헤스페레트",
    "outputOrder": 7,
    "title": "켈헤스가",
    "aliases": [
      "켈헤스가"
    ],
    "kind": "숙소촌",
    "icon": "village",
    "gridX": 59.5,
    "gridY": 19.6,
    "pixelX": 1105,
    "pixelY": 620,
    "mapXPct": 69.06,
    "mapYPct": 38.75,
    "order": 3
  },
  {
    "regionKey": "hesferet",
    "regionName": "헤스페레트",
    "outputOrder": 7,
    "title": "헤스푸크가",
    "aliases": [
      "헤스푸크가"
    ],
    "kind": "마을",
    "icon": "village",
    "gridX": 31,
    "gridY": 42.4,
    "pixelX": 496,
    "pixelY": 678,
    "mapXPct": 31,
    "mapYPct": 42.38,
    "order": 4
  },
  {
    "regionKey": "hesferet",
    "regionName": "헤스페레트",
    "outputOrder": 7,
    "title": "도르페르가",
    "aliases": [
      "도르페르가"
    ],
    "kind": "광산촌",
    "icon": "village",
    "gridX": 21.5,
    "gridY": 50,
    "pixelX": 344,
    "pixelY": 800,
    "mapXPct": 21.5,
    "mapYPct": 50,
    "order": 5
  },
  {
    "regionKey": "hesferet",
    "regionName": "헤스페레트",
    "outputOrder": 7,
    "title": "페르바르",
    "aliases": [
      "페르바르"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 12,
    "gridY": 57.6,
    "pixelX": 213,
    "pixelY": 922,
    "mapXPct": 13.31,
    "mapYPct": 57.63,
    "order": 6
  },
  {
    "regionKey": "hesferet",
    "regionName": "헤스페레트",
    "outputOrder": 7,
    "title": "람지르가",
    "aliases": [
      "람지르가"
    ],
    "kind": "숙소촌",
    "icon": "village",
    "gridX": 40.5,
    "gridY": 72.8,
    "pixelX": 648,
    "pixelY": 1165,
    "mapXPct": 40.5,
    "mapYPct": 72.81,
    "order": 7
  },
  {
    "regionKey": "hesferet",
    "regionName": "헤스페레트",
    "outputOrder": 7,
    "title": "람지르바르",
    "aliases": [
      "람지르바르"
    ],
    "kind": "도시·거점",
    "icon": "temple",
    "gridX": 40.5,
    "gridY": 72.8,
    "pixelX": 648,
    "pixelY": 1165,
    "mapXPct": 40.5,
    "mapYPct": 72.81,
    "order": 8
  },
  {
    "regionKey": "hesferet",
    "regionName": "헤스페레트",
    "outputOrder": 7,
    "title": "메브켈에트",
    "aliases": [
      "메브켈에트"
    ],
    "kind": "도시·거점",
    "icon": "market",
    "gridX": 88,
    "gridY": 88,
    "pixelX": 1387,
    "pixelY": 1387,
    "mapXPct": 86.69,
    "mapYPct": 86.69,
    "order": 9
  },
  {
    "regionKey": "kelnabet",
    "regionName": "켈나베트",
    "outputOrder": 8,
    "title": "워크바르",
    "aliases": [
      "워크바르"
    ],
    "kind": "도시·거점",
    "icon": "port",
    "gridX": 88,
    "gridY": 12,
    "pixelX": 1387,
    "pixelY": 213,
    "mapXPct": 86.69,
    "mapYPct": 13.31,
    "order": 1
  },
  {
    "regionKey": "kelnabet",
    "regionName": "켈나베트",
    "outputOrder": 8,
    "title": "마르켈미르",
    "aliases": [
      "마르켈미르"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 57.6,
    "gridY": 28.8889,
    "pixelX": 922,
    "pixelY": 462,
    "mapXPct": 57.63,
    "mapYPct": 28.88,
    "order": 2
  },
  {
    "regionKey": "kelnabet",
    "regionName": "켈나베트",
    "outputOrder": 8,
    "title": "마르푸크섬",
    "aliases": [
      "마르푸크섬"
    ],
    "kind": "선착장",
    "icon": "port",
    "gridX": 65.2,
    "gridY": 45.7778,
    "pixelX": 1043,
    "pixelY": 732,
    "mapXPct": 65.19,
    "mapYPct": 45.75,
    "order": 3
  },
  {
    "regionKey": "kelnabet",
    "regionName": "켈나베트",
    "outputOrder": 8,
    "title": "나브렌가",
    "aliases": [
      "나브렌가"
    ],
    "kind": "기록촌",
    "icon": "village",
    "gridX": 42.4,
    "gridY": 54.2222,
    "pixelX": 678,
    "pixelY": 868,
    "mapXPct": 42.38,
    "mapYPct": 54.25,
    "order": 4
  },
  {
    "regionKey": "kelnabet",
    "regionName": "켈나베트",
    "outputOrder": 8,
    "title": "마르렌움",
    "aliases": [
      "마르렌움"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 42.4,
    "gridY": 54.2222,
    "pixelX": 678,
    "pixelY": 868,
    "mapXPct": 42.38,
    "mapYPct": 54.25,
    "order": 5
  },
  {
    "regionKey": "kelnabet",
    "regionName": "켈나베트",
    "outputOrder": 8,
    "title": "나브할",
    "aliases": [
      "나브할"
    ],
    "kind": "도시·거점",
    "icon": "port",
    "gridX": 72.8,
    "gridY": 71.1111,
    "pixelX": 1165,
    "pixelY": 1138,
    "mapXPct": 72.81,
    "mapYPct": 71.13,
    "order": 6
  },
  {
    "regionKey": "kelnabet",
    "regionName": "켈나베트",
    "outputOrder": 8,
    "title": "움마르켈",
    "aliases": [
      "움마르켈"
    ],
    "kind": "도시·거점",
    "icon": "port",
    "gridX": 12,
    "gridY": 88,
    "pixelX": 213,
    "pixelY": 1387,
    "mapXPct": 13.31,
    "mapYPct": 86.69,
    "order": 7
  },
  {
    "regionKey": "kelnabet",
    "regionName": "켈나베트",
    "outputOrder": 8,
    "title": "움나브가",
    "aliases": [
      "움나브가"
    ],
    "kind": "항구촌",
    "icon": "port",
    "gridX": 12,
    "gridY": 88,
    "pixelX": 192,
    "pixelY": 1408,
    "mapXPct": 12,
    "mapYPct": 88,
    "order": 8
  },
  {
    "regionKey": "hesbeket",
    "regionName": "헤스베케트",
    "outputOrder": 9,
    "title": "베크헤스푸쿰",
    "aliases": [
      "베크헤스푸쿰"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 40.5,
    "gridY": 12,
    "pixelX": 648,
    "pixelY": 213,
    "mapXPct": 40.5,
    "mapYPct": 13.31,
    "order": 1
  },
  {
    "regionKey": "hesbeket",
    "regionName": "헤스베케트",
    "outputOrder": 9,
    "title": "푸크헤스가",
    "aliases": [
      "푸크헤스가"
    ],
    "kind": "작업촌",
    "icon": "village",
    "gridX": 40.5,
    "gridY": 27.2,
    "pixelX": 648,
    "pixelY": 435,
    "mapXPct": 40.5,
    "mapYPct": 27.19,
    "order": 2
  },
  {
    "regionKey": "hesbeket",
    "regionName": "헤스베케트",
    "outputOrder": 9,
    "title": "나르할",
    "aliases": [
      "나르할"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 59.5,
    "gridY": 42.4,
    "pixelX": 952,
    "pixelY": 678,
    "mapXPct": 59.5,
    "mapYPct": 42.38,
    "order": 3
  },
  {
    "regionKey": "hesbeket",
    "regionName": "헤스베케트",
    "outputOrder": 9,
    "title": "헤스나르가",
    "aliases": [
      "헤스나르가"
    ],
    "kind": "공동주거촌",
    "icon": "village",
    "gridX": 59.5,
    "gridY": 42.4,
    "pixelX": 952,
    "pixelY": 678,
    "mapXPct": 59.5,
    "mapYPct": 42.38,
    "order": 4
  },
  {
    "regionKey": "hesbeket",
    "regionName": "헤스베케트",
    "outputOrder": 9,
    "title": "헤스워켈",
    "aliases": [
      "헤스워켈"
    ],
    "kind": "도시·거점",
    "icon": "castle",
    "gridX": 12,
    "gridY": 57.6,
    "pixelX": 213,
    "pixelY": 922,
    "mapXPct": 13.31,
    "mapYPct": 57.63,
    "order": 5
  },
  {
    "regionKey": "hesbeket",
    "regionName": "헤스베케트",
    "outputOrder": 9,
    "title": "메브헤스베크",
    "aliases": [
      "메브헤스베크"
    ],
    "kind": "도시·거점",
    "icon": "stronghold",
    "gridX": 88,
    "gridY": 88,
    "pixelX": 1387,
    "pixelY": 1387,
    "mapXPct": 86.69,
    "mapYPct": 86.69,
    "order": 6
  },
  {
    "regionKey": "hesbeket",
    "regionName": "헤스베케트",
    "outputOrder": 9,
    "title": "메브헤스가",
    "aliases": [
      "메브헤스가"
    ],
    "kind": "초소",
    "icon": "watchtower",
    "gridX": 88,
    "gridY": 88,
    "pixelX": 1408,
    "pixelY": 1408,
    "mapXPct": 88,
    "mapYPct": 88,
    "order": 7
  },
  {
    "regionKey": "yenmebet",
    "regionName": "옌메베트",
    "outputOrder": 10,
    "title": "옌베크할",
    "aliases": [
      "옌베크할"
    ],
    "kind": "도시·거점",
    "icon": "stronghold",
    "gridX": 88,
    "gridY": 12,
    "pixelX": 1387,
    "pixelY": 213,
    "mapXPct": 86.69,
    "mapYPct": 13.31,
    "order": 1
  },
  {
    "regionKey": "yenmebet",
    "regionName": "옌메베트",
    "outputOrder": 10,
    "title": "옌워켈",
    "aliases": [
      "옌워켈"
    ],
    "kind": "도시·거점",
    "icon": "stronghold",
    "gridX": 42.4,
    "gridY": 37.3333,
    "pixelX": 678,
    "pixelY": 597,
    "mapXPct": 42.38,
    "mapYPct": 37.31,
    "order": 2
  },
  {
    "regionKey": "yenmebet",
    "regionName": "옌메베트",
    "outputOrder": 10,
    "title": "옌테크가",
    "aliases": [
      "옌테크가"
    ],
    "kind": "작업촌",
    "icon": "village",
    "gridX": 88,
    "gridY": 20.4444,
    "pixelX": 1285,
    "pixelY": 657,
    "mapXPct": 80.31,
    "mapYPct": 41.06,
    "order": 3
  },
  {
    "regionKey": "yenmebet",
    "regionName": "옌메베트",
    "outputOrder": 10,
    "title": "옌켈가",
    "aliases": [
      "옌켈가"
    ],
    "kind": "숙소촌",
    "icon": "village",
    "gridX": 42.4,
    "gridY": 45.7778,
    "pixelX": 831,
    "pixelY": 1038,
    "mapXPct": 51.94,
    "mapYPct": 64.88,
    "order": 4
  },
  {
    "regionKey": "yenmebet",
    "regionName": "옌메베트",
    "outputOrder": 10,
    "title": "실베크에트",
    "aliases": [
      "실베크에트"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 12,
    "gridY": 71.1111,
    "pixelX": 213,
    "pixelY": 1138,
    "mapXPct": 13.31,
    "mapYPct": 71.13,
    "order": 5
  },
  {
    "regionKey": "yenmebet",
    "regionName": "옌메베트",
    "outputOrder": 10,
    "title": "실람렌움",
    "aliases": [
      "실람렌움"
    ],
    "kind": "도시·거점",
    "icon": "stronghold",
    "gridX": 72.8,
    "gridY": 88,
    "pixelX": 1165,
    "pixelY": 1387,
    "mapXPct": 72.81,
    "mapYPct": 86.69,
    "order": 6
  },
  {
    "regionKey": "yenmebet",
    "regionName": "옌메베트",
    "outputOrder": 10,
    "title": "실람가",
    "aliases": [
      "실람가"
    ],
    "kind": "기록촌",
    "icon": "village",
    "gridX": 72.8,
    "gridY": 88,
    "pixelX": 1165,
    "pixelY": 1408,
    "mapXPct": 72.81,
    "mapYPct": 88,
    "order": 7
  },
  {
    "regionKey": "nimnaret",
    "regionName": "님나레트",
    "outputOrder": 11,
    "title": "님나할",
    "aliases": [
      "님나할"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 42.4,
    "gridY": 12,
    "pixelX": 678,
    "pixelY": 213,
    "mapXPct": 42.38,
    "mapYPct": 13.31,
    "order": 1
  },
  {
    "regionKey": "nimnaret",
    "regionName": "님나레트",
    "outputOrder": 11,
    "title": "얄베크움",
    "aliases": [
      "얄베크움"
    ],
    "kind": "도시·거점",
    "icon": "stronghold",
    "gridX": 57.6,
    "gridY": 42.4,
    "pixelX": 922,
    "pixelY": 678,
    "mapXPct": 57.63,
    "mapYPct": 42.38,
    "order": 2
  },
  {
    "regionKey": "nimnaret",
    "regionName": "님나레트",
    "outputOrder": 11,
    "title": "얄베크가",
    "aliases": [
      "얄베크가"
    ],
    "kind": "초소",
    "icon": "watchtower",
    "gridX": 27.2,
    "gridY": 57.6,
    "pixelX": 421,
    "pixelY": 690,
    "mapXPct": 26.31,
    "mapYPct": 43.13,
    "order": 3
  },
  {
    "regionKey": "nimnaret",
    "regionName": "님나레트",
    "outputOrder": 11,
    "title": "푸크베크움",
    "aliases": [
      "푸크베크움"
    ],
    "kind": "보관시설",
    "icon": "stronghold",
    "gridX": 88,
    "gridY": 57.6,
    "pixelX": 1408,
    "pixelY": 922,
    "mapXPct": 88,
    "mapYPct": 57.63,
    "order": 4
  },
  {
    "regionKey": "nimnaret",
    "regionName": "님나레트",
    "outputOrder": 11,
    "title": "푸크나움",
    "aliases": [
      "푸크나움"
    ],
    "kind": "도시·거점",
    "icon": "stronghold",
    "gridX": 88,
    "gridY": 57.6,
    "pixelX": 1387,
    "pixelY": 922,
    "mapXPct": 86.69,
    "mapYPct": 57.63,
    "order": 5
  },
  {
    "regionKey": "nimnaret",
    "regionName": "님나레트",
    "outputOrder": 11,
    "title": "엔켈할",
    "aliases": [
      "엔켈할"
    ],
    "kind": "도시·거점",
    "icon": "castle",
    "gridX": 12,
    "gridY": 72.8,
    "pixelX": 213,
    "pixelY": 1165,
    "mapXPct": 13.31,
    "mapYPct": 72.81,
    "order": 6
  },
  {
    "regionKey": "nimnaret",
    "regionName": "님나레트",
    "outputOrder": 11,
    "title": "헤드렌움",
    "aliases": [
      "헤드렌움"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 72.8,
    "gridY": 88,
    "pixelX": 1165,
    "pixelY": 1387,
    "mapXPct": 72.81,
    "mapYPct": 86.69,
    "order": 7
  },
  {
    "regionKey": "nimnaret",
    "regionName": "님나레트",
    "outputOrder": 11,
    "title": "헤드렌가",
    "aliases": [
      "헤드렌가"
    ],
    "kind": "대기촌",
    "icon": "village",
    "gridX": 72.8,
    "gridY": 88,
    "pixelX": 1165,
    "pixelY": 1408,
    "mapXPct": 72.81,
    "mapYPct": 88,
    "order": 8
  },
  {
    "regionKey": "silnimet",
    "regionName": "실니메트",
    "outputOrder": 12,
    "title": "실소르가",
    "aliases": [
      "실소르가"
    ],
    "kind": "숲문 마을",
    "icon": "temple",
    "gridX": 88,
    "gridY": 12,
    "pixelX": 1408,
    "pixelY": 192,
    "mapXPct": 88,
    "mapYPct": 12,
    "order": 1
  },
  {
    "regionKey": "silnimet",
    "regionName": "실니메트",
    "outputOrder": 12,
    "title": "실소르켈",
    "aliases": [
      "실소르켈"
    ],
    "kind": "도시·거점",
    "icon": "temple",
    "gridX": 88,
    "gridY": 12,
    "pixelX": 1387,
    "pixelY": 213,
    "mapXPct": 86.69,
    "mapYPct": 13.31,
    "order": 2
  },
  {
    "regionKey": "silnimet",
    "regionName": "실니메트",
    "outputOrder": 12,
    "title": "도르소르산",
    "aliases": [
      "도르소르산"
    ],
    "kind": "도시·거점",
    "icon": "temple",
    "gridX": 53.4545,
    "gridY": 21.5,
    "pixelX": 855,
    "pixelY": 344,
    "mapXPct": 53.44,
    "mapYPct": 21.5,
    "order": 3
  },
  {
    "regionKey": "silnimet",
    "regionName": "실니메트",
    "outputOrder": 12,
    "title": "실메르가",
    "aliases": [
      "실메르가"
    ],
    "kind": "채집촌",
    "icon": "village",
    "gridX": 32.7273,
    "gridY": 50,
    "pixelX": 524,
    "pixelY": 800,
    "mapXPct": 32.75,
    "mapYPct": 50,
    "order": 4
  },
  {
    "regionKey": "silnimet",
    "regionName": "실니메트",
    "outputOrder": 12,
    "title": "실메르미르",
    "aliases": [
      "실메르미르"
    ],
    "kind": "도시·거점",
    "icon": "market",
    "gridX": 32.7273,
    "gridY": 50,
    "pixelX": 524,
    "pixelY": 800,
    "mapXPct": 32.75,
    "mapYPct": 50,
    "order": 5
  },
  {
    "regionKey": "silnimet",
    "regionName": "실니메트",
    "outputOrder": 12,
    "title": "소르산가",
    "aliases": [
      "소르산가"
    ],
    "kind": "신전촌",
    "icon": "temple",
    "gridX": 53.4545,
    "gridY": 31,
    "pixelX": 1008,
    "pixelY": 802,
    "mapXPct": 63,
    "mapYPct": 50.13,
    "order": 6
  },
  {
    "regionKey": "silnimet",
    "regionName": "실니메트",
    "outputOrder": 12,
    "title": "메브메르켈",
    "aliases": [
      "메브메르켈"
    ],
    "kind": "도시·거점",
    "icon": "market",
    "gridX": 12,
    "gridY": 69,
    "pixelX": 213,
    "pixelY": 1104,
    "mapXPct": 13.31,
    "mapYPct": 69,
    "order": 7
  },
  {
    "regionKey": "silnimet",
    "regionName": "실니메트",
    "outputOrder": 12,
    "title": "메브메르가",
    "aliases": [
      "메브메르가"
    ],
    "kind": "야영지",
    "icon": "market",
    "gridX": 12,
    "gridY": 69,
    "pixelX": 192,
    "pixelY": 1104,
    "mapXPct": 12,
    "mapYPct": 69,
    "order": 8
  },
  {
    "regionKey": "silnimet",
    "regionName": "실니메트",
    "outputOrder": 12,
    "title": "벨마르미르",
    "aliases": [
      "벨마르미르"
    ],
    "kind": "도시·거점",
    "icon": "port",
    "gridX": 74.1818,
    "gridY": 88,
    "pixelX": 1187,
    "pixelY": 1387,
    "mapXPct": 74.19,
    "mapYPct": 86.69,
    "order": 9
  },
  {
    "regionKey": "ardolet",
    "regionName": "아르도레트",
    "outputOrder": 13,
    "title": "옌토르가",
    "aliases": [
      "옌토르가"
    ],
    "kind": "숙소촌",
    "icon": "temple",
    "gridX": 88,
    "gridY": 12,
    "pixelX": 1408,
    "pixelY": 192,
    "mapXPct": 88,
    "mapYPct": 12,
    "order": 1
  },
  {
    "regionKey": "ardolet",
    "regionName": "아르도레트",
    "outputOrder": 13,
    "title": "옌이엘토르",
    "aliases": [
      "옌이엘토르"
    ],
    "kind": "도시·거점",
    "icon": "temple",
    "gridX": 88,
    "gridY": 12,
    "pixelX": 1387,
    "pixelY": 213,
    "mapXPct": 86.69,
    "mapYPct": 13.31,
    "order": 2
  },
  {
    "regionKey": "ardolet",
    "regionName": "아르도레트",
    "outputOrder": 13,
    "title": "도르소르할",
    "aliases": [
      "도르소르할"
    ],
    "kind": "도시·거점",
    "icon": "temple",
    "gridX": 55.4286,
    "gridY": 37.3333,
    "pixelX": 887,
    "pixelY": 597,
    "mapXPct": 55.44,
    "mapYPct": 37.31,
    "order": 3
  },
  {
    "regionKey": "ardolet",
    "regionName": "아르도레트",
    "outputOrder": 13,
    "title": "아르소르산",
    "aliases": [
      "아르소르산"
    ],
    "kind": "도시·거점",
    "icon": "temple",
    "gridX": 77.1429,
    "gridY": 62.6667,
    "pixelX": 1234,
    "pixelY": 1003,
    "mapXPct": 77.13,
    "mapYPct": 62.69,
    "order": 4
  },
  {
    "regionKey": "ardolet",
    "regionName": "아르도레트",
    "outputOrder": 13,
    "title": "도르켈가",
    "aliases": [
      "도르켈가"
    ],
    "kind": "산길 마을",
    "icon": "watchtower",
    "gridX": 33.7143,
    "gridY": 71.1111,
    "pixelX": 539,
    "pixelY": 1138,
    "mapXPct": 33.69,
    "mapYPct": 71.13,
    "order": 5
  },
  {
    "regionKey": "ardolet",
    "regionName": "아르도레트",
    "outputOrder": 13,
    "title": "도르켈바르",
    "aliases": [
      "도르켈바르"
    ],
    "kind": "도시·거점",
    "icon": "castle",
    "gridX": 33.7143,
    "gridY": 71.1111,
    "pixelX": 539,
    "pixelY": 1138,
    "mapXPct": 33.69,
    "mapYPct": 71.13,
    "order": 6
  },
  {
    "regionKey": "ardolet",
    "regionName": "아르도레트",
    "outputOrder": 13,
    "title": "소르할",
    "aliases": [
      "소르할"
    ],
    "kind": "도시·거점",
    "icon": "temple",
    "gridX": 12,
    "gridY": 88,
    "pixelX": 192,
    "pixelY": 1408,
    "mapXPct": 12,
    "mapYPct": 88,
    "order": 7
  },
  {
    "regionKey": "ardolet",
    "regionName": "아르도레트",
    "outputOrder": 13,
    "title": "소르할가",
    "aliases": [
      "소르할가"
    ],
    "kind": "숙소촌",
    "icon": "temple",
    "gridX": 12,
    "gridY": 88,
    "pixelX": 192,
    "pixelY": 1408,
    "mapXPct": 12,
    "mapYPct": 88,
    "order": 8
  },
  {
    "regionKey": "garmebet",
    "regionName": "가르메베트",
    "outputOrder": 14,
    "title": "벨메브가",
    "aliases": [
      "벨메브가"
    ],
    "kind": "야영지",
    "icon": "village",
    "gridX": 25.8182,
    "gridY": 12,
    "pixelX": 413,
    "pixelY": 192,
    "mapXPct": 25.81,
    "mapYPct": 12,
    "order": 1
  },
  {
    "regionKey": "garmebet",
    "regionName": "가르메베트",
    "outputOrder": 14,
    "title": "벨람바르",
    "aliases": [
      "벨람바르"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 25.8182,
    "gridY": 12,
    "pixelX": 413,
    "pixelY": 213,
    "mapXPct": 25.81,
    "mapYPct": 13.31,
    "order": 2
  },
  {
    "regionKey": "garmebet",
    "regionName": "가르메베트",
    "outputOrder": 14,
    "title": "워크렌가",
    "aliases": [
      "워크렌가"
    ],
    "kind": "숙소촌",
    "icon": "market",
    "gridX": 88,
    "gridY": 22.8571,
    "pixelX": 1408,
    "pixelY": 366,
    "mapXPct": 88,
    "mapYPct": 22.88,
    "order": 3
  },
  {
    "regionKey": "garmebet",
    "regionName": "가르메베트",
    "outputOrder": 14,
    "title": "워크렌움",
    "aliases": [
      "워크렌움"
    ],
    "kind": "도시·거점",
    "icon": "stronghold",
    "gridX": 88,
    "gridY": 22.8571,
    "pixelX": 1387,
    "pixelY": 366,
    "mapXPct": 86.69,
    "mapYPct": 22.88,
    "order": 4
  },
  {
    "regionKey": "garmebet",
    "regionName": "가르메베트",
    "outputOrder": 14,
    "title": "틱람가",
    "aliases": [
      "틱람가"
    ],
    "kind": "야영지",
    "icon": "village",
    "gridX": 46.5455,
    "gridY": 44.5714,
    "pixelX": 745,
    "pixelY": 713,
    "mapXPct": 46.56,
    "mapYPct": 44.56,
    "order": 5
  },
  {
    "regionKey": "garmebet",
    "regionName": "가르메베트",
    "outputOrder": 14,
    "title": "틱메브할",
    "aliases": [
      "틱메브할"
    ],
    "kind": "도시·거점",
    "icon": "stronghold",
    "gridX": 46.5455,
    "gridY": 44.5714,
    "pixelX": 745,
    "pixelY": 713,
    "mapXPct": 46.56,
    "mapYPct": 44.56,
    "order": 6
  },
  {
    "regionKey": "garmebet",
    "regionName": "가르메베트",
    "outputOrder": 14,
    "title": "메브바르",
    "aliases": [
      "메브바르"
    ],
    "kind": "도시·거점",
    "icon": "market",
    "gridX": 67.2727,
    "gridY": 66.2857,
    "pixelX": 1076,
    "pixelY": 1061,
    "mapXPct": 67.25,
    "mapYPct": 66.31,
    "order": 7
  },
  {
    "regionKey": "garmebet",
    "regionName": "가르메베트",
    "outputOrder": 14,
    "title": "메브테크가",
    "aliases": [
      "메브테크가"
    ],
    "kind": "작업촌",
    "icon": "village",
    "gridX": 67.2727,
    "gridY": 77.1429,
    "pixelX": 742,
    "pixelY": 1373,
    "mapXPct": 46.38,
    "mapYPct": 85.81,
    "order": 8
  },
  {
    "regionKey": "garmebet",
    "regionName": "가르메베트",
    "outputOrder": 14,
    "title": "벨베크엘",
    "aliases": [
      "벨베크엘"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 12,
    "gridY": 88,
    "pixelX": 213,
    "pixelY": 1387,
    "mapXPct": 13.31,
    "mapYPct": 86.69,
    "order": 9
  },
  {
    "regionKey": "silhalet",
    "regionName": "실할레트",
    "outputOrder": 15,
    "title": "라드실할",
    "aliases": [
      "라드실할"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 88,
    "gridY": 12,
    "pixelX": 1387,
    "pixelY": 213,
    "mapXPct": 86.69,
    "mapYPct": 13.31,
    "order": 1
  },
  {
    "regionKey": "silhalet",
    "regionName": "실할레트",
    "outputOrder": 15,
    "title": "실베크엘",
    "aliases": [
      "실베크엘"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 27.2,
    "gridY": 37.3333,
    "pixelX": 435,
    "pixelY": 597,
    "mapXPct": 27.19,
    "mapYPct": 37.31,
    "order": 2
  },
  {
    "regionKey": "silhalet",
    "regionName": "실할레트",
    "outputOrder": 15,
    "title": "라드실가",
    "aliases": [
      "라드실가"
    ],
    "kind": "작업촌",
    "icon": "village",
    "gridX": 88,
    "gridY": 24.6667,
    "pixelX": 1386,
    "pixelY": 666,
    "mapXPct": 86.63,
    "mapYPct": 41.63,
    "order": 3
  },
  {
    "regionKey": "silhalet",
    "regionName": "실할레트",
    "outputOrder": 15,
    "title": "실소르산",
    "aliases": [
      "실소르산"
    ],
    "kind": "도시·거점",
    "icon": "temple",
    "gridX": 57.6,
    "gridY": 50,
    "pixelX": 922,
    "pixelY": 800,
    "mapXPct": 57.63,
    "mapYPct": 50,
    "order": 4
  },
  {
    "regionKey": "silhalet",
    "regionName": "실할레트",
    "outputOrder": 15,
    "title": "실문가",
    "aliases": [
      "실문가"
    ],
    "kind": "숲문 마을",
    "icon": "temple",
    "gridX": 42.4,
    "gridY": 50,
    "pixelX": 678,
    "pixelY": 800,
    "mapXPct": 42.38,
    "mapYPct": 50,
    "order": 5
  },
  {
    "regionKey": "silhalet",
    "regionName": "실할레트",
    "outputOrder": 15,
    "title": "실다트바르",
    "aliases": [
      "실다트바르"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 12,
    "gridY": 75.3333,
    "pixelX": 213,
    "pixelY": 1205,
    "mapXPct": 13.31,
    "mapYPct": 75.31,
    "order": 6
  },
  {
    "regionKey": "silhalet",
    "regionName": "실할레트",
    "outputOrder": 15,
    "title": "실다트가",
    "aliases": [
      "실다트가"
    ],
    "kind": "채집촌",
    "icon": "village",
    "gridX": 12,
    "gridY": 75.3333,
    "pixelX": 192,
    "pixelY": 1205,
    "mapXPct": 12,
    "mapYPct": 75.31,
    "order": 7
  },
  {
    "regionKey": "silhalet",
    "regionName": "실할레트",
    "outputOrder": 15,
    "title": "실테크엘",
    "aliases": [
      "실테크엘"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 72.8,
    "gridY": 88,
    "pixelX": 1165,
    "pixelY": 1387,
    "mapXPct": 72.81,
    "mapYPct": 86.69,
    "order": 8
  },
  {
    "regionKey": "silhalet",
    "regionName": "실할레트",
    "outputOrder": 15,
    "title": "실테크가",
    "aliases": [
      "실테크가"
    ],
    "kind": "숙소촌",
    "icon": "village",
    "gridX": 72.8,
    "gridY": 88,
    "pixelX": 1165,
    "pixelY": 1408,
    "mapXPct": 72.81,
    "mapYPct": 88,
    "order": 9
  },
  {
    "regionKey": "merhalet",
    "regionName": "메르할레트",
    "outputOrder": 16,
    "title": "헤드메르가",
    "aliases": [
      "헤드메르가"
    ],
    "kind": "대기촌",
    "icon": "village",
    "gridX": 72.8,
    "gridY": 12,
    "pixelX": 1165,
    "pixelY": 192,
    "mapXPct": 72.81,
    "mapYPct": 12,
    "order": 1
  },
  {
    "regionKey": "merhalet",
    "regionName": "메르할레트",
    "outputOrder": 16,
    "title": "헤드켈바르",
    "aliases": [
      "헤드켈바르"
    ],
    "kind": "도시·거점",
    "icon": "castle",
    "gridX": 72.8,
    "gridY": 12,
    "pixelX": 1165,
    "pixelY": 213,
    "mapXPct": 72.81,
    "mapYPct": 13.31,
    "order": 2
  },
  {
    "regionKey": "merhalet",
    "regionName": "메르할레트",
    "outputOrder": 16,
    "title": "메르바르",
    "aliases": [
      "메르바르"
    ],
    "kind": "도시·거점",
    "icon": "market",
    "gridX": 12,
    "gridY": 24.6667,
    "pixelX": 213,
    "pixelY": 395,
    "mapXPct": 13.31,
    "mapYPct": 24.69,
    "order": 3
  },
  {
    "regionKey": "merhalet",
    "regionName": "메르할레트",
    "outputOrder": 16,
    "title": "메르벨마르",
    "aliases": [
      "메르벨마르"
    ],
    "kind": "도시·거점",
    "icon": "port",
    "gridX": 42.4,
    "gridY": 50,
    "pixelX": 678,
    "pixelY": 800,
    "mapXPct": 42.38,
    "mapYPct": 50,
    "order": 4
  },
  {
    "regionKey": "merhalet",
    "regionName": "메르할레트",
    "outputOrder": 16,
    "title": "푸크메르가",
    "aliases": [
      "푸크메르가"
    ],
    "kind": "창고촌",
    "icon": "stronghold",
    "gridX": 88,
    "gridY": 62.6667,
    "pixelX": 1408,
    "pixelY": 1003,
    "mapXPct": 88,
    "mapYPct": 62.69,
    "order": 5
  },
  {
    "regionKey": "merhalet",
    "regionName": "메르할레트",
    "outputOrder": 16,
    "title": "푸크테쿰",
    "aliases": [
      "푸크테쿰"
    ],
    "kind": "도시·거점",
    "icon": "port",
    "gridX": 88,
    "gridY": 62.6667,
    "pixelX": 1387,
    "pixelY": 1003,
    "mapXPct": 86.69,
    "mapYPct": 62.69,
    "order": 6
  },
  {
    "regionKey": "merhalet",
    "regionName": "메르할레트",
    "outputOrder": 16,
    "title": "메르나브가",
    "aliases": [
      "메르나브가"
    ],
    "kind": "항구가",
    "icon": "port",
    "gridX": 42.4,
    "gridY": 62.6667,
    "pixelX": 855,
    "pixelY": 1196,
    "mapXPct": 53.44,
    "mapYPct": 74.75,
    "order": 7
  },
  {
    "regionKey": "merhalet",
    "regionName": "메르할레트",
    "outputOrder": 16,
    "title": "메르님바르",
    "aliases": [
      "메르님바르"
    ],
    "kind": "도시·거점",
    "icon": "market",
    "gridX": 27.2,
    "gridY": 88,
    "pixelX": 435,
    "pixelY": 1387,
    "mapXPct": 27.19,
    "mapYPct": 86.69,
    "order": 8
  },
  {
    "regionKey": "nimsolet",
    "regionName": "님소레트",
    "outputOrder": 17,
    "title": "님렘할",
    "aliases": [
      "님렘할"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 12,
    "gridY": 12,
    "pixelX": 213,
    "pixelY": 213,
    "mapXPct": 13.31,
    "mapYPct": 13.31,
    "order": 1
  },
  {
    "regionKey": "nimsolet",
    "regionName": "님소레트",
    "outputOrder": 17,
    "title": "렌메르미르",
    "aliases": [
      "렌메르미르"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 88,
    "gridY": 27.2,
    "pixelX": 1387,
    "pixelY": 435,
    "mapXPct": 86.69,
    "mapYPct": 27.19,
    "order": 2
  },
  {
    "regionKey": "nimsolet",
    "regionName": "님소레트",
    "outputOrder": 17,
    "title": "님렌가",
    "aliases": [
      "님렌가"
    ],
    "kind": "숙소가",
    "icon": "village",
    "gridX": 42.4,
    "gridY": 42.4,
    "pixelX": 678,
    "pixelY": 678,
    "mapXPct": 42.38,
    "mapYPct": 42.38,
    "order": 3
  },
  {
    "regionKey": "nimsolet",
    "regionName": "님소레트",
    "outputOrder": 17,
    "title": "님할",
    "aliases": [
      "님할"
    ],
    "kind": "도시·거점",
    "icon": "temple",
    "gridX": 42.4,
    "gridY": 42.4,
    "pixelX": 678,
    "pixelY": 678,
    "mapXPct": 42.38,
    "mapYPct": 42.38,
    "order": 4
  },
  {
    "regionKey": "nimsolet",
    "regionName": "님소레트",
    "outputOrder": 17,
    "title": "소르다트가",
    "aliases": [
      "소르다트가"
    ],
    "kind": "신전촌",
    "icon": "temple",
    "gridX": 72.8,
    "gridY": 72.8,
    "pixelX": 1165,
    "pixelY": 1165,
    "mapXPct": 72.81,
    "mapYPct": 72.81,
    "order": 5
  },
  {
    "regionKey": "nimsolet",
    "regionName": "님소레트",
    "outputOrder": 17,
    "title": "소르다트움",
    "aliases": [
      "소르다트움"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 72.8,
    "gridY": 72.8,
    "pixelX": 1165,
    "pixelY": 1165,
    "mapXPct": 72.81,
    "mapYPct": 72.81,
    "order": 6
  },
  {
    "regionKey": "nimsolet",
    "regionName": "님소레트",
    "outputOrder": 17,
    "title": "렌테쿰",
    "aliases": [
      "렌테쿰"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 27.2,
    "gridY": 88,
    "pixelX": 435,
    "pixelY": 1387,
    "mapXPct": 27.19,
    "mapYPct": 86.69,
    "order": 7
  },
  {
    "regionKey": "nimsolet",
    "regionName": "님소레트",
    "outputOrder": 17,
    "title": "렌테크가",
    "aliases": [
      "렌테크가"
    ],
    "kind": "작업가",
    "icon": "village",
    "gridX": 27.2,
    "gridY": 88,
    "pixelX": 435,
    "pixelY": 1408,
    "mapXPct": 27.19,
    "mapYPct": 88,
    "order": 8
  },
  {
    "regionKey": "sylvania",
    "regionName": "실바니아",
    "outputOrder": 18,
    "title": "워크실가",
    "aliases": [
      "워크실가"
    ],
    "kind": "마을",
    "icon": "village",
    "gridX": 12,
    "gridY": 12,
    "pixelX": 192,
    "pixelY": 192,
    "mapXPct": 12,
    "mapYPct": 12,
    "order": 1
  },
  {
    "regionKey": "sylvania",
    "regionName": "실바니아",
    "outputOrder": 18,
    "title": "워크켈할",
    "aliases": [
      "워크켈할"
    ],
    "kind": "도시·거점",
    "icon": "stronghold",
    "gridX": 12,
    "gridY": 12,
    "pixelX": 213,
    "pixelY": 213,
    "mapXPct": 13.31,
    "mapYPct": 13.31,
    "order": 2
  },
  {
    "regionKey": "sylvania",
    "regionName": "실바니아",
    "outputOrder": 18,
    "title": "실렌산",
    "aliases": [
      "실렌산"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 44.5714,
    "gridY": 33.7143,
    "pixelX": 713,
    "pixelY": 539,
    "mapXPct": 44.56,
    "mapYPct": 33.69,
    "order": 3
  },
  {
    "regionKey": "sylvania",
    "regionName": "실바니아",
    "outputOrder": 18,
    "title": "실킨가",
    "aliases": [
      "실킨가"
    ],
    "kind": "마을",
    "icon": "village",
    "gridX": 44.5714,
    "gridY": 33.7143,
    "pixelX": 713,
    "pixelY": 539,
    "mapXPct": 44.56,
    "mapYPct": 33.69,
    "order": 4
  },
  {
    "regionKey": "sylvania",
    "regionName": "실바니아",
    "outputOrder": 18,
    "title": "렌얄움",
    "aliases": [
      "렌얄움"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 66.2857,
    "gridY": 66.2857,
    "pixelX": 1061,
    "pixelY": 1061,
    "mapXPct": 66.31,
    "mapYPct": 66.31,
    "order": 5
  },
  {
    "regionKey": "sylvania",
    "regionName": "실바니아",
    "outputOrder": 18,
    "title": "움켈산",
    "aliases": [
      "움켈산"
    ],
    "kind": "도시·거점",
    "icon": "stronghold",
    "gridX": 88,
    "gridY": 88,
    "pixelX": 1387,
    "pixelY": 1387,
    "mapXPct": 86.69,
    "mapYPct": 86.69,
    "order": 6
  },
  {
    "regionKey": "sylvania",
    "regionName": "실바니아",
    "outputOrder": 18,
    "title": "움켈가",
    "aliases": [
      "움켈가"
    ],
    "kind": "숙소촌",
    "icon": "village",
    "gridX": 88,
    "gridY": 88,
    "pixelX": 1408,
    "pixelY": 1408,
    "mapXPct": 88,
    "mapYPct": 88,
    "order": 7
  },
  {
    "regionKey": "dragonspire",
    "regionName": "드래곤스파이어",
    "outputOrder": 19,
    "title": "나르베크토르",
    "aliases": [
      "나르베크토르"
    ],
    "kind": "도시·거점",
    "icon": "temple",
    "gridX": 66.2857,
    "gridY": 12,
    "pixelX": 1061,
    "pixelY": 213,
    "mapXPct": 66.31,
    "mapYPct": 13.31,
    "order": 1
  },
  {
    "regionKey": "dragonspire",
    "regionName": "드래곤스파이어",
    "outputOrder": 19,
    "title": "나르페르가",
    "aliases": [
      "나르페르가"
    ],
    "kind": "작업촌",
    "icon": "village",
    "gridX": 55.4286,
    "gridY": 31,
    "pixelX": 887,
    "pixelY": 496,
    "mapXPct": 55.44,
    "mapYPct": 31,
    "order": 2
  },
  {
    "regionKey": "dragonspire",
    "regionName": "드래곤스파이어",
    "outputOrder": 19,
    "title": "나르마르켈",
    "aliases": [
      "나르마르켈"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 44.5714,
    "gridY": 40.5,
    "pixelX": 713,
    "pixelY": 648,
    "mapXPct": 44.56,
    "mapYPct": 40.5,
    "order": 3
  },
  {
    "regionKey": "dragonspire",
    "regionName": "드래곤스파이어",
    "outputOrder": 19,
    "title": "나르마르렌움",
    "aliases": [
      "나르마르렌움"
    ],
    "kind": "도시·거점",
    "icon": "port",
    "gridX": 12,
    "gridY": 69,
    "pixelX": 213,
    "pixelY": 1104,
    "mapXPct": 13.31,
    "mapYPct": 69,
    "order": 4
  },
  {
    "regionKey": "dragonspire",
    "regionName": "드래곤스파이어",
    "outputOrder": 19,
    "title": "나르모스가",
    "aliases": [
      "나르모스가"
    ],
    "kind": "피난촌",
    "icon": "stronghold",
    "gridX": 44.5714,
    "gridY": 50,
    "pixelX": 866,
    "pixelY": 1106,
    "mapXPct": 54.13,
    "mapYPct": 69.13,
    "order": 5
  },
  {
    "regionKey": "dragonspire",
    "regionName": "드래곤스파이어",
    "outputOrder": 19,
    "title": "마르모스할",
    "aliases": [
      "마르모스할"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 88,
    "gridY": 88,
    "pixelX": 1387,
    "pixelY": 1387,
    "mapXPct": 86.69,
    "mapYPct": 86.69,
    "order": 6
  },
  {
    "regionKey": "dragonspire",
    "regionName": "드래곤스파이어",
    "outputOrder": 19,
    "title": "마르나르가",
    "aliases": [
      "마르나르가"
    ],
    "kind": "선착장",
    "icon": "port",
    "gridX": 88,
    "gridY": 88,
    "pixelX": 1408,
    "pixelY": 1408,
    "mapXPct": 88,
    "mapYPct": 88,
    "order": 7
  },
  {
    "regionKey": "fenrir-s-eye",
    "regionName": "펜리르의 눈",
    "outputOrder": 20,
    "title": "둔토르가",
    "aliases": [
      "둔토르가"
    ],
    "kind": "등대촌",
    "icon": "watchtower",
    "gridX": 33.7143,
    "gridY": 12,
    "pixelX": 539,
    "pixelY": 192,
    "mapXPct": 33.69,
    "mapYPct": 12,
    "order": 1
  },
  {
    "regionKey": "fenrir-s-eye",
    "regionName": "펜리르의 눈",
    "outputOrder": 20,
    "title": "둔아르토르",
    "aliases": [
      "둔아르토르"
    ],
    "kind": "도시·거점",
    "icon": "temple",
    "gridX": 33.7143,
    "gridY": 12,
    "pixelX": 539,
    "pixelY": 213,
    "mapXPct": 33.69,
    "mapYPct": 13.31,
    "order": 2
  },
  {
    "regionKey": "fenrir-s-eye",
    "regionName": "펜리르의 눈",
    "outputOrder": 20,
    "title": "둔나브렌움",
    "aliases": [
      "둔나브렌움"
    ],
    "kind": "도시·거점",
    "icon": "stronghold",
    "gridX": 66.2857,
    "gridY": 37.3333,
    "pixelX": 1061,
    "pixelY": 597,
    "mapXPct": 66.31,
    "mapYPct": 37.31,
    "order": 3
  },
  {
    "regionKey": "fenrir-s-eye",
    "regionName": "펜리르의 눈",
    "outputOrder": 20,
    "title": "둔푸크가",
    "aliases": [
      "둔푸크가"
    ],
    "kind": "보관시설",
    "icon": "stronghold",
    "gridX": 66.2857,
    "gridY": 37.3333,
    "pixelX": 1061,
    "pixelY": 597,
    "mapXPct": 66.31,
    "mapYPct": 37.31,
    "order": 4
  },
  {
    "regionKey": "fenrir-s-eye",
    "regionName": "펜리르의 눈",
    "outputOrder": 20,
    "title": "움마르소르",
    "aliases": [
      "움마르소르"
    ],
    "kind": "도시·거점",
    "icon": "town",
    "gridX": 12,
    "gridY": 62.6667,
    "pixelX": 213,
    "pixelY": 1003,
    "mapXPct": 13.31,
    "mapYPct": 62.69,
    "order": 5
  },
  {
    "regionKey": "fenrir-s-eye",
    "regionName": "펜리르의 눈",
    "outputOrder": 20,
    "title": "벱나브할",
    "aliases": [
      "벱나브할"
    ],
    "kind": "도시·거점",
    "icon": "port",
    "gridX": 88,
    "gridY": 88,
    "pixelX": 1387,
    "pixelY": 1387,
    "mapXPct": 86.69,
    "mapYPct": 86.69,
    "order": 6
  },
  {
    "regionKey": "fenrir-s-eye",
    "regionName": "펜리르의 눈",
    "outputOrder": 20,
    "title": "벱나브가",
    "aliases": [
      "벱나브가"
    ],
    "kind": "구조 거점",
    "icon": "watchtower",
    "gridX": 88,
    "gridY": 88,
    "pixelX": 1408,
    "pixelY": 1408,
    "mapXPct": 88,
    "mapYPct": 88,
    "order": 7
  }
];
