// Generated by tools/build_vireth_region_map_router_assets.mjs. Do not edit by hand.
export const GENERATED_REGION_MAPS = [
  {
    "key": "leonia",
    "aliases": [
      "leonia",
      "레오니아"
    ],
    "title": "레오니아",
    "imageUrl": "/map-assets/region-maps/ck5083-region-map-leonia-v56-1024.webp",
    "sourceFile": "01-leonia-v56-generated-source.png",
    "reviewFile": "01-leonia-v59-name-labeled-1600.png"
  },
  {
    "key": "norghard",
    "aliases": [
      "norghard",
      "노르가르드"
    ],
    "title": "노르가르드",
    "imageUrl": "/map-assets/region-maps/ck5083-region-map-norghard-v56-1024.webp",
    "sourceFile": "02-norghard-v56-generated-source.png",
    "reviewFile": "02-norghard-v59-name-labeled-1600.png"
  },
  {
    "key": "tiris",
    "aliases": [
      "tiris",
      "티리스"
    ],
    "title": "티리스",
    "imageUrl": "/map-assets/region-maps/ck5083-region-map-tiris-v56-1024.webp",
    "sourceFile": "03-tiris-v56-generated-source.png",
    "reviewFile": "03-tiris-v59-name-labeled-1600.png"
  },
  {
    "key": "linrenet",
    "aliases": [
      "linrenet",
      "린레네트"
    ],
    "title": "린레네트",
    "imageUrl": "/map-assets/region-maps/ck5083-region-map-linrenet-v56-1024.webp",
    "sourceFile": "04-linrenet-v56-generated-source.png",
    "reviewFile": "04-linrenet-v59-name-labeled-1600.png"
  },
  {
    "key": "bekdoret",
    "aliases": [
      "bekdoret",
      "벡도레트"
    ],
    "title": "벡도레트",
    "imageUrl": "/map-assets/region-maps/ck5083-region-map-bekdoret-v56-1024.webp",
    "sourceFile": "05-bekdoret-v56-generated-source.png",
    "reviewFile": "05-bekdoret-v59-name-labeled-1600.png"
  },
  {
    "key": "senhalet",
    "aliases": [
      "senhalet",
      "센할레트"
    ],
    "title": "센할레트",
    "imageUrl": "/map-assets/region-maps/ck5083-region-map-senhalet-v56-1024.webp",
    "sourceFile": "06-senhalet-v56-generated-source.png",
    "reviewFile": "06-senhalet-v59-name-labeled-1600.png"
  },
  {
    "key": "hesferet",
    "aliases": [
      "hesferet",
      "헤스페레트"
    ],
    "title": "헤스페레트",
    "imageUrl": "/map-assets/region-maps/ck5083-region-map-hesferet-v56-1024.webp",
    "sourceFile": "07-hesferet-v56-generated-source.png",
    "reviewFile": "07-hesferet-v59-name-labeled-1600.png"
  },
  {
    "key": "kelnabet",
    "aliases": [
      "kelnabet",
      "켈나베트"
    ],
    "title": "켈나베트",
    "imageUrl": "/map-assets/region-maps/ck5083-region-map-kelnabet-v56-1024.webp",
    "sourceFile": "08-kelnabet-v56-generated-source.png",
    "reviewFile": "08-kelnabet-v59-name-labeled-1600.png"
  },
  {
    "key": "hesbeket",
    "aliases": [
      "hesbeket",
      "헤스베케트"
    ],
    "title": "헤스베케트",
    "imageUrl": "/map-assets/region-maps/ck5083-region-map-hesbeket-v56-1024.webp",
    "sourceFile": "09-hesbeket-v56-generated-source.png",
    "reviewFile": "09-hesbeket-v59-name-labeled-1600.png"
  },
  {
    "key": "yenmebet",
    "aliases": [
      "yenmebet",
      "옌메베트"
    ],
    "title": "옌메베트",
    "imageUrl": "/map-assets/region-maps/ck5083-region-map-yenmebet-v56-1024.webp",
    "sourceFile": "10-yenmebet-v56-generated-source.png",
    "reviewFile": "10-yenmebet-v59-name-labeled-1600.png"
  },
  {
    "key": "nimnaret",
    "aliases": [
      "nimnaret",
      "님나레트"
    ],
    "title": "님나레트",
    "imageUrl": "/map-assets/region-maps/ck5083-region-map-nimnaret-v56-1024.webp",
    "sourceFile": "11-nimnaret-v56-generated-source.png",
    "reviewFile": "11-nimnaret-v59-name-labeled-1600.png"
  },
  {
    "key": "silnimet",
    "aliases": [
      "silnimet",
      "실니메트"
    ],
    "title": "실니메트",
    "imageUrl": "/map-assets/region-maps/ck5083-region-map-silnimet-v56-1024.webp",
    "sourceFile": "12-silnimet-v56-generated-source.png",
    "reviewFile": "12-silnimet-v59-name-labeled-1600.png"
  },
  {
    "key": "ardolet",
    "aliases": [
      "ardolet",
      "아르도레트"
    ],
    "title": "아르도레트",
    "imageUrl": "/map-assets/region-maps/ck5083-region-map-ardolet-v56-1024.webp",
    "sourceFile": "13-ardolet-v56-generated-source.png",
    "reviewFile": "13-ardolet-v59-name-labeled-1600.png"
  },
  {
    "key": "garmebet",
    "aliases": [
      "garmebet",
      "가르메베트"
    ],
    "title": "가르메베트",
    "imageUrl": "/map-assets/region-maps/ck5083-region-map-garmebet-v56-1024.webp",
    "sourceFile": "14-garmebet-v56-generated-source.png",
    "reviewFile": "14-garmebet-v59-name-labeled-1600.png"
  },
  {
    "key": "silhalet",
    "aliases": [
      "silhalet",
      "실할레트"
    ],
    "title": "실할레트",
    "imageUrl": "/map-assets/region-maps/ck5083-region-map-silhalet-v56-1024.webp",
    "sourceFile": "15-silhalet-v56-generated-source.png",
    "reviewFile": "15-silhalet-v59-name-labeled-1600.png"
  },
  {
    "key": "merhalet",
    "aliases": [
      "merhalet",
      "메르할레트"
    ],
    "title": "메르할레트",
    "imageUrl": "/map-assets/region-maps/ck5083-region-map-merhalet-v56-1024.webp",
    "sourceFile": "16-merhalet-v56-generated-source.png",
    "reviewFile": "16-merhalet-v59-name-labeled-1600.png"
  },
  {
    "key": "nimsolet",
    "aliases": [
      "nimsolet",
      "님소레트"
    ],
    "title": "님소레트",
    "imageUrl": "/map-assets/region-maps/ck5083-region-map-nimsolet-v56-1024.webp",
    "sourceFile": "17-nimsolet-v56-generated-source.png",
    "reviewFile": "17-nimsolet-v59-name-labeled-1600.png"
  },
  {
    "key": "sylvania",
    "aliases": [
      "sylvania",
      "실바니아"
    ],
    "title": "실바니아",
    "imageUrl": "/map-assets/region-maps/ck5083-region-map-sylvania-v56-1024.webp",
    "sourceFile": "18-sylvania-v56-generated-source.png",
    "reviewFile": "18-sylvania-v59-name-labeled-1600.png"
  },
  {
    "key": "dragonspire",
    "aliases": [
      "dragonspire",
      "드래곤스파이어"
    ],
    "title": "드래곤스파이어",
    "imageUrl": "/map-assets/region-maps/ck5083-region-map-dragonspire-v56-1024.webp",
    "sourceFile": "19-dragonspire-v56-generated-source.png",
    "reviewFile": "19-dragonspire-v59-name-labeled-1600.png"
  },
  {
    "key": "fenrir-s-eye",
    "aliases": [
      "fenrir-s-eye",
      "펜리르의 눈",
      "fenrir-eye",
      "펜리르"
    ],
    "title": "펜리르의 눈",
    "imageUrl": "/map-assets/region-maps/ck5083-region-map-fenrir-s-eye-v56-1024.webp",
    "sourceFile": "20-fenrir-s-eye-v56-generated-source.png",
    "reviewFile": "20-fenrir-s-eye-v59-name-labeled-1600.png"
  }
];
