import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";

const sourceDir =
  "D:/OneDrive/444_비레스/00_최신본/02_지도/09_지역별_정사각_재렌더_v56/_generated_sources";
const reviewDir =
  "D:/OneDrive/444_비레스/00_최신본/02_지도/12_장소명라벨_아이콘설치지도_v59/01_지역별_세부지도";
const assetRoot =
  "D:/OneDrive/Documents/GitHub/VIRETH/VIRETH/etc/arcadia5083-region-map-router";
const assetDir = join(assetRoot, "region-maps");
const registryPath = "workers/vireth-svg/src/generated-region-maps.ts";
const assetBase =
  "https://raw.githubusercontent.com/musueman/VIRETH/main/etc/arcadia5083-region-map-router/region-maps";

const regions = [
  ["01", "leonia", "레오니아", ["leonia", "레오니아"]],
  ["02", "norghard", "노르가르드", ["norghard", "노르가르드"]],
  ["03", "tiris", "티리스", ["tiris", "티리스"]],
  ["04", "linrenet", "린레네트", ["linrenet", "린레네트"]],
  ["05", "bekdoret", "벡도레트", ["bekdoret", "벡도레트"]],
  ["06", "senhalet", "센할레트", ["senhalet", "센할레트"]],
  ["07", "hesferet", "헤스페레트", ["hesferet", "헤스페레트"]],
  ["08", "kelnabet", "켈나베트", ["kelnabet", "켈나베트"]],
  ["09", "hesbeket", "헤스베케트", ["hesbeket", "헤스베케트"]],
  ["10", "yenmebet", "옌메베트", ["yenmebet", "옌메베트"]],
  ["11", "nimnaret", "님나레트", ["nimnaret", "님나레트"]],
  ["12", "silnimet", "실니메트", ["silnimet", "실니메트"]],
  ["13", "ardolet", "아르도레트", ["ardolet", "아르도레트"]],
  ["14", "garmebet", "가르메베트", ["garmebet", "가르메베트"]],
  ["15", "silhalet", "실할레트", ["silhalet", "실할레트"]],
  ["16", "merhalet", "메르할레트", ["merhalet", "메르할레트"]],
  ["17", "nimsolet", "님소레트", ["nimsolet", "님소레트"]],
  ["18", "sylvania", "실바니아", ["sylvania", "실바니아"]],
  ["19", "dragonspire", "드래곤스파이어", ["dragonspire", "드래곤스파이어"]],
  ["20", "fenrir-s-eye", "펜리르의 눈", ["fenrir-s-eye", "fenrir-eye", "펜리르의 눈", "펜리르"]]
];

mkdirSync(assetDir, { recursive: true });

const entries = regions.map(([index, key, title, aliases]) => {
  const sourceFile = `${index}-${key}-v56-generated-source.png`;
  const reviewFile = `${index}-${key}-v59-name-labeled-1600.png`;
  const outputFile = `ck5083-region-map-${key}-v56-1024.webp`;
  const sourcePath = join(sourceDir, sourceFile);
  const reviewPath = join(reviewDir, reviewFile);
  const outputPath = join(assetDir, outputFile);

  for (const path of [sourcePath, reviewPath]) {
    const probe = spawnSync("magick", ["identify", path], { encoding: "utf8" });
    if (probe.status !== 0) {
      throw new Error(`Missing or unreadable map source: ${path}\n${probe.stderr}`);
    }
  }

  const result = spawnSync(
    "magick",
    [sourcePath, "-resize", "1024x1024", "-strip", "-quality", "84", outputPath],
    { encoding: "utf8" }
  );
  if (result.status !== 0) {
    throw new Error(`Failed to convert ${sourcePath}\n${result.stderr}`);
  }

  return {
    key,
    aliases: [...new Set([key, title, ...aliases])],
    title,
    imageUrl: `${assetBase}/${outputFile}`,
    sourceFile: basename(sourcePath),
    reviewFile: basename(reviewPath)
  };
});

writeFileSync(
  registryPath,
  `// Generated by tools/build_vireth_region_map_router_assets.mjs. Do not edit by hand.\nexport const GENERATED_REGION_MAPS = ${JSON.stringify(entries, null, 2)};\n`,
  "utf8"
);

console.log(
  JSON.stringify(
    {
      maps: entries.length,
      assetDir,
      registryPath
    },
    null,
    2
  )
);
