from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import asdict, dataclass
from pathlib import Path

from PIL import Image


EMOTION_CODES = {
    "neutral": "n",
    "faint_smile": "sm",
    "pleased": "p",
    "concerned": "c",
    "sad_resigned": "s",
    "restrained_anger": "a",
    "surprised_alert": "u",
    "measured_explanation": "x",
}

TARGET_SIZE = (560, 760)


@dataclass
class AssetRecord:
    character_id: str
    emotion: str
    code: str
    source: str
    output: str
    source_size: tuple[int, int]
    alpha_bbox: tuple[int, int, int, int]
    output_bytes: int
    output_sha256: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build normalized Worker WebP assets from approved transparent emotion PNGs."
    )
    parser.add_argument("--source-root", type=Path, required=True)
    parser.add_argument("--output-root", type=Path, required=True)
    parser.add_argument("--mapping-output", type=Path, required=True)
    parser.add_argument("--manifest-output", type=Path, required=True)
    parser.add_argument("--progress-output", type=Path)
    parser.add_argument("--quality", type=int, default=84)
    parser.add_argument("--method", type=int, choices=range(0, 7), default=4)
    return parser.parse_args()


def discover_character_directories(source_root: Path) -> list[Path]:
    directories = sorted(
        path
        for path in source_root.iterdir()
        if path.is_dir() and len(path.name) >= 5 and path.name[0] == "C" and path.name[1:4].isdigit()
    )
    if len(directories) != 100:
        raise RuntimeError(f"Expected 100 character directories, found {len(directories)}")
    return directories


def find_emotion_sources(character_dir: Path, character_id: str) -> dict[str, Path]:
    sources: dict[str, Path] = {}
    for emotion in EMOTION_CODES:
        matches = sorted(character_dir.glob(f"*_{character_id}_{emotion}.png"))
        if len(matches) != 1:
            raise RuntimeError(
                f"Expected one {emotion} PNG for {character_id}, found {len(matches)}"
            )
        sources[emotion] = matches[0]
    return sources


def normalize_transparent_asset(
    source: Path,
) -> tuple[Image.Image, tuple[int, int, int, int], tuple[int, int]]:
    with Image.open(source) as opened:
        rgba = opened.convert("RGBA")
        source_size = rgba.size
        alpha = rgba.getchannel("A")
        extrema = alpha.getextrema()
        if extrema[0] >= 255 or extrema[1] <= 0:
            raise RuntimeError(f"Source has no usable transparency: {source}")
        alpha_bbox = alpha.getbbox()
        if alpha_bbox is None:
            raise RuntimeError(f"Source alpha is empty: {source}")

        target_w, target_h = TARGET_SIZE
        scale = min(target_w / rgba.width, target_h / rgba.height)
        resized = rgba.resize(
            (max(1, round(rgba.width * scale)), max(1, round(rgba.height * scale))),
            Image.Resampling.LANCZOS,
        )
        canvas = Image.new("RGBA", TARGET_SIZE, (255, 255, 255, 0))
        paste_x = (target_w - resized.width) // 2
        paste_y = target_h - resized.height
        canvas.alpha_composite(resized, (paste_x, paste_y))
        return canvas, alpha_bbox, source_size


def write_mapping(mapping: dict[str, dict[str, str]], output: Path) -> None:
    generated = (
        "// Generated by tools/build_vireth_transparent_emotion_worker_assets.py. "
        "Do not edit by hand.\n"
        f"export const GENERATED_TALK_EMOTIONS = "
        f"{json.dumps(mapping, ensure_ascii=False, indent=2)} as const;\n"
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generated, encoding="utf-8")


def write_progress(
    output: Path | None,
    *,
    state: str,
    completed: int,
    total: int,
    current: str,
) -> None:
    if output is None:
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        json.dumps(
            {
                "state": state,
                "completed": completed,
                "total": total,
                "remaining": total - completed,
                "current": current,
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )


def main() -> None:
    args = parse_args()
    character_directories = discover_character_directories(args.source_root)
    total = len(character_directories) * len(EMOTION_CODES)
    completed = 0
    records: list[AssetRecord] = []
    mapping: dict[str, dict[str, str]] = {}
    write_progress(
        args.progress_output,
        state="running",
        completed=completed,
        total=total,
        current="",
    )

    for character_dir in character_directories:
        character_id = character_dir.name[:4].upper()
        sources = find_emotion_sources(character_dir, character_id)
        output_dir = args.output_root / character_id.lower()
        output_dir.mkdir(parents=True, exist_ok=True)
        mapping[character_id] = {}

        for emotion, code in EMOTION_CODES.items():
            source = sources[emotion]
            normalized, alpha_bbox, source_size = normalize_transparent_asset(source)
            output = output_dir / f"{code}.webp"
            normalized.save(output, "WEBP", quality=args.quality, method=args.method)
            output_bytes = output.stat().st_size
            if output_bytes > 120_000:
                raise RuntimeError(f"Output exceeds 120 KB target: {output} ({output_bytes})")

            mapping[character_id][code] = (
                f"/character-emotion-assets/{character_id.lower()}/{code}.webp"
            )
            records.append(
                AssetRecord(
                    character_id=character_id,
                    emotion=emotion,
                    code=code,
                    source=source.relative_to(args.source_root).as_posix(),
                    output=output.relative_to(args.output_root).as_posix(),
                    source_size=source_size,
                    alpha_bbox=alpha_bbox,
                    output_bytes=output_bytes,
                    output_sha256=hashlib.sha256(output.read_bytes()).hexdigest(),
                )
            )
            completed += 1
            write_progress(
                args.progress_output,
                state="running",
                completed=completed,
                total=total,
                current=f"{character_id}:{code}",
            )
            print(f"{completed}/{total} {character_id}:{code} {output_bytes} bytes")

    write_mapping(mapping, args.mapping_output)
    args.manifest_output.parent.mkdir(parents=True, exist_ok=True)
    args.manifest_output.write_text(
        json.dumps([asdict(record) for record in records], ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    write_progress(
        args.progress_output,
        state="completed",
        completed=completed,
        total=total,
        current="",
    )
    print(f"Wrote {completed} assets for {len(mapping)} characters")


if __name__ == "__main__":
    main()
