import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const WORKSPACE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE_CSV =
  "D:/OneDrive/444_비레스/00_최신본/02_지도/13_원형아이콘_대형라벨지도_v60/_data/ck5083-place-circle-label-placement-v1.csv";
const OUT_TS = path.join(WORKSPACE_ROOT, "workers/vireth-svg/src/generated-region-map-places.ts");
const OUT_MD = path.join(WORKSPACE_ROOT, "Arcadia_5083_지역지도_거점정렬_오른쪽위순_v1.md");

function parseCsv(text) {
  const rows = [];
  let row = [];
  let cell = "";
  let inQuotes = false;

  for (let i = 0; i < text.length; i += 1) {
    const char = text[i];
    const next = text[i + 1];

    if (char === '"') {
      if (inQuotes && next === '"') {
        cell += '"';
        i += 1;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }

    if (char === "," && !inQuotes) {
      row.push(cell);
      cell = "";
      continue;
    }

    if ((char === "\n" || char === "\r") && !inQuotes) {
      if (char === "\r" && next === "\n") {
        i += 1;
      }
      row.push(cell);
      if (row.some((value) => value.length > 0)) {
        rows.push(row);
      }
      row = [];
      cell = "";
      continue;
    }

    cell += char;
  }

  if (cell.length > 0 || row.length > 0) {
    row.push(cell);
    rows.push(row);
  }

  const [rawHeaders, ...body] = rows;
  const headers = rawHeaders.map((header) => header.replace(/^\uFEFF/, "").trim());
  return body.map((values) =>
    Object.fromEntries(headers.map((header, index) => [header, values[index] ?? ""]))
  );
}

function numberValue(value) {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) {
    throw new Error(`Invalid numeric value: ${value}`);
  }
  return parsed;
}

function round2(value) {
  return Math.round(value * 100) / 100;
}

function regionKeyFromOutput(output) {
  const match = output.match(/^\d+-([a-z-]+)-v60-circle-label-1600\.png$/);
  return match?.[1] ?? "";
}

const rows = parseCsv(fs.readFileSync(SOURCE_CSV, "utf8"));
const regionRows = rows.filter((row) => regionKeyFromOutput(row.output));

if (regionRows.length === 0) {
  throw new Error("No region-local v60 map placement rows found.");
}

const regions = new Map();
for (const row of regionRows) {
  const regionKey = regionKeyFromOutput(row.output);
  const outputOrder = Number(row.output.split("-")[0]);
  const entry = {
    regionKey,
    regionName: row.region,
    outputOrder,
    title: row.place,
    aliases: [row.place],
    kind: row.kind,
    icon: row.icon,
    gridX: numberValue(row.grid_x),
    gridY: numberValue(row.grid_y),
    pixelX: Math.round(numberValue(row.pixel_x)),
    pixelY: Math.round(numberValue(row.pixel_y)),
    mapXPct: round2((numberValue(row.pixel_x) / 1600) * 100),
    mapYPct: round2((numberValue(row.pixel_y) / 1600) * 100)
  };

  if (!regions.has(regionKey)) {
    regions.set(regionKey, {
      key: regionKey,
      name: row.region,
      outputOrder,
      places: []
    });
  }
  regions.get(regionKey).places.push(entry);
}

const sortedRegions = [...regions.values()].sort((a, b) => a.outputOrder - b.outputOrder);
const generatedPlaces = [];

for (const region of sortedRegions) {
  region.places.sort(
    (a, b) =>
      a.mapYPct - b.mapYPct ||
      b.mapXPct - a.mapXPct ||
      a.title.localeCompare(b.title, "ko")
  );
  region.places.forEach((place, index) => {
    generatedPlaces.push({
      ...place,
      order: index + 1
    });
  });
}

const ts = `// Generated by tools/build_vireth_region_map_place_index.mjs. Do not edit by hand.
export const GENERATED_REGION_MAP_PLACES = ${JSON.stringify(generatedPlaces, null, 2)};
`;

const md = [
  "# Arcadia 5083 지역지도 거점 정렬 인덱스",
  "",
  `- 원본 CSV: \`${SOURCE_CSV}\``,
  "- 기준: v60 지역별 1600px 지도에 찍힌 도시·마을·거점 좌표.",
  "- 정렬: 지도 상단에서 하단으로, 같은 높이에서는 오른쪽에서 왼쪽으로.",
  "- 좌표: 지역 지도 기준 픽셀과 퍼센트 좌표를 함께 기록.",
  "",
  ...sortedRegions.flatMap((region) => [
    `## ${region.name} (\`${region.key}\`) - ${region.places.length}개`,
    "",
    "| 순서 | 거점 | 분류 | 아이콘 | X% | Y% |",
    "|---:|---|---|---|---:|---:|",
    ...generatedPlaces
      .filter((place) => place.regionKey === region.key)
      .map(
        (place) =>
          `| ${place.order} | ${place.title} | ${place.kind} | ${place.icon} | ${place.mapXPct.toFixed(2)} | ${place.mapYPct.toFixed(2)} |`
      ),
    ""
  ])
].join("\n");

fs.writeFileSync(OUT_TS, ts, "utf8");
fs.writeFileSync(OUT_MD, md, "utf8");

console.log(
  JSON.stringify(
    {
      regions: sortedRegions.length,
      places: generatedPlaces.length,
      ts: OUT_TS,
      markdown: OUT_MD
    },
    null,
    2
  )
);
